//go:build go1.22

// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package public

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for GetMapWorldParamsAccept.
const (
	GetMapWorldParamsAcceptApplicationvndHollowcubeAnvil GetMapWorldParamsAccept = "application/vnd.hollowcube.anvil"
	GetMapWorldParamsAcceptApplicationvndHollowcubePolar GetMapWorldParamsAccept = "application/vnd.hollowcube.polar"
)

// Defines values for UpdateMapWorldParamsContentType.
const (
	UpdateMapWorldParamsContentTypeApplicationvndHollowcubeAnvil UpdateMapWorldParamsContentType = "application/vnd.hollowcube.anvil"
	UpdateMapWorldParamsContentTypeApplicationvndHollowcubePolar UpdateMapWorldParamsContentType = "application/vnd.hollowcube.polar"
)

// Point defines model for Point.
type Point struct {
	X float32 `json:"x"`
	Y float32 `json:"y"`
	Z float32 `json:"z"`
}

// Pos defines model for Pos.
type Pos struct {
	Pitch float32 `json:"pitch"`
	X     float32 `json:"x"`
	Y     float32 `json:"y"`
	Yaw   float32 `json:"yaw"`
	Z     float32 `json:"z"`
}

// CreateMapJSONBody defines parameters for CreateMap.
type CreateMapJSONBody struct {
	// ExtraData Extra metadata to store with the map
	ExtraData *map[string]interface{} `json:"extraData,omitempty"`

	// LegacyMapId The ID of the legacy map to import, or null if not any type of 'legacy' map
	LegacyMapId *string `json:"legacyMapId,omitempty"`

	// Name The name of the map
	Name string `json:"name"`

	// OrgId The ID of the organization who owns the map
	OrgId      string `json:"orgId"`
	SpawnPoint Pos    `json:"spawnPoint"`
}

// GetMapWorldParams defines parameters for GetMapWorld.
type GetMapWorldParams struct {
	// Accept The content type (world format) to return, defaults to Anvil (latest).
	Accept *GetMapWorldParamsAccept `json:"accept,omitempty"`
}

// GetMapWorldParamsAccept defines parameters for GetMapWorld.
type GetMapWorldParamsAccept string

// UpdateMapWorldParams defines parameters for UpdateMapWorld.
type UpdateMapWorldParams struct {
	// ContentType The content type (world format) being uploaded, defaults to Anvil (latest).
	ContentType *UpdateMapWorldParamsContentType `json:"content-type,omitempty"`
}

// UpdateMapWorldParamsContentType defines parameters for UpdateMapWorld.
type UpdateMapWorldParamsContentType string

// CreateMapJSONRequestBody defines body for CreateMap for application/json ContentType.
type CreateMapJSONRequestBody CreateMapJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new map
	// (POST /)
	CreateMap(w http.ResponseWriter, r *http.Request)
	// Fetch publicmap statistics
	// (GET /stats)
	GetMapStats(w http.ResponseWriter, r *http.Request)
	// Fetch a map world by ID
	// (GET /{mapId}/world)
	GetMapWorld(w http.ResponseWriter, r *http.Request, mapId string, params GetMapWorldParams)
	// Update a map world by ID
	// (PUT /{mapId}/world)
	UpdateMapWorld(w http.ResponseWriter, r *http.Request, mapId string, params UpdateMapWorldParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateMap operation middleware
func (siw *ServerInterfaceWrapper) CreateMap(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMap(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMapStats operation middleware
func (siw *ServerInterfaceWrapper) GetMapStats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMapStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMapWorld operation middleware
func (siw *ServerInterfaceWrapper) GetMapWorld(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "mapId" -------------
	var mapId string

	err = runtime.BindStyledParameterWithOptions("simple", "mapId", r.PathValue("mapId"), &mapId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mapId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMapWorldParams

	headers := r.Header

	// ------------- Optional header parameter "accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("accept")]; found {
		var Accept GetMapWorldParamsAccept
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "accept", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accept", Err: err})
			return
		}

		params.Accept = &Accept

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMapWorld(w, r, mapId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMapWorld operation middleware
func (siw *ServerInterfaceWrapper) UpdateMapWorld(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "mapId" -------------
	var mapId string

	err = runtime.BindStyledParameterWithOptions("simple", "mapId", r.PathValue("mapId"), &mapId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mapId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateMapWorldParams

	headers := r.Header

	// ------------- Optional header parameter "content-type" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("content-type")]; found {
		var ContentType UpdateMapWorldParamsContentType
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "content-type", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "content-type", valueList[0], &ContentType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "content-type", Err: err})
			return
		}

		params.ContentType = &ContentType

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMapWorld(w, r, mapId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/", wrapper.CreateMap)
	m.HandleFunc("GET "+options.BaseURL+"/stats", wrapper.GetMapStats)
	m.HandleFunc("GET "+options.BaseURL+"/{mapId}/world", wrapper.GetMapWorld)
	m.HandleFunc("PUT "+options.BaseURL+"/{mapId}/world", wrapper.UpdateMapWorld)

	return m
}

type CreateMapRequestObject struct {
	Body *CreateMapJSONRequestBody
}

type CreateMapResponseObject interface {
	VisitCreateMapResponse(w http.ResponseWriter) error
}

type CreateMap200JSONResponse map[string]interface{}

func (response CreateMap200JSONResponse) VisitCreateMapResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateMap404Response struct {
}

func (response CreateMap404Response) VisitCreateMapResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetMapStatsRequestObject struct {
}

type GetMapStatsResponseObject interface {
	VisitGetMapStatsResponse(w http.ResponseWriter) error
}

type GetMapStats200JSONResponse struct {
	// TotalFails The total number of failed maps
	TotalFails int `json:"totalFails"`

	// TotalMaps The total number of maps
	TotalMaps int `json:"totalMaps"`
}

func (response GetMapStats200JSONResponse) VisitGetMapStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMapWorldRequestObject struct {
	MapId  string `json:"mapId,omitempty"`
	Params GetMapWorldParams
}

type GetMapWorldResponseObject interface {
	VisitGetMapWorldResponse(w http.ResponseWriter) error
}

type GetMapWorld200ApplicationvndHollowcubeAnvilResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetMapWorld200ApplicationvndHollowcubeAnvilResponse) VisitGetMapWorldResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/vnd.hollowcube.anvil")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMapWorld200ApplicationvndHollowcubePolarResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetMapWorld200ApplicationvndHollowcubePolarResponse) VisitGetMapWorldResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/vnd.hollowcube.polar")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMapWorld204Response struct {
}

func (response GetMapWorld204Response) VisitGetMapWorldResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetMapWorld404Response struct {
}

func (response GetMapWorld404Response) VisitGetMapWorldResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateMapWorldRequestObject struct {
	MapId  string `json:"mapId,omitempty"`
	Params UpdateMapWorldParams
	Body   io.Reader
}

type UpdateMapWorldResponseObject interface {
	VisitUpdateMapWorldResponse(w http.ResponseWriter) error
}

type UpdateMapWorld204Response struct {
}

func (response UpdateMapWorld204Response) VisitUpdateMapWorldResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateMapWorld404Response struct {
}

func (response UpdateMapWorld404Response) VisitUpdateMapWorldResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a new map
	// (POST /)
	CreateMap(ctx context.Context, request CreateMapRequestObject) (CreateMapResponseObject, error)
	// Fetch publicmap statistics
	// (GET /stats)
	GetMapStats(ctx context.Context, request GetMapStatsRequestObject) (GetMapStatsResponseObject, error)
	// Fetch a map world by ID
	// (GET /{mapId}/world)
	GetMapWorld(ctx context.Context, request GetMapWorldRequestObject) (GetMapWorldResponseObject, error)
	// Update a map world by ID
	// (PUT /{mapId}/world)
	UpdateMapWorld(ctx context.Context, request UpdateMapWorldRequestObject) (UpdateMapWorldResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateMap operation middleware
func (sh *strictHandler) CreateMap(w http.ResponseWriter, r *http.Request) {
	var request CreateMapRequestObject

	var body CreateMapJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMap(ctx, request.(CreateMapRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMap")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateMapResponseObject); ok {
		if err := validResponse.VisitCreateMapResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMapStats operation middleware
func (sh *strictHandler) GetMapStats(w http.ResponseWriter, r *http.Request) {
	var request GetMapStatsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMapStats(ctx, request.(GetMapStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMapStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMapStatsResponseObject); ok {
		if err := validResponse.VisitGetMapStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMapWorld operation middleware
func (sh *strictHandler) GetMapWorld(w http.ResponseWriter, r *http.Request, mapId string, params GetMapWorldParams) {
	var request GetMapWorldRequestObject

	request.MapId = mapId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMapWorld(ctx, request.(GetMapWorldRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMapWorld")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMapWorldResponseObject); ok {
		if err := validResponse.VisitGetMapWorldResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMapWorld operation middleware
func (sh *strictHandler) UpdateMapWorld(w http.ResponseWriter, r *http.Request, mapId string, params UpdateMapWorldParams) {
	var request UpdateMapWorldRequestObject

	request.MapId = mapId
	request.Params = params

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMapWorld(ctx, request.(UpdateMapWorldRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMapWorld")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMapWorldResponseObject); ok {
		if err := validResponse.VisitUpdateMapWorldResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
