global:
  nameOverride: map-service
  fullnameOverride: map-service

base:
  image:
    repository: mworzala/map-service
  imagePullSecrets:
    - name: dockerio

  service:
    monitor:
      enabled: true
