// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: terraform.sql

package mapdb

import (
	"context"
)

const tfCreateSchematic = `-- name: TfCreateSchematic :exec
insert into tf_schematics (player_id, name, dimensions, size, filetype, schem_data)
values ($1, $2, $3, $4, $5, $6)
`

type TfCreateSchematicParams struct {
	PlayerID   string `json:"playerId"`
	Name       string `json:"name"`
	Dimensions int    `json:"dimensions"`
	Size       int    `json:"size"`
	Filetype   string `json:"filetype"`
	SchemData  []byte `json:"schemData"`
}

func (q *Queries) TfCreateSchematic(ctx context.Context, arg TfCreateSchematicParams) error {
	_, err := q.db.Exec(ctx, tfCreateSchematic,
		arg.PlayerID,
		arg.Name,
		arg.Dimensions,
		arg.Size,
		arg.Filetype,
		arg.SchemData,
	)
	return err
}

const tfDeleteSchematic = `-- name: TfDeleteSchematic :execrows
delete
from tf_schematics
where player_id = $1
  and name = $2
`

func (q *Queries) TfDeleteSchematic(ctx context.Context, playerID string, name string) (int64, error) {
	result, err := q.db.Exec(ctx, tfDeleteSchematic, playerID, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tfGetAllSchematics = `-- name: TfGetAllSchematics :many
select name, dimensions, size, filetype
from tf_schematics
where player_id = $1
`

type TfGetAllSchematicsRow struct {
	Name       string `json:"name"`
	Dimensions int    `json:"dimensions"`
	Size       int    `json:"size"`
	Filetype   string `json:"filetype"`
}

func (q *Queries) TfGetAllSchematics(ctx context.Context, playerID string) ([]TfGetAllSchematicsRow, error) {
	rows, err := q.db.Query(ctx, tfGetAllSchematics, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TfGetAllSchematicsRow{}
	for rows.Next() {
		var i TfGetAllSchematicsRow
		if err := rows.Scan(
			&i.Name,
			&i.Dimensions,
			&i.Size,
			&i.Filetype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tfGetLocalSession = `-- name: TfGetLocalSession :one
select state
from tf_local_session
where player_id = $1
  and world_id = $2
`

func (q *Queries) TfGetLocalSession(ctx context.Context, playerID string, worldID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, tfGetLocalSession, playerID, worldID)
	var state []byte
	err := row.Scan(&state)
	return state, err
}

const tfGetPlayerSession = `-- name: TfGetPlayerSession :one
select state
from tf_player_session
where player_id = $1
`

func (q *Queries) TfGetPlayerSession(ctx context.Context, playerID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, tfGetPlayerSession, playerID)
	var state []byte
	err := row.Scan(&state)
	return state, err
}

const tfGetSchematicData = `-- name: TfGetSchematicData :one
select schem_data
from tf_schematics
where player_id = $1
  and name = $2
`

func (q *Queries) TfGetSchematicData(ctx context.Context, playerID string, name string) ([]byte, error) {
	row := q.db.QueryRow(ctx, tfGetSchematicData, playerID, name)
	var schem_data []byte
	err := row.Scan(&schem_data)
	return schem_data, err
}

const tfUpdateSchematicHeader = `-- name: TfUpdateSchematicHeader :exec
update tf_schematics
set dimensions = $3,
    filetype   = $4
where player_id = $1
  and name = $2
`

type TfUpdateSchematicHeaderParams struct {
	PlayerID   string `json:"playerId"`
	Name       string `json:"name"`
	Dimensions int    `json:"dimensions"`
	Filetype   string `json:"filetype"`
}

func (q *Queries) TfUpdateSchematicHeader(ctx context.Context, arg TfUpdateSchematicHeaderParams) error {
	_, err := q.db.Exec(ctx, tfUpdateSchematicHeader,
		arg.PlayerID,
		arg.Name,
		arg.Dimensions,
		arg.Filetype,
	)
	return err
}

const tfUpsertLocalSession = `-- name: TfUpsertLocalSession :exec
insert into tf_local_session (player_id, world_id, state)
values ($1, $2, $3)
on conflict (player_id, world_id) do update
  set state = excluded.state
`

func (q *Queries) TfUpsertLocalSession(ctx context.Context, playerID string, worldID string, state []byte) error {
	_, err := q.db.Exec(ctx, tfUpsertLocalSession, playerID, worldID, state)
	return err
}

const tfUpsertPlayerSession = `-- name: TfUpsertPlayerSession :exec
insert into tf_player_session (player_id, state)
values ($1, $2)
on conflict (player_id) do update
  set state = excluded.state
`

func (q *Queries) TfUpsertPlayerSession(ctx context.Context, playerID string, state []byte) error {
	_, err := q.db.Exec(ctx, tfUpsertPlayerSession, playerID, state)
	return err
}
