// Code generated by MockGen. DO NOT EDIT.
// Source: authz.go
//
// Generated by this command:
//
//	mockgen -source=authz.go -destination=mock_authz/authz.gen.go
//

// Package mock_authz is a generated GoMock package.
package mock_authz

import (
	context "context"
	reflect "reflect"
	time "time"

	authz "github.com/hollow-cube/hc-services/services/player-service/internal/pkg/authz"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AppendHypercube mocks base method.
func (m *MockClient) AppendHypercube(ctx context.Context, playerId string, addedTerm time.Duration, cacheKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendHypercube", ctx, playerId, addedTerm, cacheKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendHypercube indicates an expected call of AppendHypercube.
func (mr *MockClientMockRecorder) AppendHypercube(ctx, playerId, addedTerm, cacheKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendHypercube", reflect.TypeOf((*MockClient)(nil).AppendHypercube), ctx, playerId, addedTerm, cacheKey)
}

// CheckPlatformPermission mocks base method.
func (m *MockClient) CheckPlatformPermission(ctx context.Context, userId, cacheKey string, perm authz.PlatformPermission) (authz.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPlatformPermission", ctx, userId, cacheKey, perm)
	ret0, _ := ret[0].(authz.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPlatformPermission indicates an expected call of CheckPlatformPermission.
func (mr *MockClientMockRecorder) CheckPlatformPermission(ctx, userId, cacheKey, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPlatformPermission", reflect.TypeOf((*MockClient)(nil).CheckPlatformPermission), ctx, userId, cacheKey, perm)
}

// GetHypercubeStats mocks base method.
func (m *MockClient) GetHypercubeStats(ctx context.Context, playerId, cacheKey string) (time.Time, time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHypercubeStats", ctx, playerId, cacheKey)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(time.Duration)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHypercubeStats indicates an expected call of GetHypercubeStats.
func (mr *MockClientMockRecorder) GetHypercubeStats(ctx, playerId, cacheKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHypercubeStats", reflect.TypeOf((*MockClient)(nil).GetHypercubeStats), ctx, playerId, cacheKey)
}
