replicaCount: 1

base:
  cluster: "prod"
  imagePullSecrets:
    - name: dockerio

  service:
    monitor:
      enabled: true

  env:
    SESSION_ENV: "prod"
    SESSION_HTTP_ADDRESS: "0.0.0.0"
    SESSION_HTTP_PORT: "9124"

    SESSION_POSTHOG_ENDPOINT: "http://api-server.mapmaker.svc.cluster.local:9124/posthog"

    SESSION_REDIS_ADDRESS: "redis-valkey.mapmaker:6379"
    SESSION_NATS_SERVERS: "nats://nats:4222"

    SESSION_OTLP_ENDPOINT: "tempo.monitoring.svc.cluster.local:4318"

    SESSION_S3_ENDPOINT: "https://bdb9cb2904188b760591dc1589a1ccf3.r2.cloudflarestorage.com"

    SESSION_DISCORD_APPLICATION_ID: "1086860126020964423"

    SESSION_KUBERNETES_NAMESPACE: "mapmaker"
