// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: map_players.sql

package db

import (
	"context"
)

const removeMapFromSlots = `-- name: RemoveMapFromSlots :many
update map_player_data
set maps = array_replace(maps, $1, '')
where $1 = any (maps)
returning id, unlocked_slots, maps, last_played_map, last_edited_map, contest_slot
`

func (q *Queries) RemoveMapFromSlots(ctx context.Context, arrayReplace interface{}) ([]MapPlayerData, error) {
	rows, err := q.db.Query(ctx, removeMapFromSlots, arrayReplace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapPlayerData{}
	for rows.Next() {
		var i MapPlayerData
		if err := rows.Scan(
			&i.ID,
			&i.UnlockedSlots,
			&i.Map,
			&i.LastPlayedMap,
			&i.LastEditedMap,
			&i.ContestSlot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsafe_GetPlayerData = `-- name: Unsafe_GetPlayerData :one
select id, unlocked_slots, maps, last_played_map, last_edited_map, contest_slot
from map_player_data
where id = $1
`

func (q *Queries) Unsafe_GetPlayerData(ctx context.Context, id string) (MapPlayerData, error) {
	row := q.db.QueryRow(ctx, unsafe_GetPlayerData, id)
	var i MapPlayerData
	err := row.Scan(
		&i.ID,
		&i.UnlockedSlots,
		&i.Map,
		&i.LastPlayedMap,
		&i.LastEditedMap,
		&i.ContestSlot,
	)
	return i, err
}

const upsertPlayerData = `-- name: UpsertPlayerData :exec
insert into map_player_data (id, unlocked_slots, maps, last_played_map, last_edited_map, contest_slot)
values ($1, $2, $3, $4, $5, $6)
on conflict (id) do update
  set maps=excluded.maps,
      last_played_map=excluded.last_played_map,
      last_edited_map=excluded.last_edited_map,
      contest_slot=excluded.contest_slot
`

type UpsertPlayerDataParams struct {
	ID            string   `json:"id"`
	UnlockedSlots int      `json:"unlockedSlots"`
	Map           []string `json:"maps"`
	LastPlayedMap *string  `json:"lastPlayedMap"`
	LastEditedMap *string  `json:"lastEditedMap"`
	ContestSlot   *string  `json:"contestSlot"`
}

func (q *Queries) UpsertPlayerData(ctx context.Context, arg UpsertPlayerDataParams) error {
	_, err := q.db.Exec(ctx, upsertPlayerData,
		arg.ID,
		arg.UnlockedSlots,
		arg.Map,
		arg.LastPlayedMap,
		arg.LastEditedMap,
		arg.ContestSlot,
	)
	return err
}
