// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: map_ratings.sql

package db

import (
	"context"
)

const getMapRatingForMapBy = `-- name: GetMapRatingForMapBy :one
select map_id, player_id, rating, comment
from map_ratings
where map_id = $1
  and player_id = $2
`

func (q *Queries) GetMapRatingForMapBy(ctx context.Context, mapID string, playerID string) (MapRating, error) {
	row := q.db.QueryRow(ctx, getMapRatingForMapBy, mapID, playerID)
	var i MapRating
	err := row.Scan(
		&i.MapID,
		&i.PlayerID,
		&i.Rating,
		&i.Comment,
	)
	return i, err
}

const upsertMapRating = `-- name: UpsertMapRating :exec
insert into map_ratings (map_id, player_id, rating)
values ($1, $2, $3)
on conflict (map_id, player_id) do update
  set rating = excluded.rating
`

func (q *Queries) UpsertMapRating(ctx context.Context, mapID string, playerID string, rating int) error {
	_, err := q.db.Exec(ctx, upsertMapRating, mapID, playerID, rating)
	return err
}
