// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: map_building.sql

package db

import (
	"context"
)

const getHeadCountWithCategory = `-- name: GetHeadCountWithCategory :one
select count(*) as head_count
from head_db
where category = $1::text
`

func (q *Queries) GetHeadCountWithCategory(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, getHeadCountWithCategory, dollar_1)
	var head_count int64
	err := row.Scan(&head_count)
	return head_count, err
}

const getHeadCountWithSearch = `-- name: GetHeadCountWithSearch :one
select count(*) as head_count
from head_db
where name ilike $1::text
`

func (q *Queries) GetHeadCountWithSearch(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, getHeadCountWithSearch, dollar_1)
	var head_count int64
	err := row.Scan(&head_count)
	return head_count, err
}

const getHeadsWithCategory = `-- name: GetHeadsWithCategory :many
select id, category, name, tags, texture
from head_db
where category = $1::text
limit $2 offset $3
`

func (q *Queries) GetHeadsWithCategory(ctx context.Context, column1 string, limit int32, offset int32) ([]HeadDb, error) {
	rows, err := q.db.Query(ctx, getHeadsWithCategory, column1, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeadDb{}
	for rows.Next() {
		var i HeadDb
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Name,
			&i.Tags,
			&i.Texture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHeadsWithSearch = `-- name: GetHeadsWithSearch :many
select id, category, name, tags, texture
from head_db
where name ilike $1::text
limit $2 offset $3
`

func (q *Queries) GetHeadsWithSearch(ctx context.Context, column1 string, limit int32, offset int32) ([]HeadDb, error) {
	rows, err := q.db.Query(ctx, getHeadsWithSearch, column1, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeadDb{}
	for rows.Next() {
		var i HeadDb
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Name,
			&i.Tags,
			&i.Texture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomHeads = `-- name: GetRandomHeads :many
select id, category, name, tags, texture
from head_db
order by random()
limit $1
`

func (q *Queries) GetRandomHeads(ctx context.Context, limit int32) ([]HeadDb, error) {
	rows, err := q.db.Query(ctx, getRandomHeads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeadDb{}
	for rows.Next() {
		var i HeadDb
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Name,
			&i.Tags,
			&i.Texture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
