// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maps.sql

package db

import (
	"context"
)

const countMaps = `-- name: CountMaps :one
select count(*)
from maps
where deleted_at is null
  and published_at is not null
`

func (q *Queries) CountMaps(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMaps)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMap = `-- name: CreateMap :one
insert into maps (id, owner, m_type, created_at, updated_at, authz_key, file_id, legacy_map_id, published_id,
                  published_at, opt_name, opt_icon,
                  opt_variant, opt_subvariant, opt_spawn_point, opt_extra, opt_tags, deleted_at, deleted_by,
                  deleted_reason, contest, size, protocol_version)
values ($1, $2, $3, now(), now(), '', '', '', null, null, coalesce($4, ''), coalesce($5, ''),
        $6, $7, $8, null, null, null, null, null, $9, $10, 769)
returning id, owner, m_type, created_at, updated_at, verification, authz_key, file_id, legacy_map_id, published_id, published_at, quality_override, opt_name, opt_icon, size, opt_variant, opt_subvariant, opt_spawn_point, opt_only_sprint, opt_no_sprint, opt_no_jump, opt_no_sneak, opt_boat, opt_extra, opt_tags, ext, deleted_at, deleted_by, deleted_reason, protocol_version, contest, listed
`

type CreateMapParams struct {
	ID            string      `json:"id"`
	Owner         string      `json:"owner"`
	MType         string      `json:"mType"`
	Column4       interface{} `json:"column4"`
	Column5       interface{} `json:"column5"`
	OptVariant    string      `json:"optVariant"`
	OptSubvariant *string     `json:"optSubvariant"`
	OptSpawnPoint Pos         `json:"optSpawnPoint"`
	Contest       *string     `json:"contest"`
	Size          int64       `json:"size"`
}

func (q *Queries) CreateMap(ctx context.Context, arg CreateMapParams) (Map, error) {
	row := q.db.QueryRow(ctx, createMap,
		arg.ID,
		arg.Owner,
		arg.MType,
		arg.Column4,
		arg.Column5,
		arg.OptVariant,
		arg.OptSubvariant,
		arg.OptSpawnPoint,
		arg.Contest,
		arg.Size,
	)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.MType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Verification,
		&i.AuthzKey,
		&i.FileID,
		&i.LegacyMapID,
		&i.PublishedID,
		&i.PublishedAt,
		&i.QualityOverride,
		&i.OptName,
		&i.OptIcon,
		&i.Size,
		&i.OptVariant,
		&i.OptSubvariant,
		&i.OptSpawnPoint,
		&i.OptOnlySprint,
		&i.OptNoSprint,
		&i.OptNoJump,
		&i.OptNoSneak,
		&i.OptBoat,
		&i.OptExtra,
		&i.OptTags,
		&i.Ext,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedReason,
		&i.ProtocolVersion,
		&i.Contest,
		&i.Listed,
	)
	return i, err
}

const deleteMapTagsNotIn = `-- name: DeleteMapTagsNotIn :exec
delete
from map_tags
where map_id = $1
  and tag != all ($2::map_tag[])
`

func (q *Queries) DeleteMapTagsNotIn(ctx context.Context, mapID string, tags []MapTag) error {
	_, err := q.db.Exec(ctx, deleteMapTagsNotIn, mapID, tags)
	return err
}

const getMapById = `-- name: GetMapById :one
select id, owner, m_type, created_at, updated_at, verification, authz_key, file_id, legacy_map_id, published_id, published_at, quality_override, opt_name, opt_icon, size, opt_variant, opt_subvariant, opt_spawn_point, opt_only_sprint, opt_no_sprint, opt_no_jump, opt_no_sneak, opt_boat, opt_extra, opt_tags, ext, deleted_at, deleted_by, deleted_reason, protocol_version, contest, listed
from maps
where deleted_at is null and id = $1
`

func (q *Queries) GetMapById(ctx context.Context, id string) (Map, error) {
	row := q.db.QueryRow(ctx, getMapById, id)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.MType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Verification,
		&i.AuthzKey,
		&i.FileID,
		&i.LegacyMapID,
		&i.PublishedID,
		&i.PublishedAt,
		&i.QualityOverride,
		&i.OptName,
		&i.OptIcon,
		&i.Size,
		&i.OptVariant,
		&i.OptSubvariant,
		&i.OptSpawnPoint,
		&i.OptOnlySprint,
		&i.OptNoSprint,
		&i.OptNoJump,
		&i.OptNoSneak,
		&i.OptBoat,
		&i.OptExtra,
		&i.OptTags,
		&i.Ext,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedReason,
		&i.ProtocolVersion,
		&i.Contest,
		&i.Listed,
	)
	return i, err
}

const getMapWithTagsById = `-- name: GetMapWithTagsById :one
select maps.id, maps.owner, maps.m_type, maps.created_at, maps.updated_at, maps.verification, maps.authz_key, maps.file_id, maps.legacy_map_id, maps.published_id, maps.published_at, maps.quality_override, maps.opt_name, maps.opt_icon, maps.size, maps.opt_variant, maps.opt_subvariant, maps.opt_spawn_point, maps.opt_only_sprint, maps.opt_no_sprint, maps.opt_no_jump, maps.opt_no_sneak, maps.opt_boat, maps.opt_extra, maps.opt_tags, maps.ext, maps.deleted_at, maps.deleted_by, maps.deleted_reason, maps.protocol_version, maps.contest, maps.listed, array(select tag from map_tags where map_id = maps.id order by index)::map_tag[] as tags
from maps
where deleted_at is null and id = $1
`

type GetMapWithTagsByIdRow struct {
	Map  Map      `json:"map"`
	Tags []MapTag `json:"tags"`
}

func (q *Queries) GetMapWithTagsById(ctx context.Context, id string) (GetMapWithTagsByIdRow, error) {
	row := q.db.QueryRow(ctx, getMapWithTagsById, id)
	var i GetMapWithTagsByIdRow
	err := row.Scan(
		&i.Map.ID,
		&i.Map.Owner,
		&i.Map.MType,
		&i.Map.CreatedAt,
		&i.Map.UpdatedAt,
		&i.Map.Verification,
		&i.Map.AuthzKey,
		&i.Map.FileID,
		&i.Map.LegacyMapID,
		&i.Map.PublishedID,
		&i.Map.PublishedAt,
		&i.Map.QualityOverride,
		&i.Map.OptName,
		&i.Map.OptIcon,
		&i.Map.Size,
		&i.Map.OptVariant,
		&i.Map.OptSubvariant,
		&i.Map.OptSpawnPoint,
		&i.Map.OptOnlySprint,
		&i.Map.OptNoSprint,
		&i.Map.OptNoJump,
		&i.Map.OptNoSneak,
		&i.Map.OptBoat,
		&i.Map.OptExtra,
		&i.Map.OptTags,
		&i.Map.Ext,
		&i.Map.DeletedAt,
		&i.Map.DeletedBy,
		&i.Map.DeletedReason,
		&i.Map.ProtocolVersion,
		&i.Map.Contest,
		&i.Map.Listed,
		&i.Tags,
	)
	return i, err
}

const getMultiMapProgress = `-- name: GetMultiMapProgress :many
with ranked_save_states as (select m.id::text as map_id,
                                   (case when ss.completed then 1 else 0 end)::int8 as completed,
                                   ss.playtime::int8 as playtime,
                                   ss.updated
                            from (select unnest($2::uuid[]) as id) m
                              left join
                            save_states ss
                            on
                              ss.map_id = m.id and ss.player_id = $1
                            where ss.deleted is null
                              and (ss.type = 'playing' or ss.type = 'verifying')),
     progress_and_playtime as (select map_id,
                                      coalesce(max(completed), 0) as progress,
                                      case
                                        when max(completed) = 1 then min(playtime) filter (where completed = 1)
                                        else (select playtime
                                              from ranked_save_states rss
                                              where rss.map_id = rs.map_id
                                              order by updated desc
                                              limit 1)
                                        end as playtime
                               from ranked_save_states rs
                               group by map_id)
select map_id::text as map_id,
       progress::int8 + 1 as progress,
       playtime::int8 as playtime
from progress_and_playtime
`

type GetMultiMapProgressRow struct {
	MapID    string `json:"mapId"`
	Progress int32  `json:"progress"`
	Playtime int64  `json:"playtime"`
}

func (q *Queries) GetMultiMapProgress(ctx context.Context, playerID string, column2 []string) ([]GetMultiMapProgressRow, error) {
	rows, err := q.db.Query(ctx, getMultiMapProgress, playerID, column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMultiMapProgressRow{}
	for rows.Next() {
		var i GetMultiMapProgressRow
		if err := rows.Scan(&i.MapID, &i.Progress, &i.Playtime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublishedMapById = `-- name: GetPublishedMapById :one
select id, owner, m_type, created_at, updated_at, verification, authz_key, file_id, legacy_map_id, published_id, published_at, quality_override, opt_name, opt_icon, size, opt_variant, opt_subvariant, opt_spawn_point, opt_only_sprint, opt_no_sprint, opt_no_jump, opt_no_sneak, opt_boat, opt_extra, opt_tags, ext, deleted_at, deleted_by, deleted_reason, protocol_version, contest, listed, tags, play_count, win_count, total_likes, clear_rate, difficulty
from maps_published
where id = $1
`

func (q *Queries) GetPublishedMapById(ctx context.Context, id string) (PublishedMap, error) {
	row := q.db.QueryRow(ctx, getPublishedMapById, id)
	var i PublishedMap
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.MType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Verification,
		&i.AuthzKey,
		&i.FileID,
		&i.LegacyMapID,
		&i.PublishedID,
		&i.PublishedAt,
		&i.QualityOverride,
		&i.OptName,
		&i.OptIcon,
		&i.Size,
		&i.OptVariant,
		&i.OptSubvariant,
		&i.OptSpawnPoint,
		&i.OptOnlySprint,
		&i.OptNoSprint,
		&i.OptNoJump,
		&i.OptNoSneak,
		&i.OptBoat,
		&i.OptExtra,
		&i.OptTags,
		&i.Ext,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedReason,
		&i.ProtocolVersion,
		&i.Contest,
		&i.Listed,
		&i.Tags,
		&i.PlayCount,
		&i.WinCount,
		&i.TotalLikes,
		&i.ClearRate,
		&i.Difficulty,
	)
	return i, err
}

const getPublishedMapByPublishedId = `-- name: GetPublishedMapByPublishedId :one
select id, owner, m_type, created_at, updated_at, verification, authz_key, file_id, legacy_map_id, published_id, published_at, quality_override, opt_name, opt_icon, size, opt_variant, opt_subvariant, opt_spawn_point, opt_only_sprint, opt_no_sprint, opt_no_jump, opt_no_sneak, opt_boat, opt_extra, opt_tags, ext, deleted_at, deleted_by, deleted_reason, protocol_version, contest, listed, tags, play_count, win_count, total_likes, clear_rate, difficulty
from maps_published
where published_id = $1
`

func (q *Queries) GetPublishedMapByPublishedId(ctx context.Context, publishedID *int) (PublishedMap, error) {
	row := q.db.QueryRow(ctx, getPublishedMapByPublishedId, publishedID)
	var i PublishedMap
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.MType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Verification,
		&i.AuthzKey,
		&i.FileID,
		&i.LegacyMapID,
		&i.PublishedID,
		&i.PublishedAt,
		&i.QualityOverride,
		&i.OptName,
		&i.OptIcon,
		&i.Size,
		&i.OptVariant,
		&i.OptSubvariant,
		&i.OptSpawnPoint,
		&i.OptOnlySprint,
		&i.OptNoSprint,
		&i.OptNoJump,
		&i.OptNoSneak,
		&i.OptBoat,
		&i.OptExtra,
		&i.OptTags,
		&i.Ext,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedReason,
		&i.ProtocolVersion,
		&i.Contest,
		&i.Listed,
		&i.Tags,
		&i.PlayCount,
		&i.WinCount,
		&i.TotalLikes,
		&i.ClearRate,
		&i.Difficulty,
	)
	return i, err
}

const insertMapReport = `-- name: InsertMapReport :one
insert into map_reports (map_id, player_id, time, categories, comment)
values ($1, $2, now(), $3, $4)
returning id, map_id, player_id, time, categories, comment
`

type InsertMapReportParams struct {
	MapID      string  `json:"mapId"`
	PlayerID   string  `json:"playerId"`
	Categories []int   `json:"categories"`
	Comment    *string `json:"comment"`
}

func (q *Queries) InsertMapReport(ctx context.Context, arg InsertMapReportParams) (MapReports, error) {
	row := q.db.QueryRow(ctx, insertMapReport,
		arg.MapID,
		arg.PlayerID,
		arg.Categories,
		arg.Comment,
	)
	var i MapReports
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.PlayerID,
		&i.Time,
		&i.Categories,
		&i.Comment,
	)
	return i, err
}

const multiGetMapWithTagsById = `-- name: MultiGetMapWithTagsById :many
select maps.id, maps.owner, maps.m_type, maps.created_at, maps.updated_at, maps.verification, maps.authz_key, maps.file_id, maps.legacy_map_id, maps.published_id, maps.published_at, maps.quality_override, maps.opt_name, maps.opt_icon, maps.size, maps.opt_variant, maps.opt_subvariant, maps.opt_spawn_point, maps.opt_only_sprint, maps.opt_no_sprint, maps.opt_no_jump, maps.opt_no_sneak, maps.opt_boat, maps.opt_extra, maps.opt_tags, maps.ext, maps.deleted_at, maps.deleted_by, maps.deleted_reason, maps.protocol_version, maps.contest, maps.listed, array(select tag from map_tags where map_id = maps.id order by index)::map_tag[] as tags
from maps
where id = any ($1::uuid[])
`

type MultiGetMapWithTagsByIdRow struct {
	Map  Map      `json:"map"`
	Tags []MapTag `json:"tags"`
}

func (q *Queries) MultiGetMapWithTagsById(ctx context.Context, dollar_1 []string) ([]MultiGetMapWithTagsByIdRow, error) {
	rows, err := q.db.Query(ctx, multiGetMapWithTagsById, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MultiGetMapWithTagsByIdRow{}
	for rows.Next() {
		var i MultiGetMapWithTagsByIdRow
		if err := rows.Scan(
			&i.Map.ID,
			&i.Map.Owner,
			&i.Map.MType,
			&i.Map.CreatedAt,
			&i.Map.UpdatedAt,
			&i.Map.Verification,
			&i.Map.AuthzKey,
			&i.Map.FileID,
			&i.Map.LegacyMapID,
			&i.Map.PublishedID,
			&i.Map.PublishedAt,
			&i.Map.QualityOverride,
			&i.Map.OptName,
			&i.Map.OptIcon,
			&i.Map.Size,
			&i.Map.OptVariant,
			&i.Map.OptSubvariant,
			&i.Map.OptSpawnPoint,
			&i.Map.OptOnlySprint,
			&i.Map.OptNoSprint,
			&i.Map.OptNoJump,
			&i.Map.OptNoSneak,
			&i.Map.OptBoat,
			&i.Map.OptExtra,
			&i.Map.OptTags,
			&i.Map.Ext,
			&i.Map.DeletedAt,
			&i.Map.DeletedBy,
			&i.Map.DeletedReason,
			&i.Map.ProtocolVersion,
			&i.Map.Contest,
			&i.Map.Listed,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const multiGetPublishedMapsById = `-- name: MultiGetPublishedMapsById :many
select id, owner, m_type, created_at, updated_at, verification, authz_key, file_id, legacy_map_id, published_id, published_at, quality_override, opt_name, opt_icon, size, opt_variant, opt_subvariant, opt_spawn_point, opt_only_sprint, opt_no_sprint, opt_no_jump, opt_no_sneak, opt_boat, opt_extra, opt_tags, ext, deleted_at, deleted_by, deleted_reason, protocol_version, contest, listed, tags, play_count, win_count, total_likes, clear_rate, difficulty
from maps_published
where id = any ($1::uuid[])
`

func (q *Queries) MultiGetPublishedMapsById(ctx context.Context, dollar_1 []string) ([]PublishedMap, error) {
	rows, err := q.db.Query(ctx, multiGetPublishedMapsById, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublishedMap{}
	for rows.Next() {
		var i PublishedMap
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.MType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Verification,
			&i.AuthzKey,
			&i.FileID,
			&i.LegacyMapID,
			&i.PublishedID,
			&i.PublishedAt,
			&i.QualityOverride,
			&i.OptName,
			&i.OptIcon,
			&i.Size,
			&i.OptVariant,
			&i.OptSubvariant,
			&i.OptSpawnPoint,
			&i.OptOnlySprint,
			&i.OptNoSprint,
			&i.OptNoJump,
			&i.OptNoSneak,
			&i.OptBoat,
			&i.OptExtra,
			&i.OptTags,
			&i.Ext,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeletedReason,
			&i.ProtocolVersion,
			&i.Contest,
			&i.Listed,
			&i.Tags,
			&i.PlayCount,
			&i.WinCount,
			&i.TotalLikes,
			&i.ClearRate,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishMap = `-- name: PublishMap :exec
update maps
set updated_at   = now(),
    published_at = now(),
    published_id = $2,
    contest      = $3
where id = $1
`

func (q *Queries) PublishMap(ctx context.Context, iD string, publishedID *int, contest *string) error {
	_, err := q.db.Exec(ctx, publishMap, iD, publishedID, contest)
	return err
}

const searchMaps = `-- name: SearchMaps :many
select maps_published.id, maps_published.owner, maps_published.m_type, maps_published.created_at, maps_published.updated_at, maps_published.verification, maps_published.authz_key, maps_published.file_id, maps_published.legacy_map_id, maps_published.published_id, maps_published.published_at, maps_published.quality_override, maps_published.opt_name, maps_published.opt_icon, maps_published.size, maps_published.opt_variant, maps_published.opt_subvariant, maps_published.opt_spawn_point, maps_published.opt_only_sprint, maps_published.opt_no_sprint, maps_published.opt_no_jump, maps_published.opt_no_sneak, maps_published.opt_boat, maps_published.opt_extra, maps_published.opt_tags, maps_published.ext, maps_published.deleted_at, maps_published.deleted_by, maps_published.deleted_reason, maps_published.protocol_version, maps_published.contest, maps_published.listed, maps_published.tags, maps_published.play_count, maps_published.win_count, maps_published.total_likes, maps_published.clear_rate, maps_published.difficulty,
       count(*) over () as total_count
from maps_published
where listed = true
  and opt_variant = any ($1::varchar[])
  and (owner = $2 or $2 is null)
  and (opt_name ilike $3::text or $3::text is null)
  and (contest = $4 or $4 is null)
  and (quality_override = any ($5::int[]) or coalesce(cardinality($5::int[]), 0) = 0)
  and (difficulty = any ($6::int[]) or coalesce(cardinality($6::int[]), 0) = 0)
order by case when $7::text = 'random' then random() end,
         case when $7::text = 'best' and $8::text = 'desc' then -quality_override end,
         case when $7::text = 'best' and $8::text = 'asc' then quality_override end,
         case when $7::text = 'best' then -total_likes end,
         case when $7::text = 'best' then extract(epoch from published_at) * -1 end,
         case
           when $7::text = 'published' and $8::text = 'desc' then extract(epoch from published_at) * -1 end,
         case when $7::text = 'published' and $8::text = 'asc' then extract(epoch from published_at) end
offset $9::int * $10::int limit $10::int
`

type SearchMapsParams struct {
	Variants   []string `json:"variants"`
	Owner      *string  `json:"owner"`
	Name       *string  `json:"name"`
	Contest    *string  `json:"contest"`
	Quality    []int    `json:"quality"`
	Difficulty []int    `json:"difficulty"`
	Sort       string   `json:"sort"`
	SortOrder  string   `json:"sortOrder"`
	Page       int      `json:"page"`
	PageSize   int      `json:"pageSize"`
}

type SearchMapsRow struct {
	PublishedMap PublishedMap `json:"publishedMap"`
	TotalCount   int64        `json:"totalCount"`
}

func (q *Queries) SearchMaps(ctx context.Context, arg SearchMapsParams) ([]SearchMapsRow, error) {
	rows, err := q.db.Query(ctx, searchMaps,
		arg.Variants,
		arg.Owner,
		arg.Name,
		arg.Contest,
		arg.Quality,
		arg.Difficulty,
		arg.Sort,
		arg.SortOrder,
		arg.Page,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMapsRow{}
	for rows.Next() {
		var i SearchMapsRow
		if err := rows.Scan(
			&i.PublishedMap.ID,
			&i.PublishedMap.Owner,
			&i.PublishedMap.MType,
			&i.PublishedMap.CreatedAt,
			&i.PublishedMap.UpdatedAt,
			&i.PublishedMap.Verification,
			&i.PublishedMap.AuthzKey,
			&i.PublishedMap.FileID,
			&i.PublishedMap.LegacyMapID,
			&i.PublishedMap.PublishedID,
			&i.PublishedMap.PublishedAt,
			&i.PublishedMap.QualityOverride,
			&i.PublishedMap.OptName,
			&i.PublishedMap.OptIcon,
			&i.PublishedMap.Size,
			&i.PublishedMap.OptVariant,
			&i.PublishedMap.OptSubvariant,
			&i.PublishedMap.OptSpawnPoint,
			&i.PublishedMap.OptOnlySprint,
			&i.PublishedMap.OptNoSprint,
			&i.PublishedMap.OptNoJump,
			&i.PublishedMap.OptNoSneak,
			&i.PublishedMap.OptBoat,
			&i.PublishedMap.OptExtra,
			&i.PublishedMap.OptTags,
			&i.PublishedMap.Ext,
			&i.PublishedMap.DeletedAt,
			&i.PublishedMap.DeletedBy,
			&i.PublishedMap.DeletedReason,
			&i.PublishedMap.ProtocolVersion,
			&i.PublishedMap.Contest,
			&i.PublishedMap.Listed,
			&i.PublishedMap.Tags,
			&i.PublishedMap.PlayCount,
			&i.PublishedMap.WinCount,
			&i.PublishedMap.TotalLikes,
			&i.PublishedMap.ClearRate,
			&i.PublishedMap.Difficulty,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsafe_DeleteMap = `-- name: Unsafe_DeleteMap :exec
update maps
set deleted_at     = now(),
    deleted_by     = $2,
    deleted_reason = $3
where id = $1
`

func (q *Queries) Unsafe_DeleteMap(ctx context.Context, iD string, deletedBy *string, deletedReason *string) error {
	_, err := q.db.Exec(ctx, unsafe_DeleteMap, iD, deletedBy, deletedReason)
	return err
}

const updateMap = `-- name: UpdateMap :exec
update maps
set opt_name         = $2,
    opt_icon         = $3,
    size             = $4,
    opt_variant      = $5,
    opt_subvariant   = $6,
    opt_spawn_point  = $7,
    ext              = $8,
    quality_override = $9,
    listed           = $10,
    protocol_version = $11,
    opt_only_sprint  = $12,
    opt_no_sprint    = $13,
    opt_no_jump      = $14,
    opt_no_sneak     = $15,
    opt_boat         = $16,
    opt_extra        = $17
where id = $1
`

type UpdateMapParams struct {
	ID              string  `json:"id"`
	Name            *string `json:"name"`
	Icon            *string `json:"icon"`
	Size            int64   `json:"size"`
	Variant         string  `json:"variant"`
	Subvariant      *string `json:"subvariant"`
	SpawnPoint      Pos     `json:"spawnPoint"`
	Ext             MapExt  `json:"ext"`
	Quality         *int64  `json:"quality"`
	Listed          bool    `json:"listed"`
	ProtocolVersion *int    `json:"protocolVersion"`
	OnlySprint      *bool   `json:"onlySprint"`
	NoSprint        *bool   `json:"noSprint"`
	NoJump          *bool   `json:"noJump"`
	NoSneak         *bool   `json:"noSneak"`
	Boat            *bool   `json:"boat"`
	Extra           []byte  `json:"extra"`
}

func (q *Queries) UpdateMap(ctx context.Context, arg UpdateMapParams) error {
	_, err := q.db.Exec(ctx, updateMap,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Size,
		arg.Variant,
		arg.Subvariant,
		arg.SpawnPoint,
		arg.Ext,
		arg.Quality,
		arg.Listed,
		arg.ProtocolVersion,
		arg.OnlySprint,
		arg.NoSprint,
		arg.NoJump,
		arg.NoSneak,
		arg.Boat,
		arg.Extra,
	)
	return err
}

const updateMapStats = `-- name: UpdateMapStats :exec
insert into map_stats (map_id, play_count, win_count)
select $1 as map_id,
       count(distinct player_id) as play_count,
       count(distinct case when completed then player_id end) as win_count
from save_states
where map_id = $1
on conflict (map_id) do update
  set play_count=excluded.play_count,
      win_count=excluded.win_count
`

func (q *Queries) UpdateMapStats(ctx context.Context, mapID string) error {
	_, err := q.db.Exec(ctx, updateMapStats, mapID)
	return err
}

const updateMapVerification = `-- name: UpdateMapVerification :exec
update maps
set verification     = $2,
    protocol_version = coalesce($3, protocol_version)
where id = $1
`

func (q *Queries) UpdateMapVerification(ctx context.Context, iD string, verification *int64, protocolVersion *int) error {
	_, err := q.db.Exec(ctx, updateMapVerification, iD, verification, protocolVersion)
	return err
}

const upsertMapTags = `-- name: UpsertMapTags :exec
insert into map_tags (map_id, tag, index)
select $1, tag, idx
from unnest($2::map_tag[]) with ordinality as t(tag, idx)
on conflict (map_id, tag) do update set index = excluded.index
`

func (q *Queries) UpsertMapTags(ctx context.Context, mapID string, tags []MapTag) error {
	_, err := q.db.Exec(ctx, upsertMapTags, mapID, tags)
	return err
}
