// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: maps.sql

package db

import (
	"context"
)

const countMaps = `-- name: CountMaps :one
select count(*)
from maps
where deleted_at is null
  and published_at is not null
`

func (q *Queries) CountMaps(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMaps)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMap = `-- name: CreateMap :one
insert into maps (id, owner, m_type, created_at, updated_at, authz_key, file_id, legacy_map_id, published_id,
                  published_at, opt_name, opt_icon,
                  opt_variant, opt_subvariant, opt_spawn_point, opt_extra, opt_tags, deleted_at, deleted_by,
                  deleted_reason, contest, size, protocol_version)
values ($1, $2, $3, now(), now(), '', '', '', null, null, '', '',
        $4, $5, $6, null, null, null, null, null, $7, $8, 769)
returning id, owner, m_type, created_at, updated_at, verification, authz_key, file_id, legacy_map_id, published_id, published_at, quality_override, opt_name, opt_icon, size, opt_variant, opt_subvariant, opt_spawn_point, opt_only_sprint, opt_no_sprint, opt_no_jump, opt_no_sneak, opt_boat, opt_extra, opt_tags, ext, deleted_at, deleted_by, deleted_reason, protocol_version, contest, listed
`

type CreateMapParams struct {
	ID            string  `json:"id"`
	Owner         string  `json:"owner"`
	MType         string  `json:"mType"`
	OptVariant    string  `json:"optVariant"`
	OptSubvariant *string `json:"optSubvariant"`
	OptSpawnPoint Pos     `json:"optSpawnPoint"`
	Contest       *string `json:"contest"`
	Size          int64   `json:"size"`
}

func (q *Queries) CreateMap(ctx context.Context, arg CreateMapParams) (Map, error) {
	row := q.db.QueryRow(ctx, createMap,
		arg.ID,
		arg.Owner,
		arg.MType,
		arg.OptVariant,
		arg.OptSubvariant,
		arg.OptSpawnPoint,
		arg.Contest,
		arg.Size,
	)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.MType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Verification,
		&i.AuthzKey,
		&i.FileID,
		&i.LegacyMapID,
		&i.PublishedID,
		&i.PublishedAt,
		&i.QualityOverride,
		&i.OptName,
		&i.OptIcon,
		&i.Size,
		&i.OptVariant,
		&i.OptSubvariant,
		&i.OptSpawnPoint,
		&i.OptOnlySprint,
		&i.OptNoSprint,
		&i.OptNoJump,
		&i.OptNoSneak,
		&i.OptBoat,
		&i.OptExtra,
		&i.OptTags,
		&i.Ext,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedReason,
		&i.ProtocolVersion,
		&i.Contest,
		&i.Listed,
	)
	return i, err
}

const getMapById = `-- name: GetMapById :one
select id, owner, m_type, created_at, updated_at, verification, authz_key, file_id, legacy_map_id, published_id, published_at, quality_override, opt_name, opt_icon, size, opt_variant, opt_subvariant, opt_spawn_point, opt_only_sprint, opt_no_sprint, opt_no_jump, opt_no_sneak, opt_boat, opt_extra, opt_tags, ext, deleted_at, deleted_by, deleted_reason, protocol_version, contest, listed
from maps
where id = $1
`

func (q *Queries) GetMapById(ctx context.Context, id string) (Map, error) {
	row := q.db.QueryRow(ctx, getMapById, id)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.MType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Verification,
		&i.AuthzKey,
		&i.FileID,
		&i.LegacyMapID,
		&i.PublishedID,
		&i.PublishedAt,
		&i.QualityOverride,
		&i.OptName,
		&i.OptIcon,
		&i.Size,
		&i.OptVariant,
		&i.OptSubvariant,
		&i.OptSpawnPoint,
		&i.OptOnlySprint,
		&i.OptNoSprint,
		&i.OptNoJump,
		&i.OptNoSneak,
		&i.OptBoat,
		&i.OptExtra,
		&i.OptTags,
		&i.Ext,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedReason,
		&i.ProtocolVersion,
		&i.Contest,
		&i.Listed,
	)
	return i, err
}

const getMultiMapProgress = `-- name: GetMultiMapProgress :many
with ranked_save_states as (select m.id::text as map_id,
                                   ss.completed::int8 as completed,
                                   ss.playtime::int8 as playtime,
                                   ss.updated
                            from (select unnest($2::uuid[]) as id) m
                              left join
                            save_states ss
                            on
                              ss.map_id = m.id and ss.player_id = $1
                            where ss.deleted is null
                              and (ss.type = 'playing' or ss.type = 'verifying')),
     progress_and_playtime as (select map_id,
                                      coalesce(max(completed), 0) as progress,
                                      case
                                        when max(completed) = 1 then min(playtime) filter (where completed = 1)
                                        else (select playtime
                                              from ranked_save_states rss
                                              where rss.map_id = rs.map_id
                                              order by updated desc
                                              limit 1)
                                        end as playtime
                               from ranked_save_states rs
                               group by map_id)
select map_id::text as map_id,
       progress::int8 + 1 as progress,
       playtime::int8 as playtime
from progress_and_playtime
`

type GetMultiMapProgressRow struct {
	MapID    string `json:"mapId"`
	Progress int32  `json:"progress"`
	Playtime int64  `json:"playtime"`
}

func (q *Queries) GetMultiMapProgress(ctx context.Context, playerID string, column2 []string) ([]GetMultiMapProgressRow, error) {
	rows, err := q.db.Query(ctx, getMultiMapProgress, playerID, column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMultiMapProgressRow{}
	for rows.Next() {
		var i GetMultiMapProgressRow
		if err := rows.Scan(&i.MapID, &i.Progress, &i.Playtime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublishedMapById = `-- name: GetPublishedMapById :one
select id, owner, m_type, created_at, updated_at, authz_key, verification, file_id, legacy_map_id, published_id, published_at, quality_override, opt_name, opt_icon, size, opt_variant, opt_subvariant, opt_spawn_point, opt_only_sprint, opt_no_sprint, opt_no_jump, opt_no_sneak, opt_boat, opt_extra, opt_tags, protocol_version, contest, listed, ext, play_count, win_count, total_likes, clear_rate, difficulty
from maps_published
where id = $1
`

func (q *Queries) GetPublishedMapById(ctx context.Context, id string) (PublishedMap, error) {
	row := q.db.QueryRow(ctx, getPublishedMapById, id)
	var i PublishedMap
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.MType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthzKey,
		&i.Verification,
		&i.FileID,
		&i.LegacyMapID,
		&i.PublishedID,
		&i.PublishedAt,
		&i.QualityOverride,
		&i.OptName,
		&i.OptIcon,
		&i.Size,
		&i.OptVariant,
		&i.OptSubvariant,
		&i.OptSpawnPoint,
		&i.OptOnlySprint,
		&i.OptNoSprint,
		&i.OptNoJump,
		&i.OptNoSneak,
		&i.OptBoat,
		&i.OptExtra,
		&i.OptTags,
		&i.ProtocolVersion,
		&i.Contest,
		&i.Listed,
		&i.Ext,
		&i.PlayCount,
		&i.WinCount,
		&i.TotalLikes,
		&i.ClearRate,
		&i.Difficulty,
	)
	return i, err
}

const getPublishedMapByPublishedId = `-- name: GetPublishedMapByPublishedId :one
select id, owner, m_type, created_at, updated_at, authz_key, verification, file_id, legacy_map_id, published_id, published_at, quality_override, opt_name, opt_icon, size, opt_variant, opt_subvariant, opt_spawn_point, opt_only_sprint, opt_no_sprint, opt_no_jump, opt_no_sneak, opt_boat, opt_extra, opt_tags, protocol_version, contest, listed, ext, play_count, win_count, total_likes, clear_rate, difficulty
from maps_published
where published_id = $1
`

func (q *Queries) GetPublishedMapByPublishedId(ctx context.Context, publishedID *int) (PublishedMap, error) {
	row := q.db.QueryRow(ctx, getPublishedMapByPublishedId, publishedID)
	var i PublishedMap
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.MType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthzKey,
		&i.Verification,
		&i.FileID,
		&i.LegacyMapID,
		&i.PublishedID,
		&i.PublishedAt,
		&i.QualityOverride,
		&i.OptName,
		&i.OptIcon,
		&i.Size,
		&i.OptVariant,
		&i.OptSubvariant,
		&i.OptSpawnPoint,
		&i.OptOnlySprint,
		&i.OptNoSprint,
		&i.OptNoJump,
		&i.OptNoSneak,
		&i.OptBoat,
		&i.OptExtra,
		&i.OptTags,
		&i.ProtocolVersion,
		&i.Contest,
		&i.Listed,
		&i.Ext,
		&i.PlayCount,
		&i.WinCount,
		&i.TotalLikes,
		&i.ClearRate,
		&i.Difficulty,
	)
	return i, err
}

const insertMapReport = `-- name: InsertMapReport :one
insert into map_reports (map_id, player_id, time, categories, comment)
values ($1, $2, now(), $3, $4)
returning id, map_id, player_id, time, categories, comment
`

type InsertMapReportParams struct {
	MapID      string  `json:"mapId"`
	PlayerID   string  `json:"playerId"`
	Categories []int   `json:"categories"`
	Comment    *string `json:"comment"`
}

func (q *Queries) InsertMapReport(ctx context.Context, arg InsertMapReportParams) (MapReport, error) {
	row := q.db.QueryRow(ctx, insertMapReport,
		arg.MapID,
		arg.PlayerID,
		arg.Categories,
		arg.Comment,
	)
	var i MapReport
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.PlayerID,
		&i.Time,
		&i.Categories,
		&i.Comment,
	)
	return i, err
}

const publishMap = `-- name: PublishMap :exec
update maps
set updated_at   = now(),
    published_at = now(),
    published_id = $2,
    contest      = $3
where id = $1
`

func (q *Queries) PublishMap(ctx context.Context, iD string, publishedID *int, contest *string) error {
	_, err := q.db.Exec(ctx, publishMap, iD, publishedID, contest)
	return err
}

const unsafe_DeleteMap = `-- name: Unsafe_DeleteMap :exec
update maps
set deleted_at     = now(),
    deleted_by     = $2,
    deleted_reason = $3
where id = $1
`

func (q *Queries) Unsafe_DeleteMap(ctx context.Context, iD string, deletedBy *string, deletedReason *string) error {
	_, err := q.db.Exec(ctx, unsafe_DeleteMap, iD, deletedBy, deletedReason)
	return err
}

const updateMapStats = `-- name: UpdateMapStats :exec
insert into map_stats (map_id, play_count, win_count)
select $1 as map_id,
       count(distinct player_id) as play_count,
       count(distinct case when completed then player_id end) as win_count
from save_states
where map_id = $1
on conflict (map_id) do update
  set play_count=excluded.play_count,
      win_count=excluded.win_count
`

func (q *Queries) UpdateMapStats(ctx context.Context, mapID string) error {
	_, err := q.db.Exec(ctx, updateMapStats, mapID)
	return err
}

const updateMapVerification = `-- name: UpdateMapVerification :exec
update maps
set verification = $2
where id = $1
`

func (q *Queries) UpdateMapVerification(ctx context.Context, iD string, verification *int64) error {
	_, err := q.db.Exec(ctx, updateMapVerification, iD, verification)
	return err
}
