// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type SaveStateType string

const (
	SaveStateTypeEditing   SaveStateType = "editing"
	SaveStateTypePlaying   SaveStateType = "playing"
	SaveStateTypeVerifying SaveStateType = "verifying"
)

func (e *SaveStateType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SaveStateType(s)
	case string:
		*e = SaveStateType(s)
	default:
		return fmt.Errorf("unsupported scan type for SaveStateType: %T", src)
	}
	return nil
}

type NullSaveStateType struct {
	SaveStateType SaveStateType `json:"saveStateType"`
	Valid         bool          `json:"valid"` // Valid is true if SaveStateType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSaveStateType) Scan(value interface{}) error {
	if value == nil {
		ns.SaveStateType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SaveStateType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSaveStateType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SaveStateType), nil
}

type Map struct {
	ID              string     `json:"id"`
	Owner           string     `json:"owner"`
	MType           string     `json:"mType"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
	Verification    *int64     `json:"verification"`
	AuthzKey        *string    `json:"authzKey"`
	FileID          string     `json:"fileId"`
	LegacyMapID     *string    `json:"legacyMapId"`
	PublishedID     *int       `json:"publishedId"`
	PublishedAt     *time.Time `json:"publishedAt"`
	QualityOverride *int64     `json:"qualityOverride"`
	OptName         *string    `json:"optName"`
	OptIcon         *string    `json:"optIcon"`
	Size            int64      `json:"size"`
	OptVariant      string     `json:"optVariant"`
	OptSubvariant   *string    `json:"optSubvariant"`
	OptSpawnPoint   Pos        `json:"optSpawnPoint"`
	OptOnlySprint   *bool      `json:"optOnlySprint"`
	OptNoSprint     *bool      `json:"optNoSprint"`
	OptNoJump       *bool      `json:"optNoJump"`
	OptNoSneak      *bool      `json:"optNoSneak"`
	OptBoat         *bool      `json:"optBoat"`
	OptExtra        []byte     `json:"optExtra"`
	OptTags         []string   `json:"optTags"`
	Ext             MapExt     `json:"ext"`
	DeletedAt       *time.Time `json:"deletedAt"`
	DeletedBy       *string    `json:"deletedBy"`
	DeletedReason   *string    `json:"deletedReason"`
	ProtocolVersion *int       `json:"protocolVersion"`
	Contest         *string    `json:"contest"`
	Listed          bool       `json:"listed"`
}

type MapPlayerData struct {
	ID            string   `json:"id"`
	UnlockedSlots int      `json:"unlockedSlots"`
	Maps          []string `json:"maps"`
	LastPlayedMap *string  `json:"lastPlayedMap"`
	LastEditedMap *string  `json:"lastEditedMap"`
	ContestSlot   *string  `json:"contestSlot"`
}

type MapRating struct {
	MapID    string  `json:"mapId"`
	PlayerID string  `json:"playerId"`
	Rating   int     `json:"rating"`
	Comment  *string `json:"comment"`
}

type MapReport struct {
	ID         int       `json:"id"`
	MapID      string    `json:"mapId"`
	PlayerID   string    `json:"playerId"`
	Time       time.Time `json:"time"`
	Categories []int     `json:"categories"`
	Comment    *string   `json:"comment"`
}

type PublishedMap struct {
	ID              string     `json:"id"`
	Owner           string     `json:"owner"`
	MType           string     `json:"mType"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
	AuthzKey        *string    `json:"authzKey"`
	Verification    *int64     `json:"verification"`
	FileID          string     `json:"fileId"`
	LegacyMapID     *string    `json:"legacyMapId"`
	PublishedID     *int       `json:"publishedId"`
	PublishedAt     *time.Time `json:"publishedAt"`
	QualityOverride *int64     `json:"qualityOverride"`
	OptName         *string    `json:"optName"`
	OptIcon         *string    `json:"optIcon"`
	Size            int64      `json:"size"`
	OptVariant      string     `json:"optVariant"`
	OptSubvariant   *string    `json:"optSubvariant"`
	OptSpawnPoint   Pos        `json:"optSpawnPoint"`
	OptOnlySprint   *bool      `json:"optOnlySprint"`
	OptNoSprint     *bool      `json:"optNoSprint"`
	OptNoJump       *bool      `json:"optNoJump"`
	OptNoSneak      *bool      `json:"optNoSneak"`
	OptBoat         *bool      `json:"optBoat"`
	OptExtra        []byte     `json:"optExtra"`
	OptTags         []string   `json:"optTags"`
	ProtocolVersion *int       `json:"protocolVersion"`
	Contest         *string    `json:"contest"`
	Listed          bool       `json:"listed"`
	Ext             MapExt     `json:"ext"`
	PlayCount       int        `json:"playCount"`
	WinCount        int        `json:"winCount"`
	TotalLikes      int64      `json:"totalLikes"`
	ClearRate       float64    `json:"clearRate"`
	Difficulty      int32      `json:"difficulty"`
}

type SaveState struct {
	ID              string        `json:"id"`
	MapID           string        `json:"mapId"`
	PlayerID        string        `json:"playerId"`
	Type            SaveStateType `json:"type"`
	Created         time.Time     `json:"created"`
	Updated         time.Time     `json:"updated"`
	Deleted         *time.Time    `json:"deleted"`
	Completed       bool          `json:"completed"`
	Playtime        int           `json:"playtime"`
	StateV2         []byte        `json:"stateV2"`
	DataVersion     int           `json:"dataVersion"`
	ProtocolVersion *int          `json:"protocolVersion"`
	Ticks           int           `json:"ticks"`
}
