// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type SaveStateType string

const (
	SaveStateTypeEditing   SaveStateType = "editing"
	SaveStateTypePlaying   SaveStateType = "playing"
	SaveStateTypeVerifying SaveStateType = "verifying"
)

func (e *SaveStateType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SaveStateType(s)
	case string:
		*e = SaveStateType(s)
	default:
		return fmt.Errorf("unsupported scan type for SaveStateType: %T", src)
	}
	return nil
}

type NullSaveStateType struct {
	SaveStateType SaveStateType
	Valid         bool // Valid is true if SaveStateType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSaveStateType) Scan(value interface{}) error {
	if value == nil {
		ns.SaveStateType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SaveStateType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSaveStateType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SaveStateType), nil
}

type Map struct {
	ID              string
	Owner           string
	MType           string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Verification    *int64
	AuthzKey        *string
	FileID          string
	LegacyMapID     *string
	PublishedID     *int
	PublishedAt     *time.Time
	QualityOverride *int64
	OptName         *string
	OptIcon         *string
	Size            int64
	OptVariant      string
	OptSubvariant   *string
	OptSpawnPoint   string
	OptOnlySprint   *bool
	OptNoSprint     *bool
	OptNoJump       *bool
	OptNoSneak      *bool
	OptBoat         *bool
	OptExtra        []byte
	OptTags         []string
	Ext             []byte
	DeletedAt       *time.Time
	DeletedBy       pgtype.UUID
	DeletedReason   *string
	ProtocolVersion *int
	Contest         pgtype.UUID
	Listed          bool
}

type SaveState struct {
	ID              string
	MapID           string
	PlayerID        string
	Type            SaveStateType
	Created         time.Time
	Updated         time.Time
	Deleted         *time.Time
	Completed       bool
	Playtime        int
	StateV2         []byte
	DataVersion     int
	ProtocolVersion *int
	Ticks           int
}
