// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: save_states.sql

package db

import (
	"context"
	"time"
)

const countFailSaveStates = `-- name: CountFailSaveStates :one
select count(*)
from save_states
where type = 'playing'
  and completed = false
`

func (q *Queries) CountFailSaveStates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFailSaveStates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSaveState = `-- name: CreateSaveState :one
insert into save_states (id, map_id, player_id, type, created, updated, completed, playtime, data_version,
                         state_v2, protocol_version)
values (gen_random_uuid(), $1, $2, $3, now(), now(), false, 0, 0, 'null', $4)
returning id, map_id, player_id, type, created, updated, deleted, completed, playtime, state_v2, data_version, protocol_version, ticks
`

type CreateSaveStateParams struct {
	MapID           string        `json:"mapId"`
	PlayerID        string        `json:"playerId"`
	Type            SaveStateType `json:"type"`
	ProtocolVersion *int          `json:"protocolVersion"`
}

func (q *Queries) CreateSaveState(ctx context.Context, arg CreateSaveStateParams) (SaveState, error) {
	row := q.db.QueryRow(ctx, createSaveState,
		arg.MapID,
		arg.PlayerID,
		arg.Type,
		arg.ProtocolVersion,
	)
	var i SaveState
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.PlayerID,
		&i.Type,
		&i.Created,
		&i.Updated,
		&i.Deleted,
		&i.Completed,
		&i.Playtime,
		&i.StateV2,
		&i.DataVersion,
		&i.ProtocolVersion,
		&i.Ticks,
	)
	return i, err
}

const deleteVerifyingStates = `-- name: DeleteVerifyingStates :exec
delete
from save_states
where map_id = $1
  and type = 'verifying'
`

func (q *Queries) DeleteVerifyingStates(ctx context.Context, mapID string) error {
	_, err := q.db.Exec(ctx, deleteVerifyingStates, mapID)
	return err
}

const getSaveState = `-- name: GetSaveState :one
select id, map_id, player_id, type, created, updated, deleted, completed, playtime, state_v2, data_version, protocol_version, ticks
from public.save_states
where deleted is null
  and id = $1
  and map_id = $2
  and player_id = $3
`

func (q *Queries) GetSaveState(ctx context.Context, iD string, mapID string, playerID string) (SaveState, error) {
	row := q.db.QueryRow(ctx, getSaveState, iD, mapID, playerID)
	var i SaveState
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.PlayerID,
		&i.Type,
		&i.Created,
		&i.Updated,
		&i.Deleted,
		&i.Completed,
		&i.Playtime,
		&i.StateV2,
		&i.DataVersion,
		&i.ProtocolVersion,
		&i.Ticks,
	)
	return i, err
}

const unsafe_DeleteMapSaveStates = `-- name: Unsafe_DeleteMapSaveStates :exec
update save_states
set deleted = now()
where map_id = $1
`

func (q *Queries) Unsafe_DeleteMapSaveStates(ctx context.Context, mapID string) error {
	_, err := q.db.Exec(ctx, unsafe_DeleteMapSaveStates, mapID)
	return err
}

const upsertSaveState = `-- name: UpsertSaveState :exec
insert into public.save_states
(id, map_id, player_id, type, created, updated, completed, playtime, ticks, state_v2, data_version, protocol_version)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
on conflict (id, map_id, player_id) do update
  set updated          = excluded.updated,
      completed        = excluded.completed,
      playtime         = excluded.playtime,
      ticks            = excluded.ticks,
      state_v2         = excluded.state_v2,
      data_version     = excluded.data_version,
      protocol_version = excluded.protocol_version
`

type UpsertSaveStateParams struct {
	ID              string        `json:"id"`
	MapID           string        `json:"mapId"`
	PlayerID        string        `json:"playerId"`
	Type            SaveStateType `json:"type"`
	Created         time.Time     `json:"created"`
	Updated         time.Time     `json:"updated"`
	Completed       bool          `json:"completed"`
	Playtime        int           `json:"playtime"`
	Ticks           int           `json:"ticks"`
	StateV2         []byte        `json:"stateV2"`
	DataVersion     int           `json:"dataVersion"`
	ProtocolVersion *int          `json:"protocolVersion"`
}

func (q *Queries) UpsertSaveState(ctx context.Context, arg UpsertSaveStateParams) error {
	_, err := q.db.Exec(ctx, upsertSaveState,
		arg.ID,
		arg.MapID,
		arg.PlayerID,
		arg.Type,
		arg.Created,
		arg.Updated,
		arg.Completed,
		arg.Playtime,
		arg.Ticks,
		arg.StateV2,
		arg.DataVersion,
		arg.ProtocolVersion,
	)
	return err
}
