// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: save_states.sql

package db

import (
	"context"
	"time"
)

const getSaveState = `-- name: GetSaveState :one
select id, map_id, player_id, type, created, updated, deleted, completed, playtime, state_v2, data_version, protocol_version, ticks
from public.save_states
where deleted is null
  and id = $1
  and map_id = $2
  and player_id = $3
`

func (q *Queries) GetSaveState(ctx context.Context, iD string, mapID string, playerID string) (*SaveState, error) {
	row := q.db.QueryRow(ctx, getSaveState, iD, mapID, playerID)
	var i SaveState
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.PlayerID,
		&i.Type,
		&i.Created,
		&i.Updated,
		&i.Deleted,
		&i.Completed,
		&i.Playtime,
		&i.StateV2,
		&i.DataVersion,
		&i.ProtocolVersion,
		&i.Ticks,
	)
	return &i, err
}

const upsertSaveState = `-- name: UpsertSaveState :exec
insert into public.save_states
(id, map_id, player_id, type, created, updated, completed, playtime, ticks, state_v2, data_version, protocol_version)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
on conflict (id, map_id, player_id) do update
  set updated          = excluded.updated,
      completed        = excluded.completed,
      playtime         = excluded.playtime,
      ticks            = excluded.ticks,
      state_v2         = excluded.state_v2,
      data_version     = excluded.data_version,
      protocol_version = excluded.protocol_version
`

type UpsertSaveStateParams struct {
	ID              string
	MapID           string
	PlayerID        string
	Type            SaveStateType
	Created         time.Time
	Updated         time.Time
	Completed       bool
	Playtime        int
	Ticks           int
	StateV2         []byte
	DataVersion     int
	ProtocolVersion *int
}

func (q *Queries) UpsertSaveState(ctx context.Context, arg UpsertSaveStateParams) error {
	_, err := q.db.Exec(ctx, upsertSaveState,
		arg.ID,
		arg.MapID,
		arg.PlayerID,
		arg.Type,
		arg.Created,
		arg.Updated,
		arg.Completed,
		arg.Playtime,
		arg.Ticks,
		arg.StateV2,
		arg.DataVersion,
		arg.ProtocolVersion,
	)
	return err
}
