// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: terraform.sql

package db

import (
	"context"
)

const tfGetPlayerSession = `-- name: TfGetPlayerSession :one
select state
from tf_player_session
where player_id = $1
`

func (q *Queries) TfGetPlayerSession(ctx context.Context, playerID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, tfGetPlayerSession, playerID)
	var state []byte
	err := row.Scan(&state)
	return state, err
}
