//go:build go1.22

// Package intnl provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package intnl

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for MapInviteInviteType.
const (
	Invite  MapInviteInviteType = "invite"
	Request MapInviteInviteType = "request"
)

// InviteError defines model for InviteError.
type InviteError struct {
	ErrorCode float32 `json:"errorCode"`
	ErrorText string  `json:"errorText"`
}

// IsolateOverride defines model for IsolateOverride.
type IsolateOverride struct {
	Id          string    `json:"id"`
	LastUpdated time.Time `json:"lastUpdated"`
}

// MapInvite defines model for MapInvite.
type MapInvite struct {
	InviteType  MapInviteInviteType `json:"inviteType"`
	MapId       string              `json:"mapId"`
	RecipientId string              `json:"recipientId"`
	SenderId    string              `json:"senderId"`
	Time        int                 `json:"time"`
}

// MapInviteInviteType defines model for MapInvite.InviteType.
type MapInviteInviteType string

// PlayerSession defines model for PlayerSession.
type PlayerSession struct {
	CreatedAt string      `json:"createdAt"`
	Hidden    bool        `json:"hidden"`
	PlayerId  string      `json:"playerId"`
	Presence  Presence    `json:"presence"`
	ProxyId   string      `json:"proxyId"`
	ServerId  string      `json:"serverId"`
	Skin      *PlayerSkin `json:"skin,omitempty"`
	Username  string      `json:"username"`
}

// PlayerSkin defines model for PlayerSkin.
type PlayerSkin struct {
	Signature string `json:"signature"`
	Texture   string `json:"texture"`
}

// Presence defines model for Presence.
type Presence struct {
	InstanceId string `json:"instanceId"`
	MapId      string `json:"mapId"`
	State      string `json:"state"`
	Type       string `json:"type"`
}

// SessionList defines model for SessionList.
type SessionList = []PlayerSession

// PlayerId defines model for PlayerId.
type PlayerId = string

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Error string `json:"error"`
}

// BannedSessionResponse Ban object from player service.
type BannedSessionResponse map[string]interface{}

// CreatedSessionResponse PlayerData object from the player service
type CreatedSessionResponse = map[string]interface{}

// MapJoinSuccess defines model for MapJoinSuccess.
type MapJoinSuccess struct {
	Server          string `json:"server"`
	ServerClusterIP string `json:"serverClusterIP"`
}

// SessionData defines model for SessionData.
type SessionData = PlayerSession

// TransferSessionResponse defines model for TransferSessionResponse.
type TransferSessionResponse struct {
	// Data PlayerData object from the player service
	Data    map[string]interface{} `json:"data"`
	IsJoin  bool                   `json:"isJoin"`
	Session PlayerSession          `json:"session"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	ConnectedHost   *string     `json:"connectedHost,omitempty"`
	Ip              string      `json:"ip"`
	ProtocolVersion *int        `json:"protocolVersion,omitempty"`
	Proxy           string      `json:"proxy"`
	Skin            *PlayerSkin `json:"skin,omitempty"`
	Username        string      `json:"username"`
	Version         *string     `json:"version,omitempty"`
}

// TransferSessionRequest defines model for TransferSessionRequest.
type TransferSessionRequest struct {
	Map    string `json:"map"`
	Server string `json:"server"`
	State  string `json:"state"`
	Type   string `json:"type"`
}

// UpdateSession defines model for UpdateSession.
type UpdateSession struct {
	Hidden   *bool                   `json:"hidden,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// AcceptMapInviteOrRequestJSONBody defines parameters for AcceptMapInviteOrRequest.
type AcceptMapInviteOrRequestJSONBody struct {
	SenderId string `json:"senderId"`
	TargetId string `json:"targetId"`
}

// RejectMapInviteOrRequestJSONBody defines parameters for RejectMapInviteOrRequest.
type RejectMapInviteOrRequestJSONBody struct {
	SenderId string `json:"senderId"`
	TargetId string `json:"targetId"`
}

// JoinHubJSONBody defines parameters for JoinHub.
type JoinHubJSONBody struct {
	Exclude *string `json:"exclude,omitempty"`
}

// JoinMapJSONBody defines parameters for JoinMap.
type JoinMapJSONBody struct {
	Isolate *struct {
		Override *string `json:"override,omitempty"`
	} `json:"isolate,omitempty"`
	Map    string `json:"map"`
	Player string `json:"player"`
	Source string `json:"source"`
	State  string `json:"state"`
}

// UpdateSessionPropertiesJSONBody defines parameters for UpdateSessionProperties.
type UpdateSessionPropertiesJSONBody struct {
	Hidden   *bool                   `json:"hidden,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// CreateSessionJSONBody defines parameters for CreateSession.
type CreateSessionJSONBody struct {
	ConnectedHost   *string     `json:"connectedHost,omitempty"`
	Ip              string      `json:"ip"`
	ProtocolVersion *int        `json:"protocolVersion,omitempty"`
	Proxy           string      `json:"proxy"`
	Skin            *PlayerSkin `json:"skin,omitempty"`
	Username        string      `json:"username"`
	Version         *string     `json:"version,omitempty"`
}

// TransferSessionJSONBody defines parameters for TransferSession.
type TransferSessionJSONBody struct {
	Map    string `json:"map"`
	Server string `json:"server"`
	State  string `json:"state"`
	Type   string `json:"type"`
}

// AcceptMapInviteOrRequestJSONRequestBody defines body for AcceptMapInviteOrRequest for application/json ContentType.
type AcceptMapInviteOrRequestJSONRequestBody AcceptMapInviteOrRequestJSONBody

// InviteToMapJSONRequestBody defines body for InviteToMap for application/json ContentType.
type InviteToMapJSONRequestBody = MapInvite

// RejectMapInviteOrRequestJSONRequestBody defines body for RejectMapInviteOrRequest for application/json ContentType.
type RejectMapInviteOrRequestJSONRequestBody RejectMapInviteOrRequestJSONBody

// RequestToJoinMapJSONRequestBody defines body for RequestToJoinMap for application/json ContentType.
type RequestToJoinMapJSONRequestBody = MapInvite

// JoinHubJSONRequestBody defines body for JoinHub for application/json ContentType.
type JoinHubJSONRequestBody JoinHubJSONBody

// JoinMapJSONRequestBody defines body for JoinMap for application/json ContentType.
type JoinMapJSONRequestBody JoinMapJSONBody

// UpdateSessionPropertiesJSONRequestBody defines body for UpdateSessionProperties for application/json ContentType.
type UpdateSessionPropertiesJSONRequestBody UpdateSessionPropertiesJSONBody

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody CreateSessionJSONBody

// TransferSessionJSONRequestBody defines body for TransferSession for application/json ContentType.
type TransferSessionJSONRequestBody TransferSessionJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Accept a map invite or map join request
	// (POST /invites/map/accept)
	AcceptMapInviteOrRequest(w http.ResponseWriter, r *http.Request)
	// Invite a player to a map
	// (POST /invites/map/invite)
	InviteToMap(w http.ResponseWriter, r *http.Request)
	// Reject a map invite or map join request
	// (POST /invites/map/reject)
	RejectMapInviteOrRequest(w http.ResponseWriter, r *http.Request)
	// Request to join a map
	// (POST /invites/map/request)
	RequestToJoinMap(w http.ResponseWriter, r *http.Request)
	// Join a hub
	// (POST /join_hub)
	JoinHub(w http.ResponseWriter, r *http.Request)
	// Join a map
	// (POST /join_map)
	JoinMap(w http.ResponseWriter, r *http.Request)

	// (GET /server/isolate-overrides)
	GetIsolateOverrides(w http.ResponseWriter, r *http.Request)
	// An endpoint for a starting server to sync its session state
	// (POST /server/sync)
	SyncServer(w http.ResponseWriter, r *http.Request)
	// Delete a session for the given player id
	// (DELETE /session/{playerId})
	DeleteSession(w http.ResponseWriter, r *http.Request, playerId string)
	// Update a session's properties
	// (PATCH /session/{playerId})
	UpdateSessionProperties(w http.ResponseWriter, r *http.Request, playerId PlayerId)
	// Create a new session
	// (POST /session/{playerId})
	CreateSession(w http.ResponseWriter, r *http.Request, playerId PlayerId)
	// Transfer a session to a new server
	// (PUT /session/{playerId})
	TransferSession(w http.ResponseWriter, r *http.Request, playerId PlayerId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AcceptMapInviteOrRequest operation middleware
func (siw *ServerInterfaceWrapper) AcceptMapInviteOrRequest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptMapInviteOrRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InviteToMap operation middleware
func (siw *ServerInterfaceWrapper) InviteToMap(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InviteToMap(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectMapInviteOrRequest operation middleware
func (siw *ServerInterfaceWrapper) RejectMapInviteOrRequest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectMapInviteOrRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestToJoinMap operation middleware
func (siw *ServerInterfaceWrapper) RequestToJoinMap(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestToJoinMap(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinHub operation middleware
func (siw *ServerInterfaceWrapper) JoinHub(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinHub(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinMap operation middleware
func (siw *ServerInterfaceWrapper) JoinMap(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinMap(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIsolateOverrides operation middleware
func (siw *ServerInterfaceWrapper) GetIsolateOverrides(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIsolateOverrides(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncServer operation middleware
func (siw *ServerInterfaceWrapper) SyncServer(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncServer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId string

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r, playerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSessionProperties operation middleware
func (siw *ServerInterfaceWrapper) UpdateSessionProperties(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId PlayerId

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSessionProperties(w, r, playerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId PlayerId

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r, playerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TransferSession operation middleware
func (siw *ServerInterfaceWrapper) TransferSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId PlayerId

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TransferSession(w, r, playerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/invites/map/accept", wrapper.AcceptMapInviteOrRequest)
	m.HandleFunc("POST "+options.BaseURL+"/invites/map/invite", wrapper.InviteToMap)
	m.HandleFunc("POST "+options.BaseURL+"/invites/map/reject", wrapper.RejectMapInviteOrRequest)
	m.HandleFunc("POST "+options.BaseURL+"/invites/map/request", wrapper.RequestToJoinMap)
	m.HandleFunc("POST "+options.BaseURL+"/join_hub", wrapper.JoinHub)
	m.HandleFunc("POST "+options.BaseURL+"/join_map", wrapper.JoinMap)
	m.HandleFunc("GET "+options.BaseURL+"/server/isolate-overrides", wrapper.GetIsolateOverrides)
	m.HandleFunc("POST "+options.BaseURL+"/server/sync", wrapper.SyncServer)
	m.HandleFunc("DELETE "+options.BaseURL+"/session/{playerId}", wrapper.DeleteSession)
	m.HandleFunc("PATCH "+options.BaseURL+"/session/{playerId}", wrapper.UpdateSessionProperties)
	m.HandleFunc("POST "+options.BaseURL+"/session/{playerId}", wrapper.CreateSession)
	m.HandleFunc("PUT "+options.BaseURL+"/session/{playerId}", wrapper.TransferSession)

	return m
}

type BadRequestJSONResponse struct {
	Error string `json:"error"`
}

type BannedSessionResponseJSONResponse map[string]interface{}

type CreatedSessionResponseJSONResponse map[string]interface{}

type MapJoinSuccessJSONResponse struct {
	Server          string `json:"server"`
	ServerClusterIP string `json:"serverClusterIP"`
}

type NoServerAvailableResponse struct {
}

type SessionDataJSONResponse PlayerSession

type SessionNotFoundResponse struct {
}

type TransferSessionResponseJSONResponse struct {
	// Data PlayerData object from the player service
	Data    map[string]interface{} `json:"data"`
	IsJoin  bool                   `json:"isJoin"`
	Session PlayerSession          `json:"session"`
}

type AcceptMapInviteOrRequestRequestObject struct {
	Body *AcceptMapInviteOrRequestJSONRequestBody
}

type AcceptMapInviteOrRequestResponseObject interface {
	VisitAcceptMapInviteOrRequestResponse(w http.ResponseWriter) error
}

type AcceptMapInviteOrRequest200JSONResponse MapInvite

func (response AcceptMapInviteOrRequest200JSONResponse) VisitAcceptMapInviteOrRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AcceptMapInviteOrRequest400JSONResponse InviteError

func (response AcceptMapInviteOrRequest400JSONResponse) VisitAcceptMapInviteOrRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InviteToMapRequestObject struct {
	Body *InviteToMapJSONRequestBody
}

type InviteToMapResponseObject interface {
	VisitInviteToMapResponse(w http.ResponseWriter) error
}

type InviteToMap200Response struct {
}

func (response InviteToMap200Response) VisitInviteToMapResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type InviteToMap409JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response InviteToMap409JSONResponse) VisitInviteToMapResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RejectMapInviteOrRequestRequestObject struct {
	Body *RejectMapInviteOrRequestJSONRequestBody
}

type RejectMapInviteOrRequestResponseObject interface {
	VisitRejectMapInviteOrRequestResponse(w http.ResponseWriter) error
}

type RejectMapInviteOrRequest200JSONResponse MapInvite

func (response RejectMapInviteOrRequest200JSONResponse) VisitRejectMapInviteOrRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RejectMapInviteOrRequest400JSONResponse InviteError

func (response RejectMapInviteOrRequest400JSONResponse) VisitRejectMapInviteOrRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RequestToJoinMapRequestObject struct {
	Body *RequestToJoinMapJSONRequestBody
}

type RequestToJoinMapResponseObject interface {
	VisitRequestToJoinMapResponse(w http.ResponseWriter) error
}

type RequestToJoinMap200Response struct {
}

func (response RequestToJoinMap200Response) VisitRequestToJoinMapResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type RequestToJoinMap409JSONResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (response RequestToJoinMap409JSONResponse) VisitRequestToJoinMapResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type JoinHubRequestObject struct {
	Body *JoinHubJSONRequestBody
}

type JoinHubResponseObject interface {
	VisitJoinHubResponse(w http.ResponseWriter) error
}

type JoinHub200JSONResponse struct{ MapJoinSuccessJSONResponse }

func (response JoinHub200JSONResponse) VisitJoinHubResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type JoinHub400JSONResponse struct{ BadRequestJSONResponse }

func (response JoinHub400JSONResponse) VisitJoinHubResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type JoinHub401Response struct {
}

func (response JoinHub401Response) VisitJoinHubResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type JoinHub503Response = NoServerAvailableResponse

func (response JoinHub503Response) VisitJoinHubResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

type JoinMapRequestObject struct {
	Body *JoinMapJSONRequestBody
}

type JoinMapResponseObject interface {
	VisitJoinMapResponse(w http.ResponseWriter) error
}

type JoinMap200JSONResponse struct{ MapJoinSuccessJSONResponse }

func (response JoinMap200JSONResponse) VisitJoinMapResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type JoinMap400JSONResponse struct{ BadRequestJSONResponse }

func (response JoinMap400JSONResponse) VisitJoinMapResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type JoinMap401Response struct {
}

func (response JoinMap401Response) VisitJoinMapResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type JoinMap503Response = NoServerAvailableResponse

func (response JoinMap503Response) VisitJoinMapResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

type GetIsolateOverridesRequestObject struct {
}

type GetIsolateOverridesResponseObject interface {
	VisitGetIsolateOverridesResponse(w http.ResponseWriter) error
}

type GetIsolateOverrides200JSONResponse []IsolateOverride

func (response GetIsolateOverrides200JSONResponse) VisitGetIsolateOverridesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SyncServerRequestObject struct {
}

type SyncServerResponseObject interface {
	VisitSyncServerResponse(w http.ResponseWriter) error
}

type SyncServer200JSONResponse SessionList

func (response SyncServer200JSONResponse) VisitSyncServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSessionRequestObject struct {
	PlayerId string `json:"playerId"`
}

type DeleteSessionResponseObject interface {
	VisitDeleteSessionResponse(w http.ResponseWriter) error
}

type DeleteSession200Response struct {
}

func (response DeleteSession200Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteSession404Response struct {
}

func (response DeleteSession404Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateSessionPropertiesRequestObject struct {
	PlayerId PlayerId `json:"playerId"`
	Body     *UpdateSessionPropertiesJSONRequestBody
}

type UpdateSessionPropertiesResponseObject interface {
	VisitUpdateSessionPropertiesResponse(w http.ResponseWriter) error
}

type UpdateSessionProperties200JSONResponse struct{ SessionDataJSONResponse }

func (response UpdateSessionProperties200JSONResponse) VisitUpdateSessionPropertiesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSessionProperties400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateSessionProperties400JSONResponse) VisitUpdateSessionPropertiesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSessionProperties404Response = SessionNotFoundResponse

func (response UpdateSessionProperties404Response) VisitUpdateSessionPropertiesResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateSessionRequestObject struct {
	PlayerId PlayerId `json:"playerId"`
	Body     *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201JSONResponse struct {
	CreatedSessionResponseJSONResponse
}

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSession400JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession401Response struct {
}

func (response CreateSession401Response) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type CreateSession403JSONResponse struct {
	BannedSessionResponseJSONResponse
}

func (response CreateSession403JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type TransferSessionRequestObject struct {
	PlayerId PlayerId `json:"playerId"`
	Body     *TransferSessionJSONRequestBody
}

type TransferSessionResponseObject interface {
	VisitTransferSessionResponse(w http.ResponseWriter) error
}

type TransferSession201JSONResponse struct {
	TransferSessionResponseJSONResponse
}

func (response TransferSession201JSONResponse) VisitTransferSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type TransferSession400JSONResponse struct{ BadRequestJSONResponse }

func (response TransferSession400JSONResponse) VisitTransferSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type TransferSession404Response struct {
}

func (response TransferSession404Response) VisitTransferSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Accept a map invite or map join request
	// (POST /invites/map/accept)
	AcceptMapInviteOrRequest(ctx context.Context, request AcceptMapInviteOrRequestRequestObject) (AcceptMapInviteOrRequestResponseObject, error)
	// Invite a player to a map
	// (POST /invites/map/invite)
	InviteToMap(ctx context.Context, request InviteToMapRequestObject) (InviteToMapResponseObject, error)
	// Reject a map invite or map join request
	// (POST /invites/map/reject)
	RejectMapInviteOrRequest(ctx context.Context, request RejectMapInviteOrRequestRequestObject) (RejectMapInviteOrRequestResponseObject, error)
	// Request to join a map
	// (POST /invites/map/request)
	RequestToJoinMap(ctx context.Context, request RequestToJoinMapRequestObject) (RequestToJoinMapResponseObject, error)
	// Join a hub
	// (POST /join_hub)
	JoinHub(ctx context.Context, request JoinHubRequestObject) (JoinHubResponseObject, error)
	// Join a map
	// (POST /join_map)
	JoinMap(ctx context.Context, request JoinMapRequestObject) (JoinMapResponseObject, error)

	// (GET /server/isolate-overrides)
	GetIsolateOverrides(ctx context.Context, request GetIsolateOverridesRequestObject) (GetIsolateOverridesResponseObject, error)
	// An endpoint for a starting server to sync its session state
	// (POST /server/sync)
	SyncServer(ctx context.Context, request SyncServerRequestObject) (SyncServerResponseObject, error)
	// Delete a session for the given player id
	// (DELETE /session/{playerId})
	DeleteSession(ctx context.Context, request DeleteSessionRequestObject) (DeleteSessionResponseObject, error)
	// Update a session's properties
	// (PATCH /session/{playerId})
	UpdateSessionProperties(ctx context.Context, request UpdateSessionPropertiesRequestObject) (UpdateSessionPropertiesResponseObject, error)
	// Create a new session
	// (POST /session/{playerId})
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
	// Transfer a session to a new server
	// (PUT /session/{playerId})
	TransferSession(ctx context.Context, request TransferSessionRequestObject) (TransferSessionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AcceptMapInviteOrRequest operation middleware
func (sh *strictHandler) AcceptMapInviteOrRequest(w http.ResponseWriter, r *http.Request) {
	var request AcceptMapInviteOrRequestRequestObject

	var body AcceptMapInviteOrRequestJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AcceptMapInviteOrRequest(ctx, request.(AcceptMapInviteOrRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AcceptMapInviteOrRequest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AcceptMapInviteOrRequestResponseObject); ok {
		if err := validResponse.VisitAcceptMapInviteOrRequestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InviteToMap operation middleware
func (sh *strictHandler) InviteToMap(w http.ResponseWriter, r *http.Request) {
	var request InviteToMapRequestObject

	var body InviteToMapJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InviteToMap(ctx, request.(InviteToMapRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InviteToMap")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InviteToMapResponseObject); ok {
		if err := validResponse.VisitInviteToMapResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RejectMapInviteOrRequest operation middleware
func (sh *strictHandler) RejectMapInviteOrRequest(w http.ResponseWriter, r *http.Request) {
	var request RejectMapInviteOrRequestRequestObject

	var body RejectMapInviteOrRequestJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RejectMapInviteOrRequest(ctx, request.(RejectMapInviteOrRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RejectMapInviteOrRequest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RejectMapInviteOrRequestResponseObject); ok {
		if err := validResponse.VisitRejectMapInviteOrRequestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestToJoinMap operation middleware
func (sh *strictHandler) RequestToJoinMap(w http.ResponseWriter, r *http.Request) {
	var request RequestToJoinMapRequestObject

	var body RequestToJoinMapJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestToJoinMap(ctx, request.(RequestToJoinMapRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestToJoinMap")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestToJoinMapResponseObject); ok {
		if err := validResponse.VisitRequestToJoinMapResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// JoinHub operation middleware
func (sh *strictHandler) JoinHub(w http.ResponseWriter, r *http.Request) {
	var request JoinHubRequestObject

	var body JoinHubJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.JoinHub(ctx, request.(JoinHubRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "JoinHub")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(JoinHubResponseObject); ok {
		if err := validResponse.VisitJoinHubResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// JoinMap operation middleware
func (sh *strictHandler) JoinMap(w http.ResponseWriter, r *http.Request) {
	var request JoinMapRequestObject

	var body JoinMapJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.JoinMap(ctx, request.(JoinMapRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "JoinMap")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(JoinMapResponseObject); ok {
		if err := validResponse.VisitJoinMapResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetIsolateOverrides operation middleware
func (sh *strictHandler) GetIsolateOverrides(w http.ResponseWriter, r *http.Request) {
	var request GetIsolateOverridesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetIsolateOverrides(ctx, request.(GetIsolateOverridesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIsolateOverrides")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetIsolateOverridesResponseObject); ok {
		if err := validResponse.VisitGetIsolateOverridesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SyncServer operation middleware
func (sh *strictHandler) SyncServer(w http.ResponseWriter, r *http.Request) {
	var request SyncServerRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SyncServer(ctx, request.(SyncServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SyncServer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SyncServerResponseObject); ok {
		if err := validResponse.VisitSyncServerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSession operation middleware
func (sh *strictHandler) DeleteSession(w http.ResponseWriter, r *http.Request, playerId string) {
	var request DeleteSessionRequestObject

	request.PlayerId = playerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSession(ctx, request.(DeleteSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSessionResponseObject); ok {
		if err := validResponse.VisitDeleteSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSessionProperties operation middleware
func (sh *strictHandler) UpdateSessionProperties(w http.ResponseWriter, r *http.Request, playerId PlayerId) {
	var request UpdateSessionPropertiesRequestObject

	request.PlayerId = playerId

	var body UpdateSessionPropertiesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSessionProperties(ctx, request.(UpdateSessionPropertiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSessionProperties")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSessionPropertiesResponseObject); ok {
		if err := validResponse.VisitUpdateSessionPropertiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(w http.ResponseWriter, r *http.Request, playerId PlayerId) {
	var request CreateSessionRequestObject

	request.PlayerId = playerId

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TransferSession operation middleware
func (sh *strictHandler) TransferSession(w http.ResponseWriter, r *http.Request, playerId PlayerId) {
	var request TransferSessionRequestObject

	request.PlayerId = playerId

	var body TransferSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TransferSession(ctx, request.(TransferSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TransferSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TransferSessionResponseObject); ok {
		if err := validResponse.VisitTransferSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
