apiVersion: v1
kind: Service
metadata:
  name: {{ include "base.fullname" . }}-grpc
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9001
      protocol: TCP
      name: grpc
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}
