env: staging

http:
  address: 0.0.0.0
  port: 9124
metrics:
  password: ""

postgres:
  uri: "postgres://postgres:postgres@localhost:5432/map-service?sslmode=disable"

spicedb:
  endpoint: localhost:50051
  token: "foobar"
  tls: false

s3:
  endpoint: http://127.0.0.1:9000
  region: us-east-1
  access_key: mapmaker
  secret_key: mapmaker
  maps_bucket: mapmaker

redis:
  address: localhost:6379

kafka:
  brokers: kafka:9092
  schema_registry_url: http://localhost:8081

otlp:
  endpoint: ""

player_service_url: http://localhost:9126

posthog:
  personal_api_key: ""
