// Code generated by MockGen. DO NOT EDIT.
// Source: writer.go
//
// Generated by this command:
//
//	mockgen -source=writer.go -destination=mock_wkafka/writer.gen.go
//

// Package mock_wkafka is a generated GoMock package.
package mock_wkafka

import (
	context "context"
	reflect "reflect"

	kafka "github.com/segmentio/kafka-go"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncWriter is a mock of SyncWriter interface.
type MockSyncWriter struct {
	ctrl     *gomock.Controller
	recorder *MockSyncWriterMockRecorder
}

// MockSyncWriterMockRecorder is the mock recorder for MockSyncWriter.
type MockSyncWriterMockRecorder struct {
	mock *MockSyncWriter
}

// NewMockSyncWriter creates a new mock instance.
func NewMockSyncWriter(ctrl *gomock.Controller) *MockSyncWriter {
	mock := &MockSyncWriter{ctrl: ctrl}
	mock.recorder = &MockSyncWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncWriter) EXPECT() *MockSyncWriterMockRecorder {
	return m.recorder
}

// WriteMessages mocks base method.
func (m *MockSyncWriter) WriteMessages(ctx context.Context, messages ...kafka.Message) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range messages {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteMessages", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessages indicates an expected call of WriteMessages.
func (mr *MockSyncWriterMockRecorder) WriteMessages(ctx any, messages ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, messages...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessages", reflect.TypeOf((*MockSyncWriter)(nil).WriteMessages), varargs...)
}
