// Code generated by ox. DO NOT EDIT.

package v4Internal

import (
	"net/http"
	"strconv"

	"github.com/hollow-cube/api-server/pkg/ox/runtime"
)

// RegisterParams configures route registration.
type RegisterParams struct {
	Mux     *http.ServeMux
	BaseURL string // Optional prefix for all routes
}

// RegisterRoutes registers all API routes on the given ServeMux.
func RegisterRoutes(s *Server, params RegisterParams) {
	h := &handlers{server: s}
	params.Mux.HandleFunc("GET "+params.BaseURL+"/head-database/search", h.searchHeadDatabase)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/head-database/{category}", h.getHeadDatabaseCategory)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/interactions/commands", h.getCommands)
	params.Mux.HandleFunc("POST "+params.BaseURL+"/interactions", h.executeInteraction)
	params.Mux.HandleFunc("POST "+params.BaseURL+"/maps", h.createMap)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/maps/{mapId}", h.getMap)
	params.Mux.HandleFunc("PATCH "+params.BaseURL+"/maps/{mapId}", h.updateMap)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/maps/{mapId}/builders", h.getMapBuilders)
	params.Mux.HandleFunc("POST "+params.BaseURL+"/maps/{mapId}/builders", h.inviteMapBuilder)
	params.Mux.HandleFunc("DELETE "+params.BaseURL+"/maps/{mapId}/builders/{playerId}", h.removeMapBuilder)
	params.Mux.HandleFunc("POST "+params.BaseURL+"/maps/{mapId}/builders/{playerId}/accept", h.acceptMapBuilderRequest)
	params.Mux.HandleFunc("POST "+params.BaseURL+"/maps/{mapId}/builders/{playerId}/reject", h.rejectMapBuilderRequest)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/players/{playerId}/map-slots", h.getMapPlayerSlots)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/notifications", h.getNotifications)
	params.Mux.HandleFunc("PATCH "+params.BaseURL+"/notifications/{notificationId}", h.updateNotification)
	params.Mux.HandleFunc("DELETE "+params.BaseURL+"/notifications/{notificationId}", h.deleteNotification)
	params.Mux.HandleFunc("POST "+params.BaseURL+"/players", h.createPlayerData)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/players/{playerId}", h.getPlayerData)
	params.Mux.HandleFunc("PATCH "+params.BaseURL+"/players/{playerId}", h.updatePlayerData)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/players/{playerId}/display-name", h.getPlayerDisplayName)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/players/{playerId}/alts", h.getPlayerAlts)
	params.Mux.HandleFunc("POST "+params.BaseURL+"/players/search", h.searchPlayers)
}

// handlers wraps the server and provides HTTP handler methods.
type handlers struct {
	server *Server
}

func (h *handlers) searchHeadDatabase(w http.ResponseWriter, r *http.Request) {
	var req SearchHeadDatabaseRequest
	if v, err := strconv.Atoi(r.URL.Query().Get("page")); err != nil {
		runtime.WriteBadRequest(w, "invalid query parameter: page")
		return
	} else {
		req.Page = v
	}
	if v, err := strconv.Atoi(r.URL.Query().Get("pageSize")); err != nil {
		runtime.WriteBadRequest(w, "invalid query parameter: pageSize")
		return
	} else {
		req.PageSize = v
	}
	req.Query = r.URL.Query().Get("query")
	resp, err := h.server.SearchHeadDatabase(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) getHeadDatabaseCategory(w http.ResponseWriter, r *http.Request) {
	var req GetHeadDatabaseCategoryRequest
	req.Category = r.PathValue("category")
	if v, err := strconv.Atoi(r.URL.Query().Get("page")); err != nil {
		runtime.WriteBadRequest(w, "invalid query parameter: page")
		return
	} else {
		req.Page = v
	}
	if v, err := strconv.Atoi(r.URL.Query().Get("pageSize")); err != nil {
		runtime.WriteBadRequest(w, "invalid query parameter: pageSize")
		return
	} else {
		req.PageSize = v
	}
	resp, err := h.server.GetHeadDatabaseCategory(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) getCommands(w http.ResponseWriter, r *http.Request) {
	resp, err := h.server.GetCommands(r.Context())
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) executeInteraction(w http.ResponseWriter, r *http.Request) {
	var body Interaction
	if err := runtime.DecodeJSON(r, &body); err != nil {
		runtime.WriteBadRequest(w, "invalid request body")
		return
	}
	resp, err := h.server.ExecuteInteraction(r.Context(), body)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) createMap(w http.ResponseWriter, r *http.Request) {
	var body CreateMapRequest
	if err := runtime.DecodeJSON(r, &body); err != nil {
		runtime.WriteBadRequest(w, "invalid request body")
		return
	}
	resp, err := h.server.CreateMap(r.Context(), body)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 201, resp)
}

func (h *handlers) getMap(w http.ResponseWriter, r *http.Request) {
	var req MapRequest
	req.MapID = r.PathValue("mapId")
	resp, err := h.server.GetMap(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) updateMap(w http.ResponseWriter, r *http.Request) {
	var req MapRequest
	req.MapID = r.PathValue("mapId")
	var body UpdateMapRequest
	if err := runtime.DecodeJSON(r, &body); err != nil {
		runtime.WriteBadRequest(w, "invalid request body")
		return
	}
	err := h.server.UpdateMap(r.Context(), req, body)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	w.WriteHeader(200)
}

func (h *handlers) getMapBuilders(w http.ResponseWriter, r *http.Request) {
	var req GetMapBuildersRequest
	req.MapID = r.PathValue("mapId")
	if v, err := strconv.ParseBool(r.URL.Query().Get("onlyActive")); err != nil {
		runtime.WriteBadRequest(w, "invalid query parameter: onlyActive")
		return
	} else {
		req.OnlyActive = v
	}
	resp, err := h.server.GetMapBuilders(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) inviteMapBuilder(w http.ResponseWriter, r *http.Request) {
	var req MapRequest
	req.MapID = r.PathValue("mapId")
	var body InviteMapBuilderRequest
	if err := runtime.DecodeJSON(r, &body); err != nil {
		runtime.WriteBadRequest(w, "invalid request body")
		return
	}
	err := h.server.InviteMapBuilder(r.Context(), req, body)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	w.WriteHeader(200)
}

func (h *handlers) removeMapBuilder(w http.ResponseWriter, r *http.Request) {
	var req MapPlayerRequest
	req.MapID = r.PathValue("mapId")
	req.PlayerID = r.PathValue("playerId")
	err := h.server.RemoveMapBuilder(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	w.WriteHeader(200)
}

func (h *handlers) acceptMapBuilderRequest(w http.ResponseWriter, r *http.Request) {
	var req MapPlayerRequest
	req.MapID = r.PathValue("mapId")
	req.PlayerID = r.PathValue("playerId")
	err := h.server.AcceptMapBuilderRequest(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	w.WriteHeader(200)
}

func (h *handlers) rejectMapBuilderRequest(w http.ResponseWriter, r *http.Request) {
	var req MapPlayerRequest
	req.MapID = r.PathValue("mapId")
	req.PlayerID = r.PathValue("playerId")
	err := h.server.RejectMapBuilderRequest(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	w.WriteHeader(200)
}

func (h *handlers) getMapPlayerSlots(w http.ResponseWriter, r *http.Request) {
	var req PlayerRequest
	req.PlayerId = r.PathValue("playerId")
	resp, err := h.server.GetMapPlayerSlots(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) getNotifications(w http.ResponseWriter, r *http.Request) {
	var req GetNotificationsRequest
	req.PlayerID = r.URL.Query().Get("playerId")
	if v, err := strconv.Atoi(r.URL.Query().Get("page")); err != nil {
		runtime.WriteBadRequest(w, "invalid query parameter: page")
		return
	} else {
		req.Page = v
	}
	if v, err := strconv.Atoi(r.URL.Query().Get("pageSize")); err != nil {
		runtime.WriteBadRequest(w, "invalid query parameter: pageSize")
		return
	} else {
		req.PageSize = v
	}
	if v, err := strconv.ParseBool(r.URL.Query().Get("unreadOnly")); err != nil {
		runtime.WriteBadRequest(w, "invalid query parameter: unreadOnly")
		return
	} else {
		req.UnreadOnly = v
	}
	resp, err := h.server.GetNotifications(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) updateNotification(w http.ResponseWriter, r *http.Request) {
	var req NotificationRequest
	req.NotificationID = r.PathValue("notificationId")
	var body UpdateNotificationRequest
	if err := runtime.DecodeJSON(r, &body); err != nil {
		runtime.WriteBadRequest(w, "invalid request body")
		return
	}
	err := h.server.UpdateNotification(r.Context(), req, body)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	w.WriteHeader(200)
}

func (h *handlers) deleteNotification(w http.ResponseWriter, r *http.Request) {
	var req NotificationRequest
	req.NotificationID = r.PathValue("notificationId")
	err := h.server.DeleteNotification(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	w.WriteHeader(204)
}

func (h *handlers) createPlayerData(w http.ResponseWriter, r *http.Request) {
	var body CreatePlayerDataRequest
	if err := runtime.DecodeJSON(r, &body); err != nil {
		runtime.WriteBadRequest(w, "invalid request body")
		return
	}
	resp, err := h.server.CreatePlayerData(r.Context(), body)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 201, resp)
}

func (h *handlers) getPlayerData(w http.ResponseWriter, r *http.Request) {
	var req PlayerRequest
	req.PlayerId = r.PathValue("playerId")
	resp, err := h.server.GetPlayerData(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) updatePlayerData(w http.ResponseWriter, r *http.Request) {
	var req UpdatePlayerDataRequest
	req.PlayerId = r.PathValue("playerId")
	if err := runtime.DecodeJSON(r, &req.UpdatePlayerDataRequestBody); err != nil {
		runtime.WriteBadRequest(w, "invalid request body")
		return
	}
	err := h.server.UpdatePlayerData(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	w.WriteHeader(200)
}

func (h *handlers) getPlayerDisplayName(w http.ResponseWriter, r *http.Request) {
	var req PlayerRequest
	req.PlayerId = r.PathValue("playerId")
	resp, err := h.server.GetPlayerDisplayName(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) getPlayerAlts(w http.ResponseWriter, r *http.Request) {
	var req PlayerRequest
	req.PlayerId = r.PathValue("playerId")
	resp, err := h.server.GetPlayerAlts(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) searchPlayers(w http.ResponseWriter, r *http.Request) {
	var body SearchPlayersRequest
	if err := runtime.DecodeJSON(r, &body); err != nil {
		runtime.WriteBadRequest(w, "invalid request body")
		return
	}
	resp, err := h.server.SearchPlayers(r.Context(), body)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}
