// Code generated by ox. DO NOT EDIT.

package v4Internal

import (
	"net/http"
	"strconv"

	"github.com/hollow-cube/api-server/pkg/ox/runtime"
)

// RegisterRoutes registers all API routes on the given ServeMux.
func RegisterRoutes(mux *http.ServeMux, s *Server) {
	mux.HandleFunc("GET /players/{playerId}", handleGetPlayerData(s))
	mux.HandleFunc("POST /players", handleCreatePlayerData(s))
	mux.HandleFunc("PATCH /players/{playerId}", handleUpdatePlayerData(s))
	mux.HandleFunc("GET /players/{playerId}/display-name", handleGetPlayerDisplayName(s))
	mux.HandleFunc("GET /players/{playerId}/alts", handleGetPlayerAlts(s))
	mux.HandleFunc("GET /recap/{playerId}/{year}", handleGetPlayerRecap(s))
}

func handleGetPlayerData(s *Server) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req PlayerRequest
		req.PlayerId = r.PathValue("playerId")
		resp, err := s.GetPlayerData(r.Context(), req)
		if err != nil {
			runtime.HandleError(w, err)
			return
		}
		runtime.WriteJSON(w, 200, resp)
	}
}

func handleCreatePlayerData(s *Server) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var body CreatePlayerDataRequest
		if err := runtime.DecodeJSON(r, &body); err != nil {
			runtime.WriteBadRequest(w, "invalid request body")
			return
		}
		resp, err := s.CreatePlayerData(r.Context(), body)
		if err != nil {
			runtime.HandleError(w, err)
			return
		}
		runtime.WriteJSON(w, 201, resp)
	}
}

func handleUpdatePlayerData(s *Server) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req UpdatePlayerDataRequest
		req.PlayerId = r.PathValue("playerId")
		if err := runtime.DecodeJSON(r, &req.UpdatePlayerDataRequestBody); err != nil {
			runtime.WriteBadRequest(w, "invalid request body")
			return
		}
		err := s.UpdatePlayerData(r.Context(), req)
		if err != nil {
			runtime.HandleError(w, err)
			return
		}
		w.WriteHeader(200)
	}
}

func handleGetPlayerDisplayName(s *Server) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req PlayerRequest
		req.PlayerId = r.PathValue("playerId")
		resp, err := s.GetPlayerDisplayName(r.Context(), req)
		if err != nil {
			runtime.HandleError(w, err)
			return
		}
		runtime.WriteJSON(w, 200, resp)
	}
}

func handleGetPlayerAlts(s *Server) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req PlayerRequest
		req.PlayerId = r.PathValue("playerId")
		resp, err := s.GetPlayerAlts(r.Context(), req)
		if err != nil {
			runtime.HandleError(w, err)
			return
		}
		runtime.WriteJSON(w, 200, resp)
	}
}

func handleGetPlayerRecap(s *Server) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req GetPlayerRecapRequest
		req.PlayerID = r.PathValue("playerId")
		if v, err := strconv.Atoi(r.PathValue("year")); err != nil {
			runtime.WriteBadRequest(w, "invalid path parameter: year")
			return
		} else {
			req.Year = v
		}
		resp, err := s.GetPlayerRecap(r.Context(), req)
		if err != nil {
			runtime.HandleError(w, err)
			return
		}
		runtime.WriteText(w, 200, resp)
	}
}
