// Code generated by ox. DO NOT EDIT.

package v4Internal

import (
	"net/http"
	"strconv"

	"github.com/hollow-cube/api-server/pkg/ox/runtime"
)

// RegisterParams configures route registration.
type RegisterParams struct {
	Mux     *http.ServeMux
	BaseURL string // Optional prefix for all routes
}

// RegisterRoutes registers all API routes on the given ServeMux.
func RegisterRoutes(s *Server, params RegisterParams) {
	h := &handlers{server: s}
	params.Mux.HandleFunc("GET "+params.BaseURL+"/head-database/search", h.searchHeadDatabase)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/head-database/{category}", h.getHeadDatabaseCategory)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/players/{playerId}", h.getPlayerData)
	params.Mux.HandleFunc("POST "+params.BaseURL+"/players", h.createPlayerData)
	params.Mux.HandleFunc("PATCH "+params.BaseURL+"/players/{playerId}", h.updatePlayerData)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/players/{playerId}/display-name", h.getPlayerDisplayName)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/players/{playerId}/alts", h.getPlayerAlts)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/recap/{playerId}/{year}", h.getPlayerRecap)
}

// handlers wraps the server and provides HTTP handler methods.
type handlers struct {
	server *Server
}

func (h *handlers) searchHeadDatabase(w http.ResponseWriter, r *http.Request) {
	var req SearchHeadDatabaseRequest
	if v, err := strconv.Atoi(r.URL.Query().Get("page")); err != nil {
		runtime.WriteBadRequest(w, "invalid query parameter: page")
		return
	} else {
		req.Page = v
	}
	if v, err := strconv.Atoi(r.URL.Query().Get("pageSize")); err != nil {
		runtime.WriteBadRequest(w, "invalid query parameter: pageSize")
		return
	} else {
		req.PageSize = v
	}
	req.Query = r.URL.Query().Get("query")
	resp, err := h.server.SearchHeadDatabase(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) getHeadDatabaseCategory(w http.ResponseWriter, r *http.Request) {
	var req GetHeadDatabaseCategoryRequest
	req.Category = r.PathValue("category")
	if v, err := strconv.Atoi(r.URL.Query().Get("page")); err != nil {
		runtime.WriteBadRequest(w, "invalid query parameter: page")
		return
	} else {
		req.Page = v
	}
	if v, err := strconv.Atoi(r.URL.Query().Get("pageSize")); err != nil {
		runtime.WriteBadRequest(w, "invalid query parameter: pageSize")
		return
	} else {
		req.PageSize = v
	}
	resp, err := h.server.GetHeadDatabaseCategory(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) getPlayerData(w http.ResponseWriter, r *http.Request) {
	var req PlayerRequest
	req.PlayerId = r.PathValue("playerId")
	resp, err := h.server.GetPlayerData(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) createPlayerData(w http.ResponseWriter, r *http.Request) {
	var body CreatePlayerDataRequest
	if err := runtime.DecodeJSON(r, &body); err != nil {
		runtime.WriteBadRequest(w, "invalid request body")
		return
	}
	resp, err := h.server.CreatePlayerData(r.Context(), body)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 201, resp)
}

func (h *handlers) updatePlayerData(w http.ResponseWriter, r *http.Request) {
	var req UpdatePlayerDataRequest
	req.PlayerId = r.PathValue("playerId")
	if err := runtime.DecodeJSON(r, &req.UpdatePlayerDataRequestBody); err != nil {
		runtime.WriteBadRequest(w, "invalid request body")
		return
	}
	err := h.server.UpdatePlayerData(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	w.WriteHeader(200)
}

func (h *handlers) getPlayerDisplayName(w http.ResponseWriter, r *http.Request) {
	var req PlayerRequest
	req.PlayerId = r.PathValue("playerId")
	resp, err := h.server.GetPlayerDisplayName(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) getPlayerAlts(w http.ResponseWriter, r *http.Request) {
	var req PlayerRequest
	req.PlayerId = r.PathValue("playerId")
	resp, err := h.server.GetPlayerAlts(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) getPlayerRecap(w http.ResponseWriter, r *http.Request) {
	var req GetPlayerRecapRequest
	req.PlayerID = r.PathValue("playerId")
	if v, err := strconv.Atoi(r.PathValue("year")); err != nil {
		runtime.WriteBadRequest(w, "invalid path parameter: year")
		return
	} else {
		req.Year = v
	}
	resp, err := h.server.GetPlayerRecap(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteText(w, 200, resp)
}
