env: staging

http:
  address: 0.0.0.0
  port: 9124
metrics:
  password: ""

otlp:
  endpoint: ""

redis:
  address: localhost:6379

nats:
  servers: nats://localhost:4222

kubernetes:
  namespace: default

postgres:
  uri: "postgres://postgres:postgres@localhost:5432/session-service?sslmode=disable"
  players_uri: "postgres://postgres:postgres@localhost:5432/player-service?sslmode=disable"
  maps_uri: "postgres://postgres:postgres@localhost:5432/map-service?sslmode=disable"

player_service_url: http://localhost:9126
map_service_url: http://localhost:9125

posthog:
  endpoint: "http://localhost:9126/posthog"
  personal_api_key: ""

unleash:
  address: "http://unleash.mgmt.svc.cluster.local:4242/api"
  token: ""

tebex:
  private_key: ""
  secret: "abc"
  dispute_discord_webhook: ""

discord:
  application_id: ""
  public_key: ""
  token: ""

s3:
  endpoint: http://127.0.0.1:9000
  region: us-east-1
  access_key: mapmaker
  secret_key: mapmaker
  maps_bucket: mapmaker

map_isolate:
  instances:
    micro: { memory: 300 }
    mini: { memory: 400 }
    medium: { memory: 500 }
    large: { memory: 600 }
    xlarge: { memory: 800 }
  default_size: medium
  world_size_mapping:
    normal: micro
    large: mini
    massive: medium
    colossal: large
    unlimited: xlarge

github:
  private_key: ""

punishment_ladders:
  - id: "chat-minor"
    name: "Minor Chat Infraction"
    type: "mute"
    entries:
      - duration: "12h"
      - duration: "1d"
      - duration: "3d"
      - duration: "7d"
      - duration: "1mo"
      - duration: "6mo"
      - duration: "permanent"
    reasons:
      - id: toxicity
        aliases: [to]
      - id: spam
        aliases: [sp]
  - id: "chat-major"
    name: "Major Chat Infraction"
    type: "mute"
    entries:
      - duration: "3d"
      - duration: "7d"
      - duration: "2w"
      - duration: "1mo"
      - duration: "6mo"
      - duration: "permanent"
    reasons:
      - id: discrimination
        aliases: [di]
      - id: harassment
        aliases: [hr]
  - id: "gameplay-minor"
    name: "Minor Gameplay Infraction"
    type: "ban"
    entries:
      - duration: "1w"
      - duration: "1mo"
      - duration: "3mo"
      - duration: "permanent"
    reasons:
      - id: macros
        aliases: [mc]
      - id: stat-boosting
        aliases: [sb]
  - id: "gameplay-major"
    name: "Major Gameplay Infraction"
    type: "ban"
    entries:
      - duration: "1mo"
      - duration: "3mo"
      - duration: "permanent"
    reasons:
      - id: bug-abuse
        aliases: [ba]
      - id: cheating
        aliases: [ch]
  - id: "severe"
    name: "Severe Infraction"
    type: "ban"
    entries:
      - duration: "permanent"
    reasons:
      - id: dox
        aliases: [dx]
      - id: ddos
        aliases: [dd]
