env: staging

http:
  address: 0.0.0.0
  port: 9124
metrics:
  password: ""

otlp:
  endpoint: ""

redis:
  address: localhost:6379

kafka:
  brokers: kafka:9092

nats:
  servers: nats://localhost:4222

kubernetes:
  namespace: default

postgres:
  uri: "postgres://postgres:postgres@localhost:5432/session-service?sslmode=disable"

player_service_url: http://localhost:9126
map_service_url: http://localhost:9125

posthog:
  endpoint: "http://localhost:9126/posthog"
  personal_api_key: ""

unleash:
  address: "http://unleash.mgmt.svc.cluster.local:4242/api"
  token: ""

map_isolate:
  instances:
    micro: { memory: 300 }
    mini: { memory: 400 }
    medium: { memory: 500 }
    large: { memory: 600 }
    xlarge: { memory: 800 }
  default_size: medium
  world_size_mapping:
    normal: micro
    large: mini
    massive: medium
    colossal: large
    unlimited: xlarge

github:
  private_key: ""
