// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mock_storage/storage.gen.go
//

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hollow-cube/hc-services/services/player-service/internal/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddCurrency mocks base method.
func (m *MockClient) AddCurrency(ctx context.Context, playerId string, currencyType model.CurrencyType, amount int, reason model.BalanceChangeReason, meta map[string]any) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCurrency", ctx, playerId, currencyType, amount, reason, meta)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCurrency indicates an expected call of AddCurrency.
func (mr *MockClientMockRecorder) AddCurrency(ctx, playerId, currencyType, amount, reason, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCurrency", reflect.TypeOf((*MockClient)(nil).AddCurrency), ctx, playerId, currencyType, amount, reason, meta)
}

// AddLinkedAccount mocks base method.
func (m *MockClient) AddLinkedAccount(ctx context.Context, playerId, socialId, platform string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLinkedAccount", ctx, playerId, socialId, platform)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLinkedAccount indicates an expected call of AddLinkedAccount.
func (mr *MockClientMockRecorder) AddLinkedAccount(ctx, playerId, socialId, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLinkedAccount", reflect.TypeOf((*MockClient)(nil).AddLinkedAccount), ctx, playerId, socialId, platform)
}

// CreatePendingVerification mocks base method.
func (m *MockClient) CreatePendingVerification(ctx context.Context, v *model.PendingVerification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePendingVerification", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePendingVerification indicates an expected call of CreatePendingVerification.
func (mr *MockClientMockRecorder) CreatePendingVerification(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePendingVerification", reflect.TypeOf((*MockClient)(nil).CreatePendingVerification), ctx, v)
}

// CreatePlayerData mocks base method.
func (m *MockClient) CreatePlayerData(ctx context.Context, p *model.PlayerData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlayerData", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePlayerData indicates an expected call of CreatePlayerData.
func (mr *MockClientMockRecorder) CreatePlayerData(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlayerData", reflect.TypeOf((*MockClient)(nil).CreatePlayerData), ctx, p)
}

// CreateTebexState mocks base method.
func (m *MockClient) CreateTebexState(ctx context.Context, txId string, changes []*model.TebexChange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTebexState", ctx, txId, changes)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTebexState indicates an expected call of CreateTebexState.
func (mr *MockClientMockRecorder) CreateTebexState(ctx, txId, changes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTebexState", reflect.TypeOf((*MockClient)(nil).CreateTebexState), ctx, txId, changes)
}

// DeletePendingVerification mocks base method.
func (m *MockClient) DeletePendingVerification(ctx context.Context, uniqueVal *string, t model.VerificationType, isValueId bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePendingVerification", ctx, uniqueVal, t, isValueId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePendingVerification indicates an expected call of DeletePendingVerification.
func (mr *MockClientMockRecorder) DeletePendingVerification(ctx, uniqueVal, t, isValueId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingVerification", reflect.TypeOf((*MockClient)(nil).DeletePendingVerification), ctx, uniqueVal, t, isValueId)
}

// GetPendingVerification mocks base method.
func (m *MockClient) GetPendingVerification(ctx context.Context, t model.VerificationType, userSecret string) (*model.PendingVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingVerification", ctx, t, userSecret)
	ret0, _ := ret[0].(*model.PendingVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingVerification indicates an expected call of GetPendingVerification.
func (mr *MockClientMockRecorder) GetPendingVerification(ctx, t, userSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingVerification", reflect.TypeOf((*MockClient)(nil).GetPendingVerification), ctx, t, userSecret)
}

// GetPlayerBackpack mocks base method.
func (m *MockClient) GetPlayerBackpack(ctx context.Context, playerId string) (*model.PlayerBackpack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayerBackpack", ctx, playerId)
	ret0, _ := ret[0].(*model.PlayerBackpack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayerBackpack indicates an expected call of GetPlayerBackpack.
func (mr *MockClientMockRecorder) GetPlayerBackpack(ctx, playerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerBackpack", reflect.TypeOf((*MockClient)(nil).GetPlayerBackpack), ctx, playerId)
}

// GetPlayerData mocks base method.
func (m *MockClient) GetPlayerData(ctx context.Context, id string) (*model.PlayerData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayerData", ctx, id)
	ret0, _ := ret[0].(*model.PlayerData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayerData indicates an expected call of GetPlayerData.
func (mr *MockClientMockRecorder) GetPlayerData(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerData", reflect.TypeOf((*MockClient)(nil).GetPlayerData), ctx, id)
}

// LogTebexEvent mocks base method.
func (m *MockClient) LogTebexEvent(ctx context.Context, id string, time time.Time, raw string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogTebexEvent", ctx, id, time, raw)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogTebexEvent indicates an expected call of LogTebexEvent.
func (mr *MockClientMockRecorder) LogTebexEvent(ctx, id, time, raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTebexEvent", reflect.TypeOf((*MockClient)(nil).LogTebexEvent), ctx, id, time, raw)
}

// LookupPlayerByIdOrUsername mocks base method.
func (m *MockClient) LookupPlayerByIdOrUsername(ctx context.Context, idOrUsername string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupPlayerByIdOrUsername", ctx, idOrUsername)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupPlayerByIdOrUsername indicates an expected call of LookupPlayerByIdOrUsername.
func (mr *MockClientMockRecorder) LookupPlayerByIdOrUsername(ctx, idOrUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupPlayerByIdOrUsername", reflect.TypeOf((*MockClient)(nil).LookupPlayerByIdOrUsername), ctx, idOrUsername)
}

// LookupPlayerDataBySocial mocks base method.
func (m *MockClient) LookupPlayerDataBySocial(ctx context.Context, id, platform string) (*model.PlayerData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupPlayerDataBySocial", ctx, id, platform)
	ret0, _ := ret[0].(*model.PlayerData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupPlayerDataBySocial indicates an expected call of LookupPlayerDataBySocial.
func (mr *MockClientMockRecorder) LookupPlayerDataBySocial(ctx, id, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupPlayerDataBySocial", reflect.TypeOf((*MockClient)(nil).LookupPlayerDataBySocial), ctx, id, platform)
}

// RevertTebexState mocks base method.
func (m *MockClient) RevertTebexState(ctx context.Context, txId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevertTebexState", ctx, txId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevertTebexState indicates an expected call of RevertTebexState.
func (mr *MockClientMockRecorder) RevertTebexState(ctx, txId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertTebexState", reflect.TypeOf((*MockClient)(nil).RevertTebexState), ctx, txId)
}

// RunTransaction mocks base method.
func (m *MockClient) RunTransaction(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransaction", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransaction indicates an expected call of RunTransaction.
func (mr *MockClientMockRecorder) RunTransaction(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransaction", reflect.TypeOf((*MockClient)(nil).RunTransaction), ctx, f)
}

// SearchPlayersFuzzy mocks base method.
func (m *MockClient) SearchPlayersFuzzy(ctx context.Context, query string) ([]*model.PlayerData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPlayersFuzzy", ctx, query)
	ret0, _ := ret[0].([]*model.PlayerData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPlayersFuzzy indicates an expected call of SearchPlayersFuzzy.
func (mr *MockClientMockRecorder) SearchPlayersFuzzy(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPlayersFuzzy", reflect.TypeOf((*MockClient)(nil).SearchPlayersFuzzy), ctx, query)
}

// UpdatePlayerData mocks base method.
func (m *MockClient) UpdatePlayerData(ctx context.Context, p *model.PlayerData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlayerData", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlayerData indicates an expected call of UpdatePlayerData.
func (mr *MockClientMockRecorder) UpdatePlayerData(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlayerData", reflect.TypeOf((*MockClient)(nil).UpdatePlayerData), ctx, p)
}
