openapi: 3.0.2
info:
  title: Player Service Payments API
  version: "1"
paths:
  /stats:
    get:
      operationId: getPublicStats
      summary: Returns the public stats for players on hc
      responses:
        '200':
          description: Stats
          content:
            application/json:
              schema:
                type: object
                required: [ totalPlayers, totalPlaytime ]
                properties:
                  totalPlayers:
                    type: integer
                    format: int64
                    description: Total number of players
                  totalPlaytime:
                    type: integer
                    format: int64
                    description: Total playtime in seconds
  /recap/{id}:
    get:
      summary: Get the recap data for an id
      operationId: getPlayerRecap
      parameters:
        - name: id
          in: path
          description: The ID of the recap
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns the recap data
          content:
            application/json:
              schema:
                type: object
                required: [ playerId, username, year, data ]
                properties:
                  playerId: { type: string }
                  username: { type: string }
                  year: { type: integer }
                  data:
                    type: object
                    additionalProperties: true
        '404':
          description: Recap not found

