//go:build go1.22

// Package terraform provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package terraform

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// SchematicHeader defines model for SchematicHeader.
type SchematicHeader struct {
	Dimensions *TFPoint `json:"dimensions,omitempty"`
	FileType   *string  `json:"fileType,omitempty"`
	Name       string   `json:"name"`
	Size       float32  `json:"size"`
}

// TFPoint defines model for TFPoint.
type TFPoint struct {
	X float32 `json:"x"`
	Y float32 `json:"y"`
	Z float32 `json:"z"`
}

// CreateSchematicParams defines parameters for CreateSchematic.
type CreateSchematicParams struct {
	// Dimx The schematic dimensions in the x axis
	Dimx *int `form:"dimx,omitempty" json:"dimx,omitempty"`

	// Dimy The schematic dimensions in the y axis
	Dimy *int `form:"dimy,omitempty" json:"dimy,omitempty"`

	// Dimz The schematic dimensions in the z axis
	Dimz *int `form:"dimz,omitempty" json:"dimz,omitempty"`

	// FileType The schematic file type
	FileType *string `form:"fileType,omitempty" json:"fileType,omitempty"`
}

// UpdateSchematicHeaderJSONBody defines parameters for UpdateSchematicHeader.
type UpdateSchematicHeaderJSONBody struct {
	Dimensions *TFPoint `json:"dimensions,omitempty"`
	FileType   *string  `json:"fileType,omitempty"`
}

// UpdateSchematicHeaderJSONRequestBody defines body for UpdateSchematicHeader for application/json ContentType.
type UpdateSchematicHeaderJSONRequestBody UpdateSchematicHeaderJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /schem/{playerId})
	ListPlayerSchematics(w http.ResponseWriter, r *http.Request, playerId string)

	// (DELETE /schem/{playerId}/{schemName})
	DeleteSchematic(w http.ResponseWriter, r *http.Request, playerId string, schemName string)

	// (GET /schem/{playerId}/{schemName})
	GetSchematicData(w http.ResponseWriter, r *http.Request, playerId string, schemName string)

	// (POST /schem/{playerId}/{schemName})
	CreateSchematic(w http.ResponseWriter, r *http.Request, playerId string, schemName string, params CreateSchematicParams)

	// (PUT /schem/{playerId}/{schemName})
	UpdateSchematicHeader(w http.ResponseWriter, r *http.Request, playerId string, schemName string)
	// Fetch a player session by the player ID
	// (GET /session/{playerId})
	GetPlayerSession(w http.ResponseWriter, r *http.Request, playerId string)
	// Update a player session by the player ID
	// (PUT /session/{playerId})
	UpdatePlayerSession(w http.ResponseWriter, r *http.Request, playerId string)
	// Fetch a local session by the player ID and world ID
	// (GET /session/{playerId}/{worldId})
	GetLocalSession(w http.ResponseWriter, r *http.Request, playerId string, worldId string)
	// Update a local session by the player ID
	// (PUT /session/{playerId}/{worldId})
	UpdateLocalSession(w http.ResponseWriter, r *http.Request, playerId string, worldId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListPlayerSchematics operation middleware
func (siw *ServerInterfaceWrapper) ListPlayerSchematics(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId string

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlayerSchematics(w, r, playerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSchematic operation middleware
func (siw *ServerInterfaceWrapper) DeleteSchematic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId string

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	// ------------- Path parameter "schemName" -------------
	var schemName string

	err = runtime.BindStyledParameterWithOptions("simple", "schemName", r.PathValue("schemName"), &schemName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "schemName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSchematic(w, r, playerId, schemName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchematicData operation middleware
func (siw *ServerInterfaceWrapper) GetSchematicData(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId string

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	// ------------- Path parameter "schemName" -------------
	var schemName string

	err = runtime.BindStyledParameterWithOptions("simple", "schemName", r.PathValue("schemName"), &schemName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "schemName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchematicData(w, r, playerId, schemName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSchematic operation middleware
func (siw *ServerInterfaceWrapper) CreateSchematic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId string

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	// ------------- Path parameter "schemName" -------------
	var schemName string

	err = runtime.BindStyledParameterWithOptions("simple", "schemName", r.PathValue("schemName"), &schemName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "schemName", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateSchematicParams

	// ------------- Optional query parameter "dimx" -------------

	err = runtime.BindQueryParameter("form", true, false, "dimx", r.URL.Query(), &params.Dimx)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dimx", Err: err})
		return
	}

	// ------------- Optional query parameter "dimy" -------------

	err = runtime.BindQueryParameter("form", true, false, "dimy", r.URL.Query(), &params.Dimy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dimy", Err: err})
		return
	}

	// ------------- Optional query parameter "dimz" -------------

	err = runtime.BindQueryParameter("form", true, false, "dimz", r.URL.Query(), &params.Dimz)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dimz", Err: err})
		return
	}

	// ------------- Optional query parameter "fileType" -------------

	err = runtime.BindQueryParameter("form", true, false, "fileType", r.URL.Query(), &params.FileType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fileType", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSchematic(w, r, playerId, schemName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSchematicHeader operation middleware
func (siw *ServerInterfaceWrapper) UpdateSchematicHeader(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId string

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	// ------------- Path parameter "schemName" -------------
	var schemName string

	err = runtime.BindStyledParameterWithOptions("simple", "schemName", r.PathValue("schemName"), &schemName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "schemName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSchematicHeader(w, r, playerId, schemName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlayerSession operation middleware
func (siw *ServerInterfaceWrapper) GetPlayerSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId string

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlayerSession(w, r, playerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePlayerSession operation middleware
func (siw *ServerInterfaceWrapper) UpdatePlayerSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId string

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePlayerSession(w, r, playerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLocalSession operation middleware
func (siw *ServerInterfaceWrapper) GetLocalSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId string

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	// ------------- Path parameter "worldId" -------------
	var worldId string

	err = runtime.BindStyledParameterWithOptions("simple", "worldId", r.PathValue("worldId"), &worldId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "worldId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLocalSession(w, r, playerId, worldId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLocalSession operation middleware
func (siw *ServerInterfaceWrapper) UpdateLocalSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playerId" -------------
	var playerId string

	err = runtime.BindStyledParameterWithOptions("simple", "playerId", r.PathValue("playerId"), &playerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerId", Err: err})
		return
	}

	// ------------- Path parameter "worldId" -------------
	var worldId string

	err = runtime.BindStyledParameterWithOptions("simple", "worldId", r.PathValue("worldId"), &worldId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "worldId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLocalSession(w, r, playerId, worldId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/schem/{playerId}", wrapper.ListPlayerSchematics)
	m.HandleFunc("DELETE "+options.BaseURL+"/schem/{playerId}/{schemName}", wrapper.DeleteSchematic)
	m.HandleFunc("GET "+options.BaseURL+"/schem/{playerId}/{schemName}", wrapper.GetSchematicData)
	m.HandleFunc("POST "+options.BaseURL+"/schem/{playerId}/{schemName}", wrapper.CreateSchematic)
	m.HandleFunc("PUT "+options.BaseURL+"/schem/{playerId}/{schemName}", wrapper.UpdateSchematicHeader)
	m.HandleFunc("GET "+options.BaseURL+"/session/{playerId}", wrapper.GetPlayerSession)
	m.HandleFunc("PUT "+options.BaseURL+"/session/{playerId}", wrapper.UpdatePlayerSession)
	m.HandleFunc("GET "+options.BaseURL+"/session/{playerId}/{worldId}", wrapper.GetLocalSession)
	m.HandleFunc("PUT "+options.BaseURL+"/session/{playerId}/{worldId}", wrapper.UpdateLocalSession)

	return m
}

type ListPlayerSchematicsRequestObject struct {
	PlayerId string `json:"playerId"`
}

type ListPlayerSchematicsResponseObject interface {
	VisitListPlayerSchematicsResponse(w http.ResponseWriter) error
}

type ListPlayerSchematics200JSONResponse []SchematicHeader

func (response ListPlayerSchematics200JSONResponse) VisitListPlayerSchematicsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSchematicRequestObject struct {
	PlayerId  string `json:"playerId"`
	SchemName string `json:"schemName"`
}

type DeleteSchematicResponseObject interface {
	VisitDeleteSchematicResponse(w http.ResponseWriter) error
}

type DeleteSchematic200Response struct {
}

func (response DeleteSchematic200Response) VisitDeleteSchematicResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteSchematic404Response struct {
}

func (response DeleteSchematic404Response) VisitDeleteSchematicResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetSchematicDataRequestObject struct {
	PlayerId  string `json:"playerId"`
	SchemName string `json:"schemName"`
}

type GetSchematicDataResponseObject interface {
	VisitGetSchematicDataResponse(w http.ResponseWriter) error
}

type GetSchematicData200ApplicationvndTerraformSchematicResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetSchematicData200ApplicationvndTerraformSchematicResponse) VisitGetSchematicDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/vnd.terraform.schematic")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetSchematicData404Response struct {
}

func (response GetSchematicData404Response) VisitGetSchematicDataResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateSchematicRequestObject struct {
	PlayerId  string `json:"playerId"`
	SchemName string `json:"schemName"`
	Params    CreateSchematicParams
	Body      io.Reader
}

type CreateSchematicResponseObject interface {
	VisitCreateSchematicResponse(w http.ResponseWriter) error
}

type CreateSchematic200Response struct {
}

func (response CreateSchematic200Response) VisitCreateSchematicResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateSchematicHeaderRequestObject struct {
	PlayerId  string `json:"playerId"`
	SchemName string `json:"schemName"`
	Body      *UpdateSchematicHeaderJSONRequestBody
}

type UpdateSchematicHeaderResponseObject interface {
	VisitUpdateSchematicHeaderResponse(w http.ResponseWriter) error
}

type UpdateSchematicHeader200Response struct {
}

func (response UpdateSchematicHeader200Response) VisitUpdateSchematicHeaderResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateSchematicHeader404Response struct {
}

func (response UpdateSchematicHeader404Response) VisitUpdateSchematicHeaderResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetPlayerSessionRequestObject struct {
	PlayerId string `json:"playerId"`
}

type GetPlayerSessionResponseObject interface {
	VisitGetPlayerSessionResponse(w http.ResponseWriter) error
}

type GetPlayerSession200ApplicationvndTerraformPlayerSessionResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetPlayerSession200ApplicationvndTerraformPlayerSessionResponse) VisitGetPlayerSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/vnd.terraform.player_session")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetPlayerSession404Response struct {
}

func (response GetPlayerSession404Response) VisitGetPlayerSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdatePlayerSessionRequestObject struct {
	PlayerId string `json:"playerId"`
	Body     io.Reader
}

type UpdatePlayerSessionResponseObject interface {
	VisitUpdatePlayerSessionResponse(w http.ResponseWriter) error
}

type UpdatePlayerSession200Response struct {
}

func (response UpdatePlayerSession200Response) VisitUpdatePlayerSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetLocalSessionRequestObject struct {
	PlayerId string `json:"playerId"`
	WorldId  string `json:"worldId"`
}

type GetLocalSessionResponseObject interface {
	VisitGetLocalSessionResponse(w http.ResponseWriter) error
}

type GetLocalSession200ApplicationvndTerraformLocalSessionResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetLocalSession200ApplicationvndTerraformLocalSessionResponse) VisitGetLocalSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/vnd.terraform.local_session")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetLocalSession404Response struct {
}

func (response GetLocalSession404Response) VisitGetLocalSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateLocalSessionRequestObject struct {
	PlayerId string `json:"playerId"`
	WorldId  string `json:"worldId"`
	Body     io.Reader
}

type UpdateLocalSessionResponseObject interface {
	VisitUpdateLocalSessionResponse(w http.ResponseWriter) error
}

type UpdateLocalSession200Response struct {
}

func (response UpdateLocalSession200Response) VisitUpdateLocalSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /schem/{playerId})
	ListPlayerSchematics(ctx context.Context, request ListPlayerSchematicsRequestObject) (ListPlayerSchematicsResponseObject, error)

	// (DELETE /schem/{playerId}/{schemName})
	DeleteSchematic(ctx context.Context, request DeleteSchematicRequestObject) (DeleteSchematicResponseObject, error)

	// (GET /schem/{playerId}/{schemName})
	GetSchematicData(ctx context.Context, request GetSchematicDataRequestObject) (GetSchematicDataResponseObject, error)

	// (POST /schem/{playerId}/{schemName})
	CreateSchematic(ctx context.Context, request CreateSchematicRequestObject) (CreateSchematicResponseObject, error)

	// (PUT /schem/{playerId}/{schemName})
	UpdateSchematicHeader(ctx context.Context, request UpdateSchematicHeaderRequestObject) (UpdateSchematicHeaderResponseObject, error)
	// Fetch a player session by the player ID
	// (GET /session/{playerId})
	GetPlayerSession(ctx context.Context, request GetPlayerSessionRequestObject) (GetPlayerSessionResponseObject, error)
	// Update a player session by the player ID
	// (PUT /session/{playerId})
	UpdatePlayerSession(ctx context.Context, request UpdatePlayerSessionRequestObject) (UpdatePlayerSessionResponseObject, error)
	// Fetch a local session by the player ID and world ID
	// (GET /session/{playerId}/{worldId})
	GetLocalSession(ctx context.Context, request GetLocalSessionRequestObject) (GetLocalSessionResponseObject, error)
	// Update a local session by the player ID
	// (PUT /session/{playerId}/{worldId})
	UpdateLocalSession(ctx context.Context, request UpdateLocalSessionRequestObject) (UpdateLocalSessionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListPlayerSchematics operation middleware
func (sh *strictHandler) ListPlayerSchematics(w http.ResponseWriter, r *http.Request, playerId string) {
	var request ListPlayerSchematicsRequestObject

	request.PlayerId = playerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPlayerSchematics(ctx, request.(ListPlayerSchematicsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPlayerSchematics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPlayerSchematicsResponseObject); ok {
		if err := validResponse.VisitListPlayerSchematicsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSchematic operation middleware
func (sh *strictHandler) DeleteSchematic(w http.ResponseWriter, r *http.Request, playerId string, schemName string) {
	var request DeleteSchematicRequestObject

	request.PlayerId = playerId
	request.SchemName = schemName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSchematic(ctx, request.(DeleteSchematicRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSchematic")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSchematicResponseObject); ok {
		if err := validResponse.VisitDeleteSchematicResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSchematicData operation middleware
func (sh *strictHandler) GetSchematicData(w http.ResponseWriter, r *http.Request, playerId string, schemName string) {
	var request GetSchematicDataRequestObject

	request.PlayerId = playerId
	request.SchemName = schemName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSchematicData(ctx, request.(GetSchematicDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSchematicData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSchematicDataResponseObject); ok {
		if err := validResponse.VisitGetSchematicDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSchematic operation middleware
func (sh *strictHandler) CreateSchematic(w http.ResponseWriter, r *http.Request, playerId string, schemName string, params CreateSchematicParams) {
	var request CreateSchematicRequestObject

	request.PlayerId = playerId
	request.SchemName = schemName
	request.Params = params

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSchematic(ctx, request.(CreateSchematicRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSchematic")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSchematicResponseObject); ok {
		if err := validResponse.VisitCreateSchematicResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSchematicHeader operation middleware
func (sh *strictHandler) UpdateSchematicHeader(w http.ResponseWriter, r *http.Request, playerId string, schemName string) {
	var request UpdateSchematicHeaderRequestObject

	request.PlayerId = playerId
	request.SchemName = schemName

	var body UpdateSchematicHeaderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSchematicHeader(ctx, request.(UpdateSchematicHeaderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSchematicHeader")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSchematicHeaderResponseObject); ok {
		if err := validResponse.VisitUpdateSchematicHeaderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlayerSession operation middleware
func (sh *strictHandler) GetPlayerSession(w http.ResponseWriter, r *http.Request, playerId string) {
	var request GetPlayerSessionRequestObject

	request.PlayerId = playerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlayerSession(ctx, request.(GetPlayerSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlayerSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPlayerSessionResponseObject); ok {
		if err := validResponse.VisitGetPlayerSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdatePlayerSession operation middleware
func (sh *strictHandler) UpdatePlayerSession(w http.ResponseWriter, r *http.Request, playerId string) {
	var request UpdatePlayerSessionRequestObject

	request.PlayerId = playerId

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdatePlayerSession(ctx, request.(UpdatePlayerSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdatePlayerSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdatePlayerSessionResponseObject); ok {
		if err := validResponse.VisitUpdatePlayerSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLocalSession operation middleware
func (sh *strictHandler) GetLocalSession(w http.ResponseWriter, r *http.Request, playerId string, worldId string) {
	var request GetLocalSessionRequestObject

	request.PlayerId = playerId
	request.WorldId = worldId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLocalSession(ctx, request.(GetLocalSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLocalSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLocalSessionResponseObject); ok {
		if err := validResponse.VisitGetLocalSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateLocalSession operation middleware
func (sh *strictHandler) UpdateLocalSession(w http.ResponseWriter, r *http.Request, playerId string, worldId string) {
	var request UpdateLocalSessionRequestObject

	request.PlayerId = playerId
	request.WorldId = worldId

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateLocalSession(ctx, request.(UpdateLocalSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateLocalSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateLocalSessionResponseObject); ok {
		if err := validResponse.VisitUpdateLocalSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
