// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: player_sessions.sql

package db

import (
	"context"
	"time"
)

const deletePlayerSession = `-- name: DeletePlayerSession :one
delete
from player_sessions
where player_id = $1
returning player_id, created_at, proxy_id, server_id, hidden, username, skin_texture, skin_signature, p_type, p_state, p_instance_id, p_map_id, p_start_time, last_seen, protocol_version
`

func (q *Queries) DeletePlayerSession(ctx context.Context, playerID string) (*PlayerSession, error) {
	row := q.db.QueryRow(ctx, deletePlayerSession, playerID)
	var i PlayerSession
	err := row.Scan(
		&i.PlayerID,
		&i.CreatedAt,
		&i.ProxyID,
		&i.ServerID,
		&i.Hidden,
		&i.Username,
		&i.SkinTexture,
		&i.SkinSignature,
		&i.PType,
		&i.PState,
		&i.PInstanceID,
		&i.PMapID,
		&i.PStartTime,
		&i.LastSeen,
		&i.ProtocolVersion,
	)
	return &i, err
}

const getPlayerSession = `-- name: GetPlayerSession :one
select player_id, created_at, proxy_id, server_id, hidden, username, skin_texture, skin_signature, p_type, p_state, p_instance_id, p_map_id, p_start_time, last_seen, protocol_version
from player_sessions
where player_id = $1
`

func (q *Queries) GetPlayerSession(ctx context.Context, playerID string) (*PlayerSession, error) {
	row := q.db.QueryRow(ctx, getPlayerSession, playerID)
	var i PlayerSession
	err := row.Scan(
		&i.PlayerID,
		&i.CreatedAt,
		&i.ProxyID,
		&i.ServerID,
		&i.Hidden,
		&i.Username,
		&i.SkinTexture,
		&i.SkinSignature,
		&i.PType,
		&i.PState,
		&i.PInstanceID,
		&i.PMapID,
		&i.PStartTime,
		&i.LastSeen,
		&i.ProtocolVersion,
	)
	return &i, err
}

const listPlayerSessions = `-- name: ListPlayerSessions :many
select player_id, created_at, proxy_id, server_id, hidden, username, skin_texture, skin_signature, p_type, p_state, p_instance_id, p_map_id, p_start_time, last_seen, protocol_version
from player_sessions
`

func (q *Queries) ListPlayerSessions(ctx context.Context) ([]*PlayerSession, error) {
	rows, err := q.db.Query(ctx, listPlayerSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PlayerSession
	for rows.Next() {
		var i PlayerSession
		if err := rows.Scan(
			&i.PlayerID,
			&i.CreatedAt,
			&i.ProxyID,
			&i.ServerID,
			&i.Hidden,
			&i.Username,
			&i.SkinTexture,
			&i.SkinSignature,
			&i.PType,
			&i.PState,
			&i.PInstanceID,
			&i.PMapID,
			&i.PStartTime,
			&i.LastSeen,
			&i.ProtocolVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimedOutPlayers = `-- name: ListTimedOutPlayers :many
select player_id
from player_sessions
where last_seen < now() - interval '30 seconds'
  and server_id != 'devserver'
`

func (q *Queries) ListTimedOutPlayers(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTimedOutPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var player_id string
		if err := rows.Scan(&player_id); err != nil {
			return nil, err
		}
		items = append(items, player_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerLastSeenByServer = `-- name: UpdatePlayerLastSeenByServer :exec
update player_sessions
set last_seen = now()
where server_id = $1::text
  and player_id = any ($2::uuid[])
`

func (q *Queries) UpdatePlayerLastSeenByServer(ctx context.Context, column1 string, players []string) error {
	_, err := q.db.Exec(ctx, updatePlayerLastSeenByServer, column1, players)
	return err
}

const upsertPlayerSession = `-- name: UpsertPlayerSession :one
insert into player_sessions(player_id, proxy_id, server_id, hidden, username, skin_texture, skin_signature,
                            protocol_version,
                            p_type, p_state, p_instance_id, p_map_id, p_start_time)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
on conflict (player_id) do update
  set proxy_id         = excluded.proxy_id,
      server_id        = excluded.server_id,
      hidden           = excluded.hidden,
      username         = excluded.username,
      skin_texture     = excluded.skin_texture,
      skin_signature   = excluded.skin_signature,
      protocol_version = excluded.protocol_version,
      p_type           = excluded.p_type,
      p_state          = excluded.p_state,
      p_instance_id    = excluded.p_instance_id,
      p_map_id         = excluded.p_map_id,
      p_start_time     = excluded.p_start_time
returning player_id, created_at, proxy_id, server_id, hidden, username, skin_texture, skin_signature, p_type, p_state, p_instance_id, p_map_id, p_start_time, last_seen, protocol_version
`

type UpsertPlayerSessionParams struct {
	PlayerID        string
	ProxyID         string
	ServerID        *string
	Hidden          bool
	Username        *string
	SkinTexture     string
	SkinSignature   string
	ProtocolVersion int32
	PType           *string
	PState          *string
	PInstanceID     *string
	PMapID          *string
	PStartTime      *time.Time
}

func (q *Queries) UpsertPlayerSession(ctx context.Context, arg UpsertPlayerSessionParams) (*PlayerSession, error) {
	row := q.db.QueryRow(ctx, upsertPlayerSession,
		arg.PlayerID,
		arg.ProxyID,
		arg.ServerID,
		arg.Hidden,
		arg.Username,
		arg.SkinTexture,
		arg.SkinSignature,
		arg.ProtocolVersion,
		arg.PType,
		arg.PState,
		arg.PInstanceID,
		arg.PMapID,
		arg.PStartTime,
	)
	var i PlayerSession
	err := row.Scan(
		&i.PlayerID,
		&i.CreatedAt,
		&i.ProxyID,
		&i.ServerID,
		&i.Hidden,
		&i.Username,
		&i.SkinTexture,
		&i.SkinSignature,
		&i.PType,
		&i.PState,
		&i.PInstanceID,
		&i.PMapID,
		&i.PStartTime,
		&i.LastSeen,
		&i.ProtocolVersion,
	)
	return &i, err
}
