// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: server_states.sql

package db

import (
	"context"
	"time"
)

const countMapIsolatesByStatus = `-- name: CountMapIsolatesByStatus :many
select status_v2, count(*) as count
from server_states
where role = 'map-isolate'
group by status_v2
`

type CountMapIsolatesByStatusRow struct {
	StatusV2 string
	Count    int64
}

func (q *Queries) CountMapIsolatesByStatus(ctx context.Context) ([]*CountMapIsolatesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countMapIsolatesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CountMapIsolatesByStatusRow
	for rows.Next() {
		var i CountMapIsolatesByStatusRow
		if err := rows.Scan(&i.StatusV2, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteServerState = `-- name: DeleteServerState :exec
delete
from server_states
where id = $1
`

func (q *Queries) DeleteServerState(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteServerState, id)
	return err
}

const getFirstServerStateByMap = `-- name: GetFirstServerStateByMap :one
select server_states.id, server_states.role, server_states.start_time, server_states.status, server_states.cluster_ip, server_states.status_v2, server_states.status_since
from server_states
         inner join public.map_states ms on server_states.id = ms.server
where map_id = $1
  and status_v2 = 'active'
`

func (q *Queries) GetFirstServerStateByMap(ctx context.Context, mapID string) (*ServerState, error) {
	row := q.db.QueryRow(ctx, getFirstServerStateByMap, mapID)
	var i ServerState
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.StartTime,
		&i.Status,
		&i.ClusterIp,
		&i.StatusV2,
		&i.StatusSince,
	)
	return &i, err
}

const getServerState = `-- name: GetServerState :one
select id, role, start_time, status, cluster_ip, status_v2, status_since
from server_states
where id = $1
`

func (q *Queries) GetServerState(ctx context.Context, id string) (*ServerState, error) {
	row := q.db.QueryRow(ctx, getServerState, id)
	var i ServerState
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.StartTime,
		&i.Status,
		&i.ClusterIp,
		&i.StatusV2,
		&i.StatusSince,
	)
	return &i, err
}

const insertServerState = `-- name: InsertServerState :one
insert into server_states(id, role, status, cluster_ip)
values ($1, $2, $3, $4)
returning id, role, start_time, status, cluster_ip, status_v2, status_since
`

type InsertServerStateParams struct {
	ID        string
	Role      string
	Status    int32
	ClusterIp string
}

func (q *Queries) InsertServerState(ctx context.Context, arg InsertServerStateParams) (*ServerState, error) {
	row := q.db.QueryRow(ctx, insertServerState,
		arg.ID,
		arg.Role,
		arg.Status,
		arg.ClusterIp,
	)
	var i ServerState
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.StartTime,
		&i.Status,
		&i.ClusterIp,
		&i.StatusV2,
		&i.StatusSince,
	)
	return &i, err
}

const listServerIDs = `-- name: ListServerIDs :many
select id
from server_states
`

func (q *Queries) ListServerIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listServerIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersWithRoleExcept = `-- name: ListServersWithRoleExcept :many
select id
from server_states
where role = $1
  and status = 1
  and id != $2::text
`

func (q *Queries) ListServersWithRoleExcept(ctx context.Context, role string, excluding string) ([]string, error) {
	rows, err := q.db.Query(ctx, listServersWithRoleExcept, role, excluding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServerState = `-- name: UpdateServerState :exec
update server_states
set status       = $2,
    cluster_ip   = $3,
    status_v2    = $4,
    status_since = $5
where id = $1
`

type UpdateServerStateParams struct {
	ID          string
	Status      int32
	ClusterIp   string
	StatusV2    string
	StatusSince time.Time
}

func (q *Queries) UpdateServerState(ctx context.Context, arg UpdateServerStateParams) error {
	_, err := q.db.Exec(ctx, updateServerState,
		arg.ID,
		arg.Status,
		arg.ClusterIp,
		arg.StatusV2,
		arg.StatusSince,
	)
	return err
}

const updateServerStatus = `-- name: UpdateServerStatus :exec
update server_states
set status_v2    = $2,
    status_since = now()
where id = $1
`

func (q *Queries) UpdateServerStatus(ctx context.Context, iD string, statusV2 string) error {
	_, err := q.db.Exec(ctx, updateServerStatus, iD, statusV2)
	return err
}
