package text

var profanities = map[string][]string{
	"anuslick":   {},
	"arsehol":    {},
	"arselick":   {},
	"asslick":    {},
	"arsch":      {},
	"asshol":     {},
	"auschwitz":  {},
	"beaner":     {},
	"bestiality": {},
	"baise":      {},
	"bakachon":   {},
	"bakatyon":   {},
	"bastard": {
		"bastardized",
	},
	"bitch":       {},
	"btch":        {},
	"biatch":      {},
	"bussy":       {},
	"blowjob":     {},
	"blowme":      {},
	"bukakke":     {},
	"buttplug":    {},
	"buttchug":    {},
	"butagorosi":  {}, // https://www.urbandictionary.com/define.php?term=butagorosi
	"cagada":      {},
	"caralho":     {},
	"cameljockey": {},
	"castrate":    {},
	"cazzo":       {},
	"ceemen":      {},
	"chankoro":    {},
	"chink":       {},
	"chingchong":  {},
	"choad":       {},
	"chode":       {},
	"chlamydia":   {},
	"clit": {
		"clitheroe",
	},
	"clitoris": {},
	"cock": {
		"cockade",
		"cockatiel",
		"cockatiels",
		"cockatoo",
		"cockatoos",
		"cockatrice",
		"cockayne",
		"cockburn",
		"cockcroft",
		"cocked",
		"cocker",
		"cockerel",
		"cockers",
		"cockeyed",
		"cockiness",
		"cocking",
		"cocklebur",
		"cockney",
		"cockpit",
		"cockpits",
		"cockroach",
		"cockroaches",
		"cockscomb",
		"cockspur",
		"cocktail",
		"gamecock",
		"hancock",
		"haycock",
		"hitchcock",
		"leacock",
		"peacock",
		"shuttlecock",
		"stopcock",
		"woodcock",
	},
	"coon": {
		"cocoon",
		"laocoon",
		"raccoon",
		"racoon",
		"tycoon",
	},
	"cocain":    {},
	"coitus":    {},
	"cottonpic": {},
	"cottonpik": {},
	"cum": {
		"acumen",
		"acuminate",
		"altocumulus",
		"cumber",
		"cumbing",
		"cumbria",
		"cumbrian",
		"cumbrous",
		"cummerbund",
		"cumming",
		"cumulat",
		"cumuli",
		"cumulonimbus",
		"cumulus",
		"encumber",
		"encumbrance",
		"scumbag",
		"locum",
		"modicum",
		"magnacumlaude",
		"macumba",
		"practicum",
		"recumbent",
		"slocum",
		"stratocumulus",
		"succumb",
		"talcum",
		"taraxacum",
		"tecumseh",
		"tucuman",
		"capsicum",
		"cecum",
		"circum",
		"colchicum",
		"document",
		"ecumeni", // 'ecumenical' and 'ecumenism'
		"illyricum",
		"incumben", // 'incumbent' and 'incumbents' and 'incumbency'
	},
	"cunt": {
		"scunthorpe",
	},
	"cvnt":   {},
	"cunny":  {},
	"cunnie": {},
	"csam":   {},
	"cyka":   {},
	"darkie": {},
	"dick": {
		"chappaquiddick",
		"dickens",
		"dickensian",
		"dickerson",
		"dickey",
		"dickies",
		"dickinson",
		"dickson",
		"dickvandyke",
		"dicky",
	},
	"dildo":     {},
	"douchebag": {},
	"dyke": {
		"vandyke",
	},
	"downie":    {},
	"dumbass":   {},
	"ejaculate": {},
	"fag": {
		"antofagasta",
		"serfage",
		"wharfage",
		"fagin",
		"leafage",
	},
	"feck":        {},
	"fellate":     {},
	"fellatio":    {},
	"felch":       {},
	"fuck":        {},
	"fvck":        {},
	"fxck":        {},
	"fack":        {},
	"fzck":        {},
	"fck":         {},
	"fudgepacker": {},
	"flange": {
		"flanged",
		"flanges",
	},
	"gestapo": {},
	"gook":    {},
	"horny": {
		"thorny",
	},
	"hooker": {},
	"hitler": {},
	"incest": {},
	"jap": {
		"japan",
	},
	"jizz":        {},
	"jigabo":      {},
	"junglebunny": {},
	"kkk":         {},
	"kike":        {},
	"klux":        {},
	"kluklux":     {},
	"klukluxklan": {},
	"koon":        {},
	"lickmy":      {},
	"masturbat":   {},
	"molest":      {},
	"muff": {
		"muffed",
		"muffin",
		"muffins",
		"muffle",
		"muffled",
		"muffler",
		"mufflers",
		"muffles",
		"muffling",
		"muffs",
		"ragamuffin",
		"earmuff",
		"earmuffs",
	},
	"nazi": {
		"ashkenazi",
		"ashkenazic",
		"ashkenazim",
		"monazite",
	},
	"nigg":   {},
	"niqa":   {},
	"nigga":  {},
	"niqqa":  {},
	"niggu":  {},
	"niqqu":  {},
	"niggr":  {},
	"nigger": {},
	"niglet": {},
	"nignog": {},
	"paki": {
		"pakistan",
	},
	"penis": {
		"openis", // 'open is' matching against 'penis'
		"penistone",
	},
	"porn":      {},
	"prostitut": {},
	"pube":      {},
	"pussie":    {},
	"pussy": {
		"pussycat",
		"pussyfoot",
	},
	"raghead": {},
	"rape": {
		"grape",
		"forape", // for a permanent... (matches rape)
		"trapeze",
		"trapezium",
		"trapezius",
		"trapezoid",
		"therapeutic",
		"drape",
		"parapet",
		"rapeseed",
		"scrape", // scrap, scrape, scraping
		"serape",
	},
	"rapist": {
		"therapist",
	},
	"retard": {
		"retardant",
		"retarder",
		"retarding",
	},
	"rimjob": {},
	"shit": {
		"cushitic",
		"shitake",
		"pushit",
		"peshitta",
		"libshitz",
		"shitzu",
		"wishit",
		"yamashita",
		"finishit",
		"shitbox",   // 'hitbox'
		"shiTMG",    // 'iTMG'
		"publishit", // 'publish'
		"englishit", // 'english'
	},
	"slut": {},
	"spunk": {
		"spunky",
	},
	"suckmy": {},
	"sodom":  {},
	"semen": {
		"sement",
	},
	"teensex": {},
	"tittie":  {},
	"titty":   {},
	"trannie": {},
	"tranny":  {},
	"vagina":  {},
	"wank": {
		"swank",
		"wankel",
	},
	"wetback": {},
	"whore": {
		"whores",      // who responded, who restarted, etc..
		"whorev",      // who revolutionized, who revolted, etc..
		"whoreturned", // who returned (can't unblock whoret or someone can say whore tits)
	},
	"whitepower": {},
	"fondle":     {},
	"minestorm":  {},
	"kissmy":     {},
	"blowmy":     {},
	"jelqing":    {},
	"dafuq":      {},
}
