openapi: 3.0.2
info:
  title: Map Service Public API
  version: "1"
paths:
  /stats:
    get:
      operationId: getMapStats
      summary: Fetch public map statistics
      description: long description TODO
      responses:
        '200':
          description: 'Public map statistics'
          content:
            application/json:
              schema:
                type: object
                required: [totalMaps, totalFails]
                properties:
                  totalMaps:
                    description: The total number of maps
                    type: integer
                  totalFails:
                    description: The total number of failed maps
                    type: integer

components:
  responses:
    BadRequest:
      description: Invalid input
      content:
        application/json:
          schema:
            type: object
            required: [message]
            properties:
              message:
                type: string
  schemas:
    Point:
      type: object
      required: [ x, y, z ]
      properties:
        x: { type: number }
        y: { type: number }
        z: { type: number }
    Pos:
      allOf:
        - $ref: '#/components/schemas/Point'
        - type: object
          required: [ yaw, pitch ]
          properties:
            yaw: { type: number }
            pitch: { type: number }

    MapManualTriggerWebhook:
      description: >-
        A webhook payload when a map manual trigger is pressed in an organization map.
      type: object
      required: [ sender, orgId, mapId, timestamp ]
      properties:
        sender:
          description: The UUID of the user who triggered the event
          type: string
        orgId:
          description: The ID of the organization who owns the map
          type: string
        mapId:
          description: The ID of the map
          type: string
        timestamp:
          description: The timestamp of the event in iso format
          type: string
          format: date-time
