global:
  nameOverride: player-service
  fullnameOverride: player-service

base:
  image:
    repository: mworzala/player-service
  imagePullSecrets:
    - name: dockerio

  service:
    extraPorts:
      - name: grpc
        containerPort: 9001
