replicaCount: 1

base:
  cluster: "prod"

  service:
    monitor:
      enabled: true

  env:
    PLAYERS_ENV: "prod"
    PLAYERS_HTTP_ADDRESS: "0.0.0.0"
    PLAYERS_HTTP_PORT: "9124"

    PLAYERS_OTLP_ENDPOINT: "tempo.monitoring.svc.cluster.local:4318"

    PLAYERS_NATS_SERVERS: "nats://nats:4222"
    PLAYERS_REDIS_ADDRESS: "redis-master.mapmaker.svc.cluster.local:6379"

    PLAYERS_S3_ENDPOINT: "https://bdb9cb2904188b760591dc1589a1ccf3.r2.cloudflarestorage.com"

    PLAYERS_DISCORD_APPLICATION_ID: "1086860126020964423"
