replicaCount: 1

base:
  image:
    repository: player-service

  imagePullSecrets: []
  volumes: []
  volumeMounts: []

  env:
    PLAYERS_ENV: "tilt"
    PLAYERS_HTTP_ADDRESS: "0.0.0.0"
    PLAYERS_HTTP_PORT: "9124"
    PLAYERS_POSTGRES_URI: "postgres://postgres:postgres@postgres-postgresql:5432/player-service?sslmode=disable"
    PLAYERS_KAFKA_BROKERS: "kafka:9093"
    PLAYERS_NATS_SERVERS: "nats://nats:4222"
    PLAYERS_REDIS_ADDRESS: "redis-master:6379"

    PLAYERS_TEBEX_SECRET: "explicit_ignore"
