// Code generated by ox. DO NOT EDIT.

package v1Public

import (
	"net/http"

	"github.com/hollow-cube/api-server/pkg/ox/runtime"
)

// RegisterParams configures route registration.
type RegisterParams struct {
	Mux     *http.ServeMux
	BaseURL string // Optional prefix for all routes
}

// RegisterRoutes registers all API routes on the given ServeMux.
func RegisterRoutes(s *Server, params RegisterParams) {
	h := &handlers{server: s}
	params.Mux.HandleFunc("GET "+params.BaseURL+"/@me/status", h.getPlayerStatus)
}

// handlers wraps the server and provides HTTP handler methods.
type handlers struct {
	server *Server
}

func (h *handlers) getPlayerStatus(w http.ResponseWriter, r *http.Request) {
	var req AuthenticatedRequest
	req.PlayerID = r.Header.Get("x-auth-user")
	resp, err := h.server.GetPlayerStatus(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}
