// Code generated by ox. DO NOT EDIT.

package v1Public

import (
	"io"
	"net/http"

	"github.com/hollow-cube/api-server/pkg/ox/runtime"
)

// RegisterParams configures route registration.
type RegisterParams struct {
	Mux     *http.ServeMux
	BaseURL string // Optional prefix for all routes
}

// RegisterRoutes registers all API routes on the given ServeMux.
func RegisterRoutes(s *Server, params RegisterParams) {
	h := &handlers{server: s}
	params.Mux.HandleFunc("POST "+params.BaseURL+"/auth/redeem", h.redeemLaunchGrant)
	params.Mux.HandleFunc("POST "+params.BaseURL+"/auth/token", h.refreshAccessToken)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/maps/{mapId}/editor/bootstrap", h.getEditorBootstrap)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/maps/{mapId}/editor/events", h.streamEditorEvents)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/maps/{mapId}/files", h.getMapFiles)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/maps/{mapId}/files/{path...}", h.getMapFile)
	params.Mux.HandleFunc("PUT "+params.BaseURL+"/maps/{mapId}/files/{path...}", h.updateMapFile)
	params.Mux.HandleFunc("DELETE "+params.BaseURL+"/maps/{mapId}/files/{path...}", h.deleteMapFile)
	params.Mux.HandleFunc("GET "+params.BaseURL+"/@me/status", h.getPlayerStatus)
}

// handlers wraps the server and provides HTTP handler methods.
type handlers struct {
	server *Server
}

func (h *handlers) redeemLaunchGrant(w http.ResponseWriter, r *http.Request) {
	var req RedeemRequest
	req.DPoP = r.Header.Get("DPoP")
	if err := runtime.DecodeJSON(r, &req.Body); err != nil {
		runtime.WriteBadRequest(w, "invalid request body")
		return
	}
	resp, err := h.server.RedeemLaunchGrant(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) refreshAccessToken(w http.ResponseWriter, r *http.Request) {
	var req RefreshAccessTokenRequest
	req.DPoP = r.Header.Get("DPoP")
	if err := runtime.DecodeJSON(r, &req.Body); err != nil {
		runtime.WriteBadRequest(w, "invalid request body")
		return
	}
	resp, err := h.server.RefreshAccessToken(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) getEditorBootstrap(w http.ResponseWriter, r *http.Request) {
	var req MapRequest
	req.MapID = r.PathValue("mapId")
	resp, err := h.server.GetEditorBootstrap(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) streamEditorEvents(w http.ResponseWriter, r *http.Request) {
	var req StreamEditorEventsRequest
	req.MapID = r.PathValue("mapId")
	req.LastEventID = r.Header.Get("Last-Event-ID")
	resp, err := h.server.StreamEditorEvents(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteSSE[EditorEvent](w, r, resp)
}

func (h *handlers) getMapFiles(w http.ResponseWriter, r *http.Request) {
	var req MapRequest
	req.MapID = r.PathValue("mapId")
	resp, err := h.server.GetMapFiles(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) getMapFile(w http.ResponseWriter, r *http.Request) {
	var req GetMapFileRequest
	req.MapID = r.PathValue("mapId")
	req.Path = r.PathValue("path")
	req.IfNoneMatch = r.Header.Get("If-None-Match")
	resp, err := h.server.GetMapFile(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteStream(w, 200, resp)
}

func (h *handlers) updateMapFile(w http.ResponseWriter, r *http.Request) {
	var req UpdateMapFileRequest
	req.MapID = r.PathValue("mapId")
	req.Path = r.PathValue("path")
	req.ContentType = r.Header.Get("Content-Type")
	req.IfMatch = r.Header.Get("If-Match")
	req.IfNoneMatch = r.Header.Get("If-None-Match")
	if b, err := io.ReadAll(r.Body); err != nil {
		runtime.WriteBadRequest(w, "failed to read request body")
		return
	} else {
		req.Body = b
	}
	resp, err := h.server.UpdateMapFile(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}

func (h *handlers) deleteMapFile(w http.ResponseWriter, r *http.Request) {
	var req DeleteMapFileRequest
	req.MapID = r.PathValue("mapId")
	req.Path = r.PathValue("path")
	req.IfMatch = r.Header.Get("If-Match")
	req.IfNoneMatch = r.Header.Get("If-None-Match")
	err := h.server.DeleteMapFile(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	w.WriteHeader(204)
}

func (h *handlers) getPlayerStatus(w http.ResponseWriter, r *http.Request) {
	var req AuthenticatedRequest
	req.PlayerID = r.Header.Get("x-auth-user")
	resp, err := h.server.GetPlayerStatus(r.Context(), req)
	if err != nil {
		runtime.HandleError(w, err)
		return
	}
	runtime.WriteJSON(w, 200, resp)
}
