replicaCount: 1

base:
  cluster: "prod"
  imagePullSecrets:
    - name: dockerio

  service:
    monitor:
      enabled: true

  env:
    SESSION_ENV: "prod"
    SESSION_HTTP_ADDRESS: "0.0.0.0"
    SESSION_HTTP_PORT: "9124"

    SESSION_POSTHOG_ENDPOINT: "http://player-service.mapmaker.svc.cluster.local:9124/posthog"

    SESSION_REDIS_ADDRESS: "redis-master.mapmaker.svc.cluster.local:6379"
    SESSION_PLAYER_SERVICE_URL: "http://player-service.mapmaker.svc.cluster.local:9124"
    SESSION_MAP_SERVICE_URL: "http://map-service.mapmaker.svc.cluster.local:9124"
    SESSION_KAFKA_BROKERS: "kafka.mapmaker.svc.cluster.local:9093"
    SESSION_NATS_SERVERS: "nats://nats:4222"
    SESSION_SPICEDB_ENDPOINT: "spicedb.mapmaker.svc.cluster.local:50051"

    SESSION_OTLP_ENDPOINT: "tempo.monitoring.svc.cluster.local:4318"

    SESSION_KUBERNETES_NAMESPACE: "mapmaker"
