@startuml
'https://plantuml.com/object-diagram

'Object stored in postgres
object Punishment {
  playerId: UUID
  executorId: UUID
  type: PunishmentType
  createdAt: Unix timestamp
  ladderId: string
  comment: string
  revokedBy: UUID
  revokedAt: Unix timestamp
  revokedReason: Component
}

'Object stored in config
object Ladder {
  id: string
  name: string
  punishmentType: PunishmentType
  entries: LadderEntry[]
}

object LadderEntry {
  duration: ISO 8601 duration
  message: string
}

enum PunishmentType {
  BAN
  MUTE
  KICK
}

'Used to indicate the player should be kicked from whatever proxy they are on
object PlayerBannedMessage {
  playerId: UUID
  kickMessage: JSON Component
}

@enduml
