@startuml
'https://plantuml.com/sequence-diagram

title Payment Processing

participant tebex
participant "player-service" as player
queue kafka
database postgres
database spicedb
database discord

== On Webhook Event ==
autonumber

tebex->player: New event
player->player: Validate signature & body
player->kafka: Produce event body (partitioned by customer id)
kafka->player: ack
player->tebex: OK

== ""payment.completed"" ==
autonumber

note right of player: Only handle cubits events here\nHypercube is handled through\nrecurring-payment events.
kafka->player: Consume event

group transaction
player->postgres: Write to ""player_data""\n""(cubits+=100)""
player->postgres: Write to ""tebex_log"" for reversion\n""(tx_id=..,time=now,type=cubits,amount=100,reverted=false)""
player->postgres: Write to ""tx_log""\n""(tx_id=..,time=now,raw=..)""
end

== ""payment.refunded"" ==
autonumber

kafka->player: Consume event

player->postgres: Fetch ""tebex_log(tx_id=..,reverted=false)""
postgres->player: Valid entry

group transaction
alt Cubits
player->postgres: Write to ""player_data""\n""(cubits=min(0,cubits-100))""
else Hypercube
player->spicedb: Get ""mapmaker/platform:0 {player}:hypercube""\nSelect ""expiration"" from caveat context.

player->spicedb: Set ""mapmaker/platform:0 {player}:hypercube""\nSet ""expiration"" in caveat context.
end
player->postgres: Write to ""tebex_log""\n""(reverted=true)""
end

== payment.dispute.opened ==
autonumber

kafka->player: Consume event

player->discord: Send message to ""#admin-chat""

== payment.dispute.won ==
autonumber

kafka->player: Consume event
player->player: What do we do??

== payment.dispute.lost ==
autonumber

kafka->player: Consume event

player->player: Ban the player\n""(length=permanent,reason=dispute)""

== recurring-payment.started ==
autonumber

kafka->player: Consume event

player->spicedb: Get ""mapmaker/platform:0 {player}:hypercube""\nSelect ""expiration"" from caveat context.

group 2-phase commit
player->spicedb: Set ""mapmaker/platform:0 {player}:hypercube""\nSet ""expiration"" in caveat context.
player->postgres: Write to ""tebex_log""\n""(tx_id=..,time=now,type=hypercube,amount=30d,reverted=false)""
player->postgres: Write to ""tx_log""\n""(tx_id=..,time=now,raw=..)""
end

== recurring-payment.renewed ==
autonumber

note left of kafka: Same logic as ""recurring-payment.started""


@enduml