// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ip_history.sql

package playerdb

import (
	"context"
)

const addPlayerIP = `-- name: AddPlayerIP :exec
insert into public.ip_history (player_id, address, first_seen, last_seen, seen_count)
values ($1, $2, now(), now(), 1)
on conflict (player_id, address) do update set last_seen  = excluded.last_seen,
                                               seen_count = ip_history.seen_count + 1
`

func (q *Queries) AddPlayerIP(ctx context.Context, playerID string, address string) error {
	_, err := q.db.Exec(ctx, addPlayerIP, playerID, address)
	return err
}

const getPlayerIPHistory = `-- name: GetPlayerIPHistory :many
select address
from public.ip_history
where player_id = $1
order by last_seen desc
`

func (q *Queries) GetPlayerIPHistory(ctx context.Context, playerID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getPlayerIPHistory, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersByIPs = `-- name: GetPlayersByIPs :many
select player_data.id, player_data.username, player_data.first_join, player_data.last_online, player_data.playtime, player_data.experience, player_data.beta_enabled, player_data.settings, player_data.coins, player_data.cubits, player_data.skin, player_data.online, player_data.hypercube_start, player_data.hypercube_end, player_data.role, player_data.extra_map_slots, player_data.max_map_size, player_data.map_builders
from ip_history
         inner join player_data on ip_history.player_id = player_data.id
where address = ANY ($1::text[])
group by player_data.id
`

func (q *Queries) GetPlayersByIPs(ctx context.Context, dollar_1 []string) ([]PlayerData, error) {
	rows, err := q.db.Query(ctx, getPlayersByIPs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerData{}
	for rows.Next() {
		var i PlayerData
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstJoin,
			&i.LastOnline,
			&i.Playtime,
			&i.Experience,
			&i.BetaEnabled,
			&i.Settings,
			&i.Coins,
			&i.Cubits,
			&i.Skin,
			&i.Online,
			&i.HypercubeStart,
			&i.HypercubeEnd,
			&i.Role,
			&i.ExtraMapSlots,
			&i.MaxMapSize,
			&i.MapBuilders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
