// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: linked_accounts.sql

package playerdb

import (
	"context"
	"time"
)

const addLinkedAccount = `-- name: AddLinkedAccount :exec
insert into linked_accounts (player_id, social_id, type)
values ($2, $3, $1)
`

func (q *Queries) AddLinkedAccount(ctx context.Context, type_ string, playerID string, socialID string) error {
	_, err := q.db.Exec(ctx, addLinkedAccount, type_, playerID, socialID)
	return err
}

const deletePendingVerificationBySecret = `-- name: DeletePendingVerificationBySecret :exec
delete
from pending_verification
where type = $1
  and user_secret = $2
`

func (q *Queries) DeletePendingVerificationBySecret(ctx context.Context, type_ string, userSecret string) error {
	_, err := q.db.Exec(ctx, deletePendingVerificationBySecret, type_, userSecret)
	return err
}

const getPendingVerificationBySecret = `-- name: GetPendingVerificationBySecret :one
select type, user_id, user_secret, expiration
from pending_verification
where type = $1
  and user_secret = $2
`

func (q *Queries) GetPendingVerificationBySecret(ctx context.Context, type_ string, userSecret string) (PendingVerification, error) {
	row := q.db.QueryRow(ctx, getPendingVerificationBySecret, type_, userSecret)
	var i PendingVerification
	err := row.Scan(
		&i.Type,
		&i.UserID,
		&i.UserSecret,
		&i.Expiration,
	)
	return i, err
}

const lookupPlayerDataBySocialId = `-- name: LookupPlayerDataBySocialId :one
select player_data.id, player_data.username, player_data.first_join, player_data.last_online, player_data.playtime, player_data.experience, player_data.beta_enabled, player_data.settings, player_data.coins, player_data.cubits, player_data.skin, player_data.online, player_data.hypercube_start, player_data.hypercube_end, player_data.role, player_data.extra_map_slots, player_data.max_map_size, player_data.map_builders
from player_data
  inner join linked_accounts linked on linked.player_id = player_data.id
where linked.type = $1
  and linked.social_id = $2
`

func (q *Queries) LookupPlayerDataBySocialId(ctx context.Context, type_ string, socialID string) (PlayerData, error) {
	row := q.db.QueryRow(ctx, lookupPlayerDataBySocialId, type_, socialID)
	var i PlayerData
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstJoin,
		&i.LastOnline,
		&i.Playtime,
		&i.Experience,
		&i.BetaEnabled,
		&i.Settings,
		&i.Coins,
		&i.Cubits,
		&i.Skin,
		&i.Online,
		&i.HypercubeStart,
		&i.HypercubeEnd,
		&i.Role,
		&i.ExtraMapSlots,
		&i.MaxMapSize,
		&i.MapBuilders,
	)
	return i, err
}

const lookupSocialIdByPlayerId = `-- name: LookupSocialIdByPlayerId :one
select social_id
from linked_accounts
where type = $1
  and player_id = $2
`

func (q *Queries) LookupSocialIdByPlayerId(ctx context.Context, type_ string, playerID string) (string, error) {
	row := q.db.QueryRow(ctx, lookupSocialIdByPlayerId, type_, playerID)
	var social_id string
	err := row.Scan(&social_id)
	return social_id, err
}

const upsertPendingVerification = `-- name: UpsertPendingVerification :exec
insert into pending_verification (type, user_id, user_secret, expiration)
values ($1, $2, $3, $4)
on conflict (type, user_id)
  do update set user_secret = $3,
                expiration  = $4
`

type UpsertPendingVerificationParams struct {
	Type       string    `json:"type"`
	UserID     string    `json:"userId"`
	UserSecret string    `json:"userSecret"`
	Expiration time.Time `json:"expiration"`
}

func (q *Queries) UpsertPendingVerification(ctx context.Context, arg UpsertPendingVerificationParams) error {
	_, err := q.db.Exec(ctx, upsertPendingVerification,
		arg.Type,
		arg.UserID,
		arg.UserSecret,
		arg.Expiration,
	)
	return err
}
