// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifcations.sql

package playerdb

import (
	"context"
	"time"
)

const deleteMatching = `-- name: DeleteMatching :many
update player_notifications
set deleted_at = now()
where deleted_at is null
  and ($1::uuid is null or player_id = $1::uuid)
  and ($2::text is null or key = $2::text)
returning id, player_id, type, key, data, created_at, read_at, expires_at, deleted_at
`

func (q *Queries) DeleteMatching(ctx context.Context, playerID *string, key *string) ([]PlayerNotification, error) {
	rows, err := q.db.Query(ctx, deleteMatching, playerID, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerNotification{}
	for rows.Next() {
		var i PlayerNotification
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Type,
			&i.Key,
			&i.Data,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ExpiresAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteNotification = `-- name: DeleteNotification :execrows
update player_notifications
set deleted_at = now()
where id = $1
  and deleted_at is null
`

func (q *Queries) DeleteNotification(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotification, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotifications = `-- name: GetNotifications :many
select player_notifications.id, player_notifications.player_id, player_notifications.type, player_notifications.key, player_notifications.data, player_notifications.created_at, player_notifications.read_at, player_notifications.expires_at, player_notifications.deleted_at,
       count(*) over () as total_count
from player_notifications
where player_id = $1
  and deleted_at is null
  and (expires_at is null or expires_at > now())
  and (not $2 or read_at is null)
order by created_at desc
limit $3 offset $4
`

type GetNotificationsParams struct {
	PlayerID string      `json:"playerId"`
	Column2  interface{} `json:"column2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetNotificationsRow struct {
	PlayerNotification PlayerNotification `json:"playerNotification"`
	TotalCount         int64              `json:"totalCount"`
}

func (q *Queries) GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]GetNotificationsRow, error) {
	rows, err := q.db.Query(ctx, getNotifications,
		arg.PlayerID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNotificationsRow{}
	for rows.Next() {
		var i GetNotificationsRow
		if err := rows.Scan(
			&i.PlayerNotification.ID,
			&i.PlayerNotification.PlayerID,
			&i.PlayerNotification.Type,
			&i.PlayerNotification.Key,
			&i.PlayerNotification.Data,
			&i.PlayerNotification.CreatedAt,
			&i.PlayerNotification.ReadAt,
			&i.PlayerNotification.ExpiresAt,
			&i.PlayerNotification.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
update player_notifications
set read_at = now()
where id = $1
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationUnread = `-- name: MarkNotificationUnread :execrows
update player_notifications
set read_at = null
where id = $1
`

func (q *Queries) MarkNotificationUnread(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationUnread, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unsafe_AddNotification = `-- name: Unsafe_AddNotification :exec
insert into player_notifications (id, type, key, player_id, data, expires_at)
values (gen_random_uuid(), $1, $2, $3, $4, $5)
`

type Unsafe_AddNotificationParams struct {
	Type      string          `json:"type"`
	Key       string          `json:"key"`
	PlayerID  string          `json:"playerId"`
	Data      *map[string]any `json:"data"`
	ExpiresAt *time.Time      `json:"expiresAt"`
}

func (q *Queries) Unsafe_AddNotification(ctx context.Context, arg Unsafe_AddNotificationParams) error {
	_, err := q.db.Exec(ctx, unsafe_AddNotification,
		arg.Type,
		arg.Key,
		arg.PlayerID,
		arg.Data,
		arg.ExpiresAt,
	)
	return err
}

const unsafe_DeleteNotification = `-- name: Unsafe_DeleteNotification :exec
delete
from player_notifications
where type = $1
  and key = $2
  and player_id = $3
`

func (q *Queries) Unsafe_DeleteNotification(ctx context.Context, type_ string, key string, playerID string) error {
	_, err := q.db.Exec(ctx, unsafe_DeleteNotification, type_, key, playerID)
	return err
}
