// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: player_data.sql

package playerdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateTOTP = `-- name: ActivateTOTP :one
update player_totp
set active = true
where player_id = $1
  and key = $2
  and active = false
returning 1
`

func (q *Queries) ActivateTOTP(ctx context.Context, playerID string, key []byte) (int32, error) {
	row := q.db.QueryRow(ctx, activateTOTP, playerID, key)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const addTOTP = `-- name: AddTOTP :execrows
insert into player_totp (player_id, active, key, recovery_codes)
values ($1, $2, $3, $4)
on conflict (player_id)
  do update set key            = excluded.key,
                recovery_codes = excluded.recovery_codes,
                created_at     = now()
where player_totp.active = false
`

type AddTOTPParams struct {
	PlayerID      string   `json:"playerId"`
	Active        *bool    `json:"active"`
	Key           []byte   `json:"key"`
	RecoveryCodes []string `json:"recoveryCodes"`
}

func (q *Queries) AddTOTP(ctx context.Context, arg AddTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTOTP,
		arg.PlayerID,
		arg.Active,
		arg.Key,
		arg.RecoveryCodes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const appendHypercube = `-- name: AppendHypercube :exec
update player_data
set hypercube_start = case
                        when hypercube_start is null or hypercube_end < now()
                          then now()
                        else hypercube_end
  end,
    hypercube_end   = greatest(coalesce(hypercube_end, now()), now()) + $2::interval
where id = $1
`

func (q *Queries) AppendHypercube(ctx context.Context, iD string, column2 pgtype.Interval) error {
	_, err := q.db.Exec(ctx, appendHypercube, iD, column2)
	return err
}

const createPlayerData = `-- name: CreatePlayerData :one
insert into player_data (id, username, first_join, last_online, skin, online)
values ($1, $2, now(), now(), $3, false)
returning id, username, first_join, last_online, playtime, experience, beta_enabled, settings, coins, cubits, skin, online, hypercube_start, hypercube_end, role, extra_map_slots, max_map_size, map_builders
`

func (q *Queries) CreatePlayerData(ctx context.Context, iD string, username string, skin *PlayerSkin) (PlayerData, error) {
	row := q.db.QueryRow(ctx, createPlayerData, iD, username, skin)
	var i PlayerData
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstJoin,
		&i.LastOnline,
		&i.Playtime,
		&i.Experience,
		&i.BetaEnabled,
		&i.Settings,
		&i.Coins,
		&i.Cubits,
		&i.Skin,
		&i.Online,
		&i.HypercubeStart,
		&i.HypercubeEnd,
		&i.Role,
		&i.ExtraMapSlots,
		&i.MaxMapSize,
		&i.MapBuilders,
	)
	return i, err
}

const deleteTOTP = `-- name: DeleteTOTP :exec
delete
from player_totp
where player_id = $1
`

func (q *Queries) DeleteTOTP(ctx context.Context, playerID string) error {
	_, err := q.db.Exec(ctx, deleteTOTP, playerID)
	return err
}

const getPlayerData = `-- name: GetPlayerData :one
select id, username, first_join, last_online, playtime, experience, beta_enabled, settings, coins, cubits, skin, online, hypercube_start, hypercube_end, role, extra_map_slots, max_map_size, map_builders
from player_data
where id = $1
limit 1
`

func (q *Queries) GetPlayerData(ctx context.Context, id string) (PlayerData, error) {
	row := q.db.QueryRow(ctx, getPlayerData, id)
	var i PlayerData
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstJoin,
		&i.LastOnline,
		&i.Playtime,
		&i.Experience,
		&i.BetaEnabled,
		&i.Settings,
		&i.Coins,
		&i.Cubits,
		&i.Skin,
		&i.Online,
		&i.HypercubeStart,
		&i.HypercubeEnd,
		&i.Role,
		&i.ExtraMapSlots,
		&i.MaxMapSize,
		&i.MapBuilders,
	)
	return i, err
}

const getPlayerStats = `-- name: GetPlayerStats :one
select count(*), sum(playtime)
from public.player_data
`

type GetPlayerStatsRow struct {
	Count int64 `json:"count"`
	Sum   int64 `json:"sum"`
}

func (q *Queries) GetPlayerStats(ctx context.Context) (GetPlayerStatsRow, error) {
	row := q.db.QueryRow(ctx, getPlayerStats)
	var i GetPlayerStatsRow
	err := row.Scan(&i.Count, &i.Sum)
	return i, err
}

const getTOTP = `-- name: GetTOTP :one
select player_id, created_at, active, key, recovery_codes
from player_totp
where player_id = $1
`

func (q *Queries) GetTOTP(ctx context.Context, playerID string) (PlayerTotp, error) {
	row := q.db.QueryRow(ctx, getTOTP, playerID)
	var i PlayerTotp
	err := row.Scan(
		&i.PlayerID,
		&i.CreatedAt,
		&i.Active,
		&i.Key,
		&i.RecoveryCodes,
	)
	return i, err
}

const legacySearchPlayersFuzzy = `-- name: LegacySearchPlayersFuzzy :many

select id, username, first_join, last_online, playtime, experience, beta_enabled, settings, coins, cubits, skin, online, hypercube_start, hypercube_end, role, extra_map_slots, max_map_size, map_builders
from player_data
where username ~* $1
limit $2
`

// SQLC is a bit dumb and redeclares the 'experience' variable so we have to rename it
func (q *Queries) LegacySearchPlayersFuzzy(ctx context.Context, username string, limit int32) ([]PlayerData, error) {
	rows, err := q.db.Query(ctx, legacySearchPlayersFuzzy, username, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerData{}
	for rows.Next() {
		var i PlayerData
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstJoin,
			&i.LastOnline,
			&i.Playtime,
			&i.Experience,
			&i.BetaEnabled,
			&i.Settings,
			&i.Coins,
			&i.Cubits,
			&i.Skin,
			&i.Online,
			&i.HypercubeStart,
			&i.HypercubeEnd,
			&i.Role,
			&i.ExtraMapSlots,
			&i.MaxMapSize,
			&i.MapBuilders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPlayerByIdOrUsername = `-- name: LookupPlayerByIdOrUsername :one
select id
from public.player_data
where id = $1
   or lower(username) = lower($2)
`

func (q *Queries) LookupPlayerByIdOrUsername(ctx context.Context, iD string, lower string) (string, error) {
	row := q.db.QueryRow(ctx, lookupPlayerByIdOrUsername, iD, lower)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lookupPlayerByUsername = `-- name: LookupPlayerByUsername :one
select id
from public.player_data
where lower(username) = lower($1)
`

func (q *Queries) LookupPlayerByUsername(ctx context.Context, lower string) (string, error) {
	row := q.db.QueryRow(ctx, lookupPlayerByUsername, lower)
	var id string
	err := row.Scan(&id)
	return id, err
}

const playerExistsById = `-- name: PlayerExistsById :one
select exists (select 1
               from public.player_data
               where id = $1)
`

func (q *Queries) PlayerExistsById(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, playerExistsById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const searchPlayersFuzzy = `-- name: SearchPlayersFuzzy :many
select id, username, first_join, last_online, playtime, experience, beta_enabled, settings, coins, cubits, skin, online, hypercube_start, hypercube_end, role, extra_map_slots, max_map_size, map_builders
from player_data
where id != all ($1::uuid[])
  and (
    lower(username) % lower($2)
    or lower(username) ilike '%' || lower($2) || '%'
  )
order by similarity(lower(username), lower($2)) desc
limit $3
`

func (q *Queries) SearchPlayersFuzzy(ctx context.Context, excludeIds []string, search string, limit int32) ([]PlayerData, error) {
	rows, err := q.db.Query(ctx, searchPlayersFuzzy, excludeIds, search, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerData{}
	for rows.Next() {
		var i PlayerData
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstJoin,
			&i.LastOnline,
			&i.Playtime,
			&i.Experience,
			&i.BetaEnabled,
			&i.Settings,
			&i.Coins,
			&i.Cubits,
			&i.Skin,
			&i.Online,
			&i.HypercubeStart,
			&i.HypercubeEnd,
			&i.Role,
			&i.ExtraMapSlots,
			&i.MaxMapSize,
			&i.MapBuilders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlayerUnlocks = `-- name: SetPlayerUnlocks :exec
update player_data
set extra_map_slots = greatest(extra_map_slots + $2, $3),
    max_map_size    = greatest(max_map_size, $4),
    map_builders    = greatest(map_builders, $5)
where id = $1
`

type SetPlayerUnlocksParams struct {
	ID          string `json:"id"`
	AddSlots    int16  `json:"addSlots"`
	SetSlots    int16  `json:"setSlots"`
	SetSize     int16  `json:"setSize"`
	SetBuilders int16  `json:"setBuilders"`
}

func (q *Queries) SetPlayerUnlocks(ctx context.Context, arg SetPlayerUnlocksParams) error {
	_, err := q.db.Exec(ctx, setPlayerUnlocks,
		arg.ID,
		arg.AddSlots,
		arg.SetSlots,
		arg.SetSize,
		arg.SetBuilders,
	)
	return err
}

const updatePlayerData = `-- name: UpdatePlayerData :exec
update public.player_data
set username     = coalesce($2, username),
    last_online  = coalesce($3, last_online),
    online       = coalesce($4, online),
    playtime     = coalesce($5, playtime),
    beta_enabled = coalesce($6, beta_enabled),
    settings     = coalesce($7, settings),
    skin         = $8
where id = $1
`

type UpdatePlayerDataParams struct {
	ID          string         `json:"id"`
	Username    *string        `json:"username"`
	LastOnline  *time.Time     `json:"lastOnline"`
	Online      *bool          `json:"online"`
	Playtime    *int           `json:"playtime"`
	BetaEnabled *bool          `json:"betaEnabled"`
	Settings    PlayerSettings `json:"settings"`
	Skin        *PlayerSkin    `json:"skin"`
}

func (q *Queries) UpdatePlayerData(ctx context.Context, arg UpdatePlayerDataParams) error {
	_, err := q.db.Exec(ctx, updatePlayerData,
		arg.ID,
		arg.Username,
		arg.LastOnline,
		arg.Online,
		arg.Playtime,
		arg.BetaEnabled,
		arg.Settings,
		arg.Skin,
	)
	return err
}

const addExperience = `-- name: addExperience :one
update public.player_data
set experience = experience + $2
where id = $1
  and experience + $2 >= 0
returning experience as exp
`

func (q *Queries) addExperience(ctx context.Context, iD string, experience int) (int, error) {
	row := q.db.QueryRow(ctx, addExperience, iD, experience)
	var exp int
	err := row.Scan(&exp)
	return exp, err
}
