// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: leaderboards.sql

package mapdb

import (
	"context"
)

const getMapsBeatenLeaderboard = `-- name: GetMapsBeatenLeaderboard :many
select s1.player_id,
       count(distinct s1.map_id) as unique_maps_beaten
from save_states as s1
         join maps on s1.map_id = maps.id
where s1.deleted is null
  and s1.completed = true
  and (s1.type = 'playing' or s1.type = 'verifying')
  and maps.published_at is not null
group by s1.player_id
order by unique_maps_beaten desc
limit 10
`

type GetMapsBeatenLeaderboardRow struct {
	PlayerID         string `json:"playerId"`
	UniqueMapsBeaten int64  `json:"uniqueMapsBeaten"`
}

func (q *Queries) GetMapsBeatenLeaderboard(ctx context.Context) ([]GetMapsBeatenLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getMapsBeatenLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMapsBeatenLeaderboardRow{}
	for rows.Next() {
		var i GetMapsBeatenLeaderboardRow
		if err := rows.Scan(&i.PlayerID, &i.UniqueMapsBeaten); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMapsBeatenLeaderboardForPlayer = `-- name: GetMapsBeatenLeaderboardForPlayer :one
select count(distinct map_id) as unique_maps_beaten
from save_states
         join maps on save_states.map_id = maps.id
where deleted is null
  and completed = true
  and (type = 'playing' or type = 'verifying')
  and player_id = $1
  and maps.published_at is not null
`

func (q *Queries) GetMapsBeatenLeaderboardForPlayer(ctx context.Context, playerID string) (int64, error) {
	row := q.db.QueryRow(ctx, getMapsBeatenLeaderboardForPlayer, playerID)
	var unique_maps_beaten int64
	err := row.Scan(&unique_maps_beaten)
	return unique_maps_beaten, err
}

const getPlayerBestTimes = `-- name: GetPlayerBestTimes :many
select distinct on (save_states.map_id) save_states.map_id,
                                        save_states.playtime,
                                        maps.opt_name as map_name,
                                        maps.published_id
from save_states
         join maps on save_states.map_id = maps.id
where save_states.deleted is null
  and save_states.completed = true
  and save_states.player_id = $1
  and (save_states.type = 'playing' or save_states.type = 'verifying')
  and save_states.playtime != 0
  and maps.published_at is not null
  and maps.deleted_at is null
order by save_states.map_id, save_states.playtime asc
`

type GetPlayerBestTimesRow struct {
	MapID       string  `json:"mapId"`
	Playtime    int     `json:"playtime"`
	MapName     *string `json:"mapName"`
	PublishedID *int    `json:"publishedId"`
}

// Returns the player's best time per completed map
func (q *Queries) GetPlayerBestTimes(ctx context.Context, playerID string) ([]GetPlayerBestTimesRow, error) {
	rows, err := q.db.Query(ctx, getPlayerBestTimes, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerBestTimesRow{}
	for rows.Next() {
		var i GetPlayerBestTimesRow
		if err := rows.Scan(
			&i.MapID,
			&i.Playtime,
			&i.MapName,
			&i.PublishedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopTimesLeaderboard = `-- name: GetTopTimesLeaderboard :many
select s1.player_id,
       count(distinct s1.map_id) as top_times
from (select map_id, (round(min(playtime) / 50.0) * 50)::bigint as min_playtime
      from save_states
               join maps on save_states.map_id = maps.id
      where deleted is null
        and completed = true
        and playtime != 0
        and (type = 'playing' or type = 'verifying')
        and maps.published_at is not null
        and maps.deleted_at is null
        and coalesce(maps.leaderboard->>'format', 'time') = 'time'
      group by map_id) as shortest_playtimes
         join save_states as s1
              on s1.map_id = shortest_playtimes.map_id
                  and (round(s1.playtime / 50.0) * 50)::bigint = shortest_playtimes.min_playtime
where s1.deleted is null
  and s1.completed = true
group by s1.player_id
order by top_times desc
limit 10
`

type GetTopTimesLeaderboardRow struct {
	PlayerID string `json:"playerId"`
	TopTimes int64  `json:"topTimes"`
}

func (q *Queries) GetTopTimesLeaderboard(ctx context.Context) ([]GetTopTimesLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getTopTimesLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopTimesLeaderboardRow{}
	for rows.Next() {
		var i GetTopTimesLeaderboardRow
		if err := rows.Scan(&i.PlayerID, &i.TopTimes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopTimesLeaderboardForPlayer = `-- name: GetTopTimesLeaderboardForPlayer :one
select count(distinct s1.map_id) as top_times
from (select map_id, (round(min(playtime) / 50.0) * 50)::bigint as min_playtime
      from save_states
               join maps on save_states.map_id = maps.id
      where deleted is null
        and completed = true
        and playtime != 0
        and (type = 'playing' or type = 'verifying')
        and maps.published_at is not null
        and maps.deleted_at is null
      group by map_id) as shortest_playtimes
         join save_states as s1
              on s1.map_id = shortest_playtimes.map_id
                  and (round(s1.playtime / 50.0) * 50)::bigint = shortest_playtimes.min_playtime
                  and s1.player_id = $1
where s1.deleted is null
  and s1.completed = true
`

func (q *Queries) GetTopTimesLeaderboardForPlayer(ctx context.Context, playerID string) (int64, error) {
	row := q.db.QueryRow(ctx, getTopTimesLeaderboardForPlayer, playerID)
	var top_times int64
	err := row.Scan(&top_times)
	return top_times, err
}
