// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: map_files.sql

package mapdb

import (
	"context"
)

const deleteMapFile = `-- name: DeleteMapFile :one
delete
from map_files
where map_id = $1
  and path = $2
returning path as deleted_path
`

func (q *Queries) DeleteMapFile(ctx context.Context, mapID string, path string) (string, error) {
	row := q.db.QueryRow(ctx, deleteMapFile, mapID, path)
	var deleted_path string
	err := row.Scan(&deleted_path)
	return deleted_path, err
}

const getMapFile = `-- name: GetMapFile :one
select path, content, content_type, content_hash, size
from map_files
where map_id = $1
  and path = $2
`

type GetMapFileRow struct {
	Path        string `json:"path"`
	Content     []byte `json:"content"`
	ContentType string `json:"contentType"`
	ContentHash []byte `json:"contentHash"`
	Size        int    `json:"size"`
}

func (q *Queries) GetMapFile(ctx context.Context, mapID string, path string) (GetMapFileRow, error) {
	row := q.db.QueryRow(ctx, getMapFile, mapID, path)
	var i GetMapFileRow
	err := row.Scan(
		&i.Path,
		&i.Content,
		&i.ContentType,
		&i.ContentHash,
		&i.Size,
	)
	return i, err
}

const getMapFiles = `-- name: GetMapFiles :many
select path,
       content_type,
       content_hash,
       size
from map_files
where map_id = $1
`

type GetMapFilesRow struct {
	Path        string `json:"path"`
	ContentType string `json:"contentType"`
	ContentHash []byte `json:"contentHash"`
	Size        int    `json:"size"`
}

func (q *Queries) GetMapFiles(ctx context.Context, mapID string) ([]GetMapFilesRow, error) {
	rows, err := q.db.Query(ctx, getMapFiles, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMapFilesRow{}
	for rows.Next() {
		var i GetMapFilesRow
		if err := rows.Scan(
			&i.Path,
			&i.ContentType,
			&i.ContentHash,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMapFile = `-- name: UpsertMapFile :one
insert into map_files (map_id, path, content, content_hash, content_type)
values ($1, $2, $3, $4, $5)
on conflict (map_id, path) do update
  set content      = excluded.content,
      content_hash = excluded.content_hash,
      content_type = excluded.content_type,
      updated_at   = now()
returning path, content_type, content_hash, size
`

type UpsertMapFileParams struct {
	MapID       string `json:"mapId"`
	Path        string `json:"path"`
	Content     []byte `json:"content"`
	ContentHash []byte `json:"contentHash"`
	ContentType string `json:"contentType"`
}

type UpsertMapFileRow struct {
	Path        string `json:"path"`
	ContentType string `json:"contentType"`
	ContentHash []byte `json:"contentHash"`
	Size        int    `json:"size"`
}

func (q *Queries) UpsertMapFile(ctx context.Context, arg UpsertMapFileParams) (UpsertMapFileRow, error) {
	row := q.db.QueryRow(ctx, upsertMapFile,
		arg.MapID,
		arg.Path,
		arg.Content,
		arg.ContentHash,
		arg.ContentType,
	)
	var i UpsertMapFileRow
	err := row.Scan(
		&i.Path,
		&i.ContentType,
		&i.ContentHash,
		&i.Size,
	)
	return i, err
}
