// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: map_files.sql

package mapdb

import (
	"context"
)

const deleteProjectFile = `-- name: DeleteProjectFile :one
delete
from map_files
where map_id = $1
  and path = $2
returning path as deleted_path
`

func (q *Queries) DeleteProjectFile(ctx context.Context, mapID string, path string) (string, error) {
	row := q.db.QueryRow(ctx, deleteProjectFile, mapID, path)
	var deleted_path string
	err := row.Scan(&deleted_path)
	return deleted_path, err
}

const getProjectFile = `-- name: GetProjectFile :one
select path, content, content_type, size
from map_files
where map_id = $1
  and path = $2
`

type GetProjectFileRow struct {
	Path        string `json:"path"`
	Content     []byte `json:"content"`
	ContentType string `json:"contentType"`
	Size        int    `json:"size"`
}

func (q *Queries) GetProjectFile(ctx context.Context, mapID string, path string) (GetProjectFileRow, error) {
	row := q.db.QueryRow(ctx, getProjectFile, mapID, path)
	var i GetProjectFileRow
	err := row.Scan(
		&i.Path,
		&i.Content,
		&i.ContentType,
		&i.Size,
	)
	return i, err
}

const getProjectFiles = `-- name: GetProjectFiles :many
select path,
       content_type,
       content_hash,
       size
from map_files
where map_id = $1
`

type GetProjectFilesRow struct {
	Path        string `json:"path"`
	ContentType string `json:"contentType"`
	ContentHash []byte `json:"contentHash"`
	Size        int    `json:"size"`
}

func (q *Queries) GetProjectFiles(ctx context.Context, mapID string) ([]GetProjectFilesRow, error) {
	rows, err := q.db.Query(ctx, getProjectFiles, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectFilesRow{}
	for rows.Next() {
		var i GetProjectFilesRow
		if err := rows.Scan(
			&i.Path,
			&i.ContentType,
			&i.ContentHash,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectFile = `-- name: UpsertProjectFile :one
insert into map_files (map_id, path, content, content_hash, content_type)
values ($1, $2, $3, $4, $5)
on conflict (map_id, path) do update
  set content      = excluded.content,
      content_hash = excluded.content_hash,
      content_type = excluded.content_type,
      updated_at   = now()
returning path, content_type, content_hash, size
`

type UpsertProjectFileParams struct {
	MapID       string `json:"mapId"`
	Path        string `json:"path"`
	Content     []byte `json:"content"`
	ContentHash []byte `json:"contentHash"`
	ContentType string `json:"contentType"`
}

type UpsertProjectFileRow struct {
	Path        string `json:"path"`
	ContentType string `json:"contentType"`
	ContentHash []byte `json:"contentHash"`
	Size        int    `json:"size"`
}

func (q *Queries) UpsertProjectFile(ctx context.Context, arg UpsertProjectFileParams) (UpsertProjectFileRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectFile,
		arg.MapID,
		arg.Path,
		arg.Content,
		arg.ContentHash,
		arg.ContentType,
	)
	var i UpsertProjectFileRow
	err := row.Scan(
		&i.Path,
		&i.ContentType,
		&i.ContentHash,
		&i.Size,
	)
	return i, err
}
