// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: map_building.sql

package mapdb

import (
	"context"
)

const getHeadsWithCategory = `-- name: GetHeadsWithCategory :many
select head_db.id, head_db.category, head_db.name, head_db.tags, head_db.texture,
       count(*) over () as total_count
from head_db
where category = $1::text
limit $2 offset $3
`

type GetHeadsWithCategoryRow struct {
	HeadDb     HeadDb `json:"headDb"`
	TotalCount int64  `json:"totalCount"`
}

func (q *Queries) GetHeadsWithCategory(ctx context.Context, column1 string, limit int32, offset int32) ([]GetHeadsWithCategoryRow, error) {
	rows, err := q.db.Query(ctx, getHeadsWithCategory, column1, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHeadsWithCategoryRow{}
	for rows.Next() {
		var i GetHeadsWithCategoryRow
		if err := rows.Scan(
			&i.HeadDb.ID,
			&i.HeadDb.Category,
			&i.HeadDb.Name,
			&i.HeadDb.Tags,
			&i.HeadDb.Texture,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHeadsWithSearch = `-- name: GetHeadsWithSearch :many
select head_db.id, head_db.category, head_db.name, head_db.tags, head_db.texture,
       count(*) over () as total_count
from head_db
where name ilike $1::text
limit $2 offset $3
`

type GetHeadsWithSearchRow struct {
	HeadDb     HeadDb `json:"headDb"`
	TotalCount int64  `json:"totalCount"`
}

func (q *Queries) GetHeadsWithSearch(ctx context.Context, column1 string, limit int32, offset int32) ([]GetHeadsWithSearchRow, error) {
	rows, err := q.db.Query(ctx, getHeadsWithSearch, column1, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHeadsWithSearchRow{}
	for rows.Next() {
		var i GetHeadsWithSearchRow
		if err := rows.Scan(
			&i.HeadDb.ID,
			&i.HeadDb.Category,
			&i.HeadDb.Name,
			&i.HeadDb.Tags,
			&i.HeadDb.Texture,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomHeads = `-- name: GetRandomHeads :many
select id, category, name, tags, texture
from head_db
order by random()
limit $1
`

func (q *Queries) GetRandomHeads(ctx context.Context, limit int32) ([]HeadDb, error) {
	rows, err := q.db.Query(ctx, getRandomHeads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeadDb{}
	for rows.Next() {
		var i HeadDb
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Name,
			&i.Tags,
			&i.Texture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
