// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: save_states.sql

package mapdb

import (
	"context"
	"time"
)

const countFailSaveStates = `-- name: CountFailSaveStates :one
select count(*)
from save_states
where type = 'playing'
  and completed = false
`

func (q *Queries) CountFailSaveStates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFailSaveStates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSaveState = `-- name: CreateSaveState :one
insert into save_states (id, map_id, player_id, type, created, updated, completed, playtime, data_version,
                         state_v2, protocol_version)
values (gen_random_uuid(), $1, $2, $3, now(), now(), false, 0, 0, 'null', $4)
returning id, map_id, player_id, type, created, updated, deleted, completed, playtime, state_v2, data_version, protocol_version, ticks, score
`

type CreateSaveStateParams struct {
	MapID           string        `json:"mapId"`
	PlayerID        string        `json:"playerId"`
	Type            SaveStateType `json:"type"`
	ProtocolVersion *int          `json:"protocolVersion"`
}

func (q *Queries) CreateSaveState(ctx context.Context, arg CreateSaveStateParams) (SaveState, error) {
	row := q.db.QueryRow(ctx, createSaveState,
		arg.MapID,
		arg.PlayerID,
		arg.Type,
		arg.ProtocolVersion,
	)
	var i SaveState
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.PlayerID,
		&i.Type,
		&i.Created,
		&i.Updated,
		&i.Deleted,
		&i.Completed,
		&i.Playtime,
		&i.StateV2,
		&i.DataVersion,
		&i.ProtocolVersion,
		&i.Ticks,
		&i.Score,
	)
	return i, err
}

const deleteMapPlayerSaveStates = `-- name: DeleteMapPlayerSaveStates :exec
update public.save_states
set deleted = now()
where deleted is null
  and map_id = $1
  and player_id = $2
`

func (q *Queries) DeleteMapPlayerSaveStates(ctx context.Context, mapID string, playerID string) error {
	_, err := q.db.Exec(ctx, deleteMapPlayerSaveStates, mapID, playerID)
	return err
}

const deleteSaveState = `-- name: DeleteSaveState :execrows
delete
from save_states
where id = $1
  and map_id = $2
  and player_id = $3
`

func (q *Queries) DeleteSaveState(ctx context.Context, iD string, mapID string, playerID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSaveState, iD, mapID, playerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteVerifyingStates = `-- name: DeleteVerifyingStates :exec
update save_states
set deleted = now()
where map_id = $1
  and type = 'verifying'
  and deleted is null
`

func (q *Queries) DeleteVerifyingStates(ctx context.Context, mapID string) error {
	_, err := q.db.Exec(ctx, deleteVerifyingStates, mapID)
	return err
}

const getAllBestCompletedSaveStatesForMap = `-- name: GetAllBestCompletedSaveStatesForMap :many
select distinct on (player_id) ss.id, ss.map_id, ss.player_id, ss.type, ss.created, ss.updated, ss.deleted, ss.completed, ss.playtime, ss.state_v2, ss.data_version, ss.protocol_version, ss.ticks, ss.score
from save_states ss
         join maps m on m.id = ss.map_id
where ss.deleted is null
  and ss.map_id = $1
  and (ss.type = 'playing' or ss.type = 'verifying')
  and ss.completed = true
order by player_id, case
    when m.leaderboard is not null and (m.leaderboard ->> 'asc')::boolean = false
        then -coalesce(ss.score, greatest(ss.playtime, ss.ticks * 50))
    else coalesce(ss.score, greatest(ss.playtime, ss.ticks * 50))
end
`

func (q *Queries) GetAllBestCompletedSaveStatesForMap(ctx context.Context, mapID string) ([]SaveState, error) {
	rows, err := q.db.Query(ctx, getAllBestCompletedSaveStatesForMap, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SaveState{}
	for rows.Next() {
		var i SaveState
		if err := rows.Scan(
			&i.ID,
			&i.MapID,
			&i.PlayerID,
			&i.Type,
			&i.Created,
			&i.Updated,
			&i.Deleted,
			&i.Completed,
			&i.Playtime,
			&i.StateV2,
			&i.DataVersion,
			&i.ProtocolVersion,
			&i.Ticks,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBestSaveState = `-- name: GetBestSaveState :one
select ss.id, ss.map_id, ss.player_id, ss.type, ss.created, ss.updated, ss.deleted, ss.completed, ss.playtime, ss.state_v2, ss.data_version, ss.protocol_version, ss.ticks, ss.score
from save_states ss
  join maps m on m.id = ss.map_id
where ss.deleted is null
  and ss.map_id = $1
  and ss.player_id = $2
  and (ss.type = 'playing' or ss.type = 'verifying')
  and ss.completed = true
order by case
           when m.leaderboard is not null
             and (m.leaderboard ->> 'asc')::boolean = false
             then -coalesce(ss.score, greatest(ss.playtime, ss.ticks * 50))
           else coalesce(ss.score, greatest(ss.playtime, ss.ticks * 50))
           end
limit 1
`

func (q *Queries) GetBestSaveState(ctx context.Context, mapID string, playerID string) (SaveState, error) {
	row := q.db.QueryRow(ctx, getBestSaveState, mapID, playerID)
	var i SaveState
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.PlayerID,
		&i.Type,
		&i.Created,
		&i.Updated,
		&i.Deleted,
		&i.Completed,
		&i.Playtime,
		&i.StateV2,
		&i.DataVersion,
		&i.ProtocolVersion,
		&i.Ticks,
		&i.Score,
	)
	return i, err
}

const getBestSaveStateSinceBeta = `-- name: GetBestSaveStateSinceBeta :one
select id, map_id, player_id, type, created, updated, deleted, completed, playtime, state_v2, data_version, protocol_version, ticks, score
from save_states
where deleted is null
  and map_id = $1
  and player_id = $2
  and type = 'playing'
  and completed = true
  and created > '2024-04-05T09:00:00-04:00'::timestamptz
order by coalesce(score, greatest(playtime, ticks * 50))
limit 1
`

func (q *Queries) GetBestSaveStateSinceBeta(ctx context.Context, mapID string, playerID string) (SaveState, error) {
	row := q.db.QueryRow(ctx, getBestSaveStateSinceBeta, mapID, playerID)
	var i SaveState
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.PlayerID,
		&i.Type,
		&i.Created,
		&i.Updated,
		&i.Deleted,
		&i.Completed,
		&i.Playtime,
		&i.StateV2,
		&i.DataVersion,
		&i.ProtocolVersion,
		&i.Ticks,
		&i.Score,
	)
	return i, err
}

const getCompletedMaps = `-- name: GetCompletedMaps :many
select distinct map_id
from save_states
where deleted is null
  and completed = true
  and player_id = $1
`

func (q *Queries) GetCompletedMaps(ctx context.Context, playerID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getCompletedMaps, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var map_id string
		if err := rows.Scan(&map_id); err != nil {
			return nil, err
		}
		items = append(items, map_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestSaveState = `-- name: GetLatestSaveState :one
select id, map_id, player_id, type, created, updated, deleted, completed, playtime, state_v2, data_version, protocol_version, ticks, score
from save_states
where deleted is null
  and map_id = $1
  and player_id = $2
  and type = $3
order by updated desc
limit 1
`

func (q *Queries) GetLatestSaveState(ctx context.Context, mapID string, playerID string, type_ SaveStateType) (SaveState, error) {
	row := q.db.QueryRow(ctx, getLatestSaveState, mapID, playerID, type_)
	var i SaveState
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.PlayerID,
		&i.Type,
		&i.Created,
		&i.Updated,
		&i.Deleted,
		&i.Completed,
		&i.Playtime,
		&i.StateV2,
		&i.DataVersion,
		&i.ProtocolVersion,
		&i.Ticks,
		&i.Score,
	)
	return i, err
}

const getRecentMaps = `-- name: GetRecentMaps :many
select map_id
from save_states
where player_id = $1
  and type = $2
  and deleted is null
group by map_id
order by max(updated) desc
offset $3::int * $4::int limit $4::int + 1
`

type GetRecentMapsParams struct {
	PlayerID string        `json:"playerId"`
	Type     SaveStateType `json:"type"`
	Page     int           `json:"page"`
	PageSize int           `json:"pageSize"`
}

func (q *Queries) GetRecentMaps(ctx context.Context, arg GetRecentMapsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getRecentMaps,
		arg.PlayerID,
		arg.Type,
		arg.Page,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var map_id string
		if err := rows.Scan(&map_id); err != nil {
			return nil, err
		}
		items = append(items, map_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSaveState = `-- name: GetSaveState :one
select id, map_id, player_id, type, created, updated, deleted, completed, playtime, state_v2, data_version, protocol_version, ticks, score
from public.save_states
where deleted is null
  and id = $1
  and map_id = $2
  and player_id = $3
`

func (q *Queries) GetSaveState(ctx context.Context, iD string, mapID string, playerID string) (SaveState, error) {
	row := q.db.QueryRow(ctx, getSaveState, iD, mapID, playerID)
	var i SaveState
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.PlayerID,
		&i.Type,
		&i.Created,
		&i.Updated,
		&i.Deleted,
		&i.Completed,
		&i.Playtime,
		&i.StateV2,
		&i.DataVersion,
		&i.ProtocolVersion,
		&i.Ticks,
		&i.Score,
	)
	return i, err
}

const unsafe_DeleteMapSaveStates = `-- name: Unsafe_DeleteMapSaveStates :exec
update save_states
set deleted = now()
where map_id = $1
  and deleted is null
`

func (q *Queries) Unsafe_DeleteMapSaveStates(ctx context.Context, mapID string) error {
	_, err := q.db.Exec(ctx, unsafe_DeleteMapSaveStates, mapID)
	return err
}

const upsertSaveState = `-- name: UpsertSaveState :exec
insert into public.save_states
(id, map_id, player_id, type, created, updated, completed, playtime, ticks, score, state_v2, data_version,
 protocol_version)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
on conflict (id, map_id, player_id) do update
  set updated          = excluded.updated,
      completed        = excluded.completed,
      playtime         = excluded.playtime,
      ticks            = excluded.ticks,
      score            = excluded.score,
      state_v2         = excluded.state_v2,
      data_version     = excluded.data_version,
      protocol_version = excluded.protocol_version
`

type UpsertSaveStateParams struct {
	ID              string        `json:"id"`
	MapID           string        `json:"mapId"`
	PlayerID        string        `json:"playerId"`
	Type            SaveStateType `json:"type"`
	Created         time.Time     `json:"created"`
	Updated         time.Time     `json:"updated"`
	Completed       bool          `json:"completed"`
	Playtime        int           `json:"playtime"`
	Ticks           int           `json:"ticks"`
	Score           *float64      `json:"score"`
	StateV2         []byte        `json:"stateV2"`
	DataVersion     int           `json:"dataVersion"`
	ProtocolVersion *int          `json:"protocolVersion"`
}

func (q *Queries) UpsertSaveState(ctx context.Context, arg UpsertSaveStateParams) error {
	_, err := q.db.Exec(ctx, upsertSaveState,
		arg.ID,
		arg.MapID,
		arg.PlayerID,
		arg.Type,
		arg.Created,
		arg.Updated,
		arg.Completed,
		arg.Playtime,
		arg.Ticks,
		arg.Score,
		arg.StateV2,
		arg.DataVersion,
		arg.ProtocolVersion,
	)
	return err
}
