// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"
)

const deleteAllApiKeys = `-- name: DeleteAllApiKeys :exec
update api_keys
set deleted_at = now()
where deleted_at is null and player_id = $1
`

func (q *Queries) DeleteAllApiKeys(ctx context.Context, playerID string) error {
	_, err := q.db.Exec(ctx, deleteAllApiKeys, playerID)
	return err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
select id, key_hash, player_id, created_at, deleted_at from api_keys where deleted_at is null and key_hash = $1 limit 1
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.PlayerID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertApiKey = `-- name: InsertApiKey :exec
insert into api_keys (key_hash, player_id)
values ($1, $2)
`

func (q *Queries) InsertApiKey(ctx context.Context, keyHash string, playerID string) error {
	_, err := q.db.Exec(ctx, insertApiKey, keyHash, playerID)
	return err
}
