// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blocks.sql

package db

import (
	"context"
	"time"
)

const countBlockedPlayers = `-- name: CountBlockedPlayers :one
select count(*)
from player_blocks
where player_id = $1
`

func (q *Queries) CountBlockedPlayers(ctx context.Context, playerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countBlockedPlayers, playerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlayerBlock = `-- name: CreatePlayerBlock :exec
insert into player_blocks (player_id, target_id)
values ($1, $2)
`

func (q *Queries) CreatePlayerBlock(ctx context.Context, playerID string, targetID string) error {
	_, err := q.db.Exec(ctx, createPlayerBlock, playerID, targetID)
	return err
}

const deletePlayerBlock = `-- name: DeletePlayerBlock :execrows
delete
from player_blocks
where player_id = $1
  and target_id = $2
`

func (q *Queries) DeletePlayerBlock(ctx context.Context, playerID string, targetID string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlayerBlock, playerID, targetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBlockedPlayers = `-- name: GetBlockedPlayers :many
select pb.target_id, pd.username, pb.created_at
from player_blocks pb
         join player_data pd on pd.id = pb.target_id
where pb.player_id = $1
limit $2 offset $3
`

type GetBlockedPlayersRow struct {
	TargetID  string    `json:"targetId"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) GetBlockedPlayers(ctx context.Context, playerID string, limit int32, offset int32) ([]GetBlockedPlayersRow, error) {
	rows, err := q.db.Query(ctx, getBlockedPlayers, playerID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlockedPlayersRow{}
	for rows.Next() {
		var i GetBlockedPlayersRow
		if err := rows.Scan(&i.TargetID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlocksBetween = `-- name: GetBlocksBetween :many
select pb.player_id, pb.target_id, pd.username, pb.created_at
from player_blocks pb
         join player_data pd on pd.id = pb.target_id
where (player_id = $1 and target_id = $2)
   or ($3 and player_id = $2 and target_id = $1)
`

type GetBlocksBetweenRow struct {
	PlayerID  string    `json:"playerId"`
	TargetID  string    `json:"targetId"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) GetBlocksBetween(ctx context.Context, playerID string, targetID string, column3 interface{}) ([]GetBlocksBetweenRow, error) {
	rows, err := q.db.Query(ctx, getBlocksBetween, playerID, targetID, column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlocksBetweenRow{}
	for rows.Next() {
		var i GetBlocksBetweenRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.TargetID,
			&i.Username,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isBlocked = `-- name: IsBlocked :one
select exists (select 1
               from player_blocks
               where player_id = $1
                 and target_id = $2)
`

func (q *Queries) IsBlocked(ctx context.Context, playerID string, targetID string) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, playerID, targetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
