// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blocks.sql

package db

import (
	"context"
	"time"
)

const createPlayerBlock = `-- name: CreatePlayerBlock :exec
insert into player_blocks (player_id, target_id)
values ($1, $2)
`

func (q *Queries) CreatePlayerBlock(ctx context.Context, playerID string, targetID string) error {
	_, err := q.db.Exec(ctx, createPlayerBlock, playerID, targetID)
	return err
}

const deletePlayerBlock = `-- name: DeletePlayerBlock :execrows
delete
from player_blocks
where player_id = $1
  and target_id = $2
`

func (q *Queries) DeletePlayerBlock(ctx context.Context, playerID string, targetID string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlayerBlock, playerID, targetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBlockedPlayers = `-- name: GetBlockedPlayers :many
select pb.target_id, pd.username, pb.created_at
from player_blocks pb
         join player_data pd on pd.id = pb.target_id
where pb.player_id = $1
`

type GetBlockedPlayersRow struct {
	TargetID  string    `json:"targetId"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) GetBlockedPlayers(ctx context.Context, playerID string) ([]GetBlockedPlayersRow, error) {
	rows, err := q.db.Query(ctx, getBlockedPlayers, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlockedPlayersRow{}
	for rows.Next() {
		var i GetBlockedPlayersRow
		if err := rows.Scan(&i.TargetID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isBlocked = `-- name: IsBlocked :one
select exists (select 1
               from player_blocks
               where player_id = $1
                 and target_id = $2)
`

func (q *Queries) IsBlocked(ctx context.Context, playerID string, targetID string) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, playerID, targetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
