// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: currency.sql

package db

import (
	"context"
)

const getUnlockedCosmetics = `-- name: GetUnlockedCosmetics :many
select cosmetic_path
from player_cosmetics
where player_id = $1
`

func (q *Queries) GetUnlockedCosmetics(ctx context.Context, playerID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUnlockedCosmetics, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var cosmetic_path string
		if err := rows.Scan(&cosmetic_path); err != nil {
			return nil, err
		}
		items = append(items, cosmetic_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlockCosmetic = `-- name: UnlockCosmetic :exec
insert into player_cosmetics (player_id, cosmetic_path, unlocked_at)
values ($1, $2, now())
`

func (q *Queries) UnlockCosmetic(ctx context.Context, playerID string, cosmeticPath string) error {
	_, err := q.db.Exec(ctx, unlockCosmetic, playerID, cosmeticPath)
	return err
}

const unsafe_AddCoins = `-- name: Unsafe_AddCoins :many
update player_data
set coins = coins + $1
where id = $2
  and coins + $1 >= 0
returning coins
`

func (q *Queries) Unsafe_AddCoins(ctx context.Context, delta int, iD string) ([]int, error) {
	rows, err := q.db.Query(ctx, unsafe_AddCoins, delta, iD)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int
	for rows.Next() {
		var coins int
		if err := rows.Scan(&coins); err != nil {
			return nil, err
		}
		items = append(items, coins)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsafe_AddCubits = `-- name: Unsafe_AddCubits :many
update player_data
set cubits = cubits + $1
where id = $2
  and cubits + $1 >= 0
returning cubits
`

func (q *Queries) Unsafe_AddCubits(ctx context.Context, delta int, iD string) ([]int, error) {
	rows, err := q.db.Query(ctx, unsafe_AddCubits, delta, iD)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int
	for rows.Next() {
		var cubits int
		if err := rows.Scan(&cubits); err != nil {
			return nil, err
		}
		items = append(items, cubits)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsafe_AppendTxLog = `-- name: Unsafe_AppendTxLog :exec
insert into tx_log (player_id, timestamp, reason, currency, amount, meta)
values ($1, now(), $2, $3, $4, $5)
`

type Unsafe_AppendTxLogParams struct {
	PlayerID string      `json:"playerId"`
	Reason   string      `json:"reason"`
	Currency string      `json:"currency"`
	Amount   int         `json:"amount"`
	Meta     interface{} `json:"meta"`
}

func (q *Queries) Unsafe_AppendTxLog(ctx context.Context, arg Unsafe_AppendTxLogParams) error {
	_, err := q.db.Exec(ctx, unsafe_AppendTxLog,
		arg.PlayerID,
		arg.Reason,
		arg.Currency,
		arg.Amount,
		arg.Meta,
	)
	return err
}
