// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: friends.sql

package db

import (
	"context"
	"time"
)

const createFriendRequest = `-- name: CreateFriendRequest :exec
insert into player_friend_requests (player_id, target_id)
values ($1, $2)
`

func (q *Queries) CreateFriendRequest(ctx context.Context, playerID string, targetID string) error {
	_, err := q.db.Exec(ctx, createFriendRequest, playerID, targetID)
	return err
}

const createPlayerFriend = `-- name: CreatePlayerFriend :exec
insert into player_friends (player_id, target_id)
values ($1, $2)
`

func (q *Queries) CreatePlayerFriend(ctx context.Context, playerID string, targetID string) error {
	_, err := q.db.Exec(ctx, createPlayerFriend, playerID, targetID)
	return err
}

const deleteFriendRequest = `-- name: DeleteFriendRequest :execrows
delete
from player_friend_requests
where player_id = $1
  and target_id = $2
`

func (q *Queries) DeleteFriendRequest(ctx context.Context, playerID string, targetID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFriendRequest, playerID, targetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFriendRequestBidirectional = `-- name: DeleteFriendRequestBidirectional :execrows
delete
from player_friend_requests
where (player_id = $1 and target_id = $2)
   or (player_id = $2 and target_id = $1)
`

func (q *Queries) DeleteFriendRequestBidirectional(ctx context.Context, playerID string, targetID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFriendRequestBidirectional, playerID, targetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePlayerFriend = `-- name: DeletePlayerFriend :execrows
delete
from player_friends
where player_id = $1
  and target_id = $2
`

func (q *Queries) DeletePlayerFriend(ctx context.Context, playerID string, targetID string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlayerFriend, playerID, targetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePlayerFriendBidirectional = `-- name: DeletePlayerFriendBidirectional :execrows
delete
from player_friends
where (player_id = $1 and target_id = $2)
   or (player_id = $2 and target_id = $1)
`

func (q *Queries) DeletePlayerFriendBidirectional(ctx context.Context, playerID string, targetID string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlayerFriendBidirectional, playerID, targetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const friendRequestExists = `-- name: FriendRequestExists :one
select exists (select 1
               from player_friend_requests
               where player_id = $1
                 and target_id = $2)
`

func (q *Queries) FriendRequestExists(ctx context.Context, playerID string, targetID string) (bool, error) {
	row := q.db.QueryRow(ctx, friendRequestExists, playerID, targetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const friendshipExists = `-- name: FriendshipExists :one
select exists (select 1
               from player_friends
               where player_id = $1
                 and target_id = $2)
`

func (q *Queries) FriendshipExists(ctx context.Context, playerID string, targetID string) (bool, error) {
	row := q.db.QueryRow(ctx, friendshipExists, playerID, targetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getIncomingFriendRequests = `-- name: GetIncomingFriendRequests :many

select pfr.player_id, pd.username, pfr.created_at
from player_friend_requests pfr
         join player_data pd on pd.id = pfr.player_id
where pfr.target_id = $1
`

type GetIncomingFriendRequestsRow struct {
	PlayerID  string    `json:"playerId"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
}

// Friend Requests
func (q *Queries) GetIncomingFriendRequests(ctx context.Context, targetID string) ([]*GetIncomingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, getIncomingFriendRequests, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetIncomingFriendRequestsRow{}
	for rows.Next() {
		var i GetIncomingFriendRequestsRow
		if err := rows.Scan(&i.PlayerID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutgoingFriendRequests = `-- name: GetOutgoingFriendRequests :many
select pfr.target_id, pd.username, pfr.created_at
from player_friend_requests pfr
         join player_data pd on pd.id = pfr.target_id
where pfr.player_id = $1
`

type GetOutgoingFriendRequestsRow struct {
	TargetID  string    `json:"targetId"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) GetOutgoingFriendRequests(ctx context.Context, playerID string) ([]*GetOutgoingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, getOutgoingFriendRequests, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetOutgoingFriendRequestsRow{}
	for rows.Next() {
		var i GetOutgoingFriendRequestsRow
		if err := rows.Scan(&i.TargetID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerFriends = `-- name: GetPlayerFriends :many

select pf.target_id, pd.username, pf.created_at
from player_friends pf
         join player_data pd on pd.id = pf.target_id
where pf.player_id = $1
`

type GetPlayerFriendsRow struct {
	TargetID  string    `json:"targetId"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
}

// Friends
func (q *Queries) GetPlayerFriends(ctx context.Context, playerID string) ([]*GetPlayerFriendsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerFriends, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetPlayerFriendsRow{}
	for rows.Next() {
		var i GetPlayerFriendsRow
		if err := rows.Scan(&i.TargetID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
