// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friends.sql

package db

import (
	"context"
	"time"
)

const countFriendRequests = `-- name: CountFriendRequests :one

select count(*) as total
from player_friend_requests
where (player_id = $1 or $1 is null)
  and (target_id = $2 or $2 is null)
`

// Friend Requests
func (q *Queries) CountFriendRequests(ctx context.Context, playerID *string, targetID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countFriendRequests, playerID, targetID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPlayerFriends = `-- name: CountPlayerFriends :one

select count(*) as total
from player_friends
where player_id = $1
`

// Friends
func (q *Queries) CountPlayerFriends(ctx context.Context, playerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayerFriends, playerID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createFriendRequest = `-- name: CreateFriendRequest :exec
insert into player_friend_requests (player_id, target_id)
values ($1, $2)
`

func (q *Queries) CreateFriendRequest(ctx context.Context, playerID string, targetID string) error {
	_, err := q.db.Exec(ctx, createFriendRequest, playerID, targetID)
	return err
}

const createPlayerFriend = `-- name: CreatePlayerFriend :exec
insert into player_friends (player_id, target_id)
values ($1, $2)
`

func (q *Queries) CreatePlayerFriend(ctx context.Context, playerID string, targetID string) error {
	_, err := q.db.Exec(ctx, createPlayerFriend, playerID, targetID)
	return err
}

const deleteFriendRequest = `-- name: DeleteFriendRequest :one
WITH deleted AS (
    DELETE FROM player_friend_requests
        WHERE player_id = $1
            AND target_id = $2
        RETURNING player_id, target_id, created_at)
SELECT d.player_id, d.target_id, d.created_at, pd.username
FROM deleted d
         JOIN player_data pd ON pd.id = d.player_id
`

type DeleteFriendRequestRow struct {
	PlayerID  string    `json:"playerId"`
	TargetID  string    `json:"targetId"`
	CreatedAt time.Time `json:"createdAt"`
	Username  string    `json:"username"`
}

func (q *Queries) DeleteFriendRequest(ctx context.Context, playerID string, targetID string) (DeleteFriendRequestRow, error) {
	row := q.db.QueryRow(ctx, deleteFriendRequest, playerID, targetID)
	var i DeleteFriendRequestRow
	err := row.Scan(
		&i.PlayerID,
		&i.TargetID,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}

const deleteFriendRequestBidirectional = `-- name: DeleteFriendRequestBidirectional :one
WITH deleted AS (
    DELETE FROM player_friend_requests
        WHERE (player_id = $1 AND target_id = $2)
            OR (player_id = $2 AND target_id = $1)
        RETURNING player_id, target_id, created_at)
SELECT d.player_id, d.target_id, d.created_at, pd.username
FROM deleted d
         JOIN player_data pd ON pd.id = d.player_id
`

type DeleteFriendRequestBidirectionalRow struct {
	PlayerID  string    `json:"playerId"`
	TargetID  string    `json:"targetId"`
	CreatedAt time.Time `json:"createdAt"`
	Username  string    `json:"username"`
}

func (q *Queries) DeleteFriendRequestBidirectional(ctx context.Context, playerID string, targetID string) (DeleteFriendRequestBidirectionalRow, error) {
	row := q.db.QueryRow(ctx, deleteFriendRequestBidirectional, playerID, targetID)
	var i DeleteFriendRequestBidirectionalRow
	err := row.Scan(
		&i.PlayerID,
		&i.TargetID,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}

const deletePlayerFriend = `-- name: DeletePlayerFriend :execrows
delete
from player_friends
where player_id = $1
  and target_id = $2
`

func (q *Queries) DeletePlayerFriend(ctx context.Context, playerID string, targetID string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlayerFriend, playerID, targetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePlayerFriendBidirectional = `-- name: DeletePlayerFriendBidirectional :execrows
delete
from player_friends
where (player_id = $1 and target_id = $2)
   or (player_id = $2 and target_id = $1)
`

func (q *Queries) DeletePlayerFriendBidirectional(ctx context.Context, playerID string, targetID string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlayerFriendBidirectional, playerID, targetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const friendRequestExists = `-- name: FriendRequestExists :one
select exists (select 1
               from player_friend_requests
               where player_id = $1
                 and target_id = $2)
`

func (q *Queries) FriendRequestExists(ctx context.Context, playerID string, targetID string) (bool, error) {
	row := q.db.QueryRow(ctx, friendRequestExists, playerID, targetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const friendshipExists = `-- name: FriendshipExists :one
select exists (select 1
               from player_friends
               where player_id = $1
                 and target_id = $2)
`

func (q *Queries) FriendshipExists(ctx context.Context, playerID string, targetID string) (bool, error) {
	row := q.db.QueryRow(ctx, friendshipExists, playerID, targetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getIncomingFriendRequests = `-- name: GetIncomingFriendRequests :many
select pfr.player_id, pd.username, pfr.created_at
from player_friend_requests pfr
         join player_data pd on pd.id = pfr.player_id
where pfr.target_id = $1
limit $2 offset $3
`

type GetIncomingFriendRequestsRow struct {
	PlayerID  string    `json:"playerId"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) GetIncomingFriendRequests(ctx context.Context, targetID string, limit int32, offset int32) ([]GetIncomingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, getIncomingFriendRequests, targetID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIncomingFriendRequestsRow{}
	for rows.Next() {
		var i GetIncomingFriendRequestsRow
		if err := rows.Scan(&i.PlayerID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutgoingFriendRequests = `-- name: GetOutgoingFriendRequests :many
select pfr.target_id, pd.username, pfr.created_at
from player_friend_requests pfr
         join player_data pd on pd.id = pfr.target_id
where pfr.player_id = $1
limit $2 offset $3
`

type GetOutgoingFriendRequestsRow struct {
	TargetID  string    `json:"targetId"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) GetOutgoingFriendRequests(ctx context.Context, playerID string, limit int32, offset int32) ([]GetOutgoingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, getOutgoingFriendRequests, playerID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOutgoingFriendRequestsRow{}
	for rows.Next() {
		var i GetOutgoingFriendRequestsRow
		if err := rows.Scan(&i.TargetID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerFriendUsage = `-- name: GetPlayerFriendUsage :one
select (select count(*) from player_friends where player_friends.player_id = $1)::int as friend_count,
       (select count(*)
        from player_friend_requests
        where player_friend_requests.player_id = $1)::int                             as outgoing_friend_request_count
`

type GetPlayerFriendUsageRow struct {
	FriendCount                int `json:"friendCount"`
	OutgoingFriendRequestCount int `json:"outgoingFriendRequestCount"`
}

func (q *Queries) GetPlayerFriendUsage(ctx context.Context, playerID string) (GetPlayerFriendUsageRow, error) {
	row := q.db.QueryRow(ctx, getPlayerFriendUsage, playerID)
	var i GetPlayerFriendUsageRow
	err := row.Scan(&i.FriendCount, &i.OutgoingFriendRequestCount)
	return i, err
}

const getPlayerFriends = `-- name: GetPlayerFriends :many
select pf.target_id, pd.username, pd.online, pd.last_online, pf.created_at
from player_friends pf
         join player_data pd on pd.id = pf.target_id
where pf.player_id = $1
order by pd.online desc,    -- ensure online friends are listed first
         pf.created_at desc -- just here for consistency in ordering
limit $2 offset $3
`

type GetPlayerFriendsRow struct {
	TargetID   string    `json:"targetId"`
	Username   string    `json:"username"`
	Online     bool      `json:"online"`
	LastOnline time.Time `json:"lastOnline"`
	CreatedAt  time.Time `json:"createdAt"`
}

func (q *Queries) GetPlayerFriends(ctx context.Context, playerID string, limit int32, offset int32) ([]GetPlayerFriendsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerFriends, playerID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerFriendsRow{}
	for rows.Next() {
		var i GetPlayerFriendsRow
		if err := rows.Scan(
			&i.TargetID,
			&i.Username,
			&i.Online,
			&i.LastOnline,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
