// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ip_history.sql

package db

import (
	"context"
)

const addPlayerIP = `-- name: AddPlayerIP :exec
insert into public.ip_history (player_id, address, first_seen, last_seen, seen_count)
values ($1, $2, now(), now(), 1)
on conflict (player_id, address) do update set last_seen  = excluded.last_seen,
                                               seen_count = ip_history.seen_count + 1
`

func (q *Queries) AddPlayerIP(ctx context.Context, playerID string, address string) error {
	_, err := q.db.Exec(ctx, addPlayerIP, playerID, address)
	return err
}

const getPlayerIPHistory = `-- name: GetPlayerIPHistory :many
select address
from public.ip_history
where player_id = $1
order by last_seen desc
`

func (q *Queries) GetPlayerIPHistory(ctx context.Context, playerID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getPlayerIPHistory, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersByIPs = `-- name: GetPlayersByIPs :many
select player_data.id, player_data.username
from ip_history
         inner join player_data on ip_history.player_id = player_data.id
where address = ANY ($1::text[])
group by player_data.id
`

type GetPlayersByIPsRow struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) GetPlayersByIPs(ctx context.Context, dollar_1 []string) ([]GetPlayersByIPsRow, error) {
	rows, err := q.db.Query(ctx, getPlayersByIPs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayersByIPsRow{}
	for rows.Next() {
		var i GetPlayersByIPsRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
