// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type ApiKey struct {
	ID        string
	KeyHash   string
	PlayerID  string
	CreatedAt *time.Time
	DeletedAt *time.Time
}

type PlayerData struct {
	ID          string
	Username    string
	FirstJoin   time.Time
	LastOnline  time.Time
	Playtime    int64
	Experience  int64
	BetaEnabled *bool
	Settings    PlayerSettings
	Coins       int64
	Cubits      int64
}
