// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type RelationshipStatus string

const (
	RelationshipStatusPending RelationshipStatus = "pending"
	RelationshipStatusFriend  RelationshipStatus = "friend"
	RelationshipStatusBlocked RelationshipStatus = "blocked"
)

func (e *RelationshipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RelationshipStatus(s)
	case string:
		*e = RelationshipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RelationshipStatus: %T", src)
	}
	return nil
}

type NullRelationshipStatus struct {
	RelationshipStatus RelationshipStatus `json:"relationshipStatus"`
	Valid              bool               `json:"valid"` // Valid is true if RelationshipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRelationshipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RelationshipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RelationshipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRelationshipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RelationshipStatus), nil
}

type ApiKey struct {
	ID        string     `json:"id"`
	KeyHash   string     `json:"keyHash"`
	PlayerID  string     `json:"playerId"`
	CreatedAt *time.Time `json:"createdAt"`
	DeletedAt *time.Time `json:"deletedAt"`
}

type PendingVerification struct {
	Type       string    `json:"type"`
	UserID     string    `json:"userId"`
	UserSecret string    `json:"userSecret"`
	Expiration time.Time `json:"expiration"`
}

type PlayerData struct {
	ID          string         `json:"id"`
	Username    string         `json:"username"`
	FirstJoin   time.Time      `json:"firstJoin"`
	LastOnline  time.Time      `json:"lastOnline"`
	Playtime    int            `json:"playtime"`
	Experience  int            `json:"experience"`
	BetaEnabled *bool          `json:"betaEnabled"`
	Settings    PlayerSettings `json:"settings"`
	Coins       int            `json:"coins"`
	Cubits      int            `json:"cubits"`
}

type PlayerRelationship struct {
	PlayerID  string             `json:"playerId"`
	TargetID  string             `json:"targetId"`
	Status    RelationshipStatus `json:"status"`
	CreatedAt time.Time          `json:"createdAt"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

type PlayerTotp struct {
	PlayerID      string             `json:"playerId"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	Active        *bool              `json:"active"`
	Key           []byte             `json:"key"`
	RecoveryCodes []string           `json:"recoveryCodes"`
}

type Punishment struct {
	ID            int        `json:"id"`
	PlayerID      string     `json:"playerId"`
	ExecutorID    string     `json:"executorId"`
	Type          string     `json:"type"`
	CreatedAt     time.Time  `json:"createdAt"`
	LadderID      *string    `json:"ladderId"`
	Comment       string     `json:"comment"`
	ExpiresAt     *time.Time `json:"expiresAt"`
	RevokedBy     *string    `json:"revokedBy"`
	RevokedAt     *time.Time `json:"revokedAt"`
	RevokedReason *string    `json:"revokedReason"`
}
