// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifcations.sql

package db

import (
	"context"
	"time"
)

const deleteNotification = `-- name: DeleteNotification :execrows
update player_notifications
set deleted_at = now()
where player_id = $1
  and id = $2
  and deleted_at is null
`

func (q *Queries) DeleteNotification(ctx context.Context, playerID string, iD string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotification, playerID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationCount = `-- name: GetNotificationCount :one
select count(*)
from player_notifications
where player_id = $1
  and deleted_at is null
  and (expires_at is null or expires_at > now())
  and (not $2 or read_at is null)
`

func (q *Queries) GetNotificationCount(ctx context.Context, playerID string, column2 interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, getNotificationCount, playerID, column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNotifications = `-- name: GetNotifications :many
select id, type, key, data, created_at, read_at, expires_at
from player_notifications
where player_id = $1
  and deleted_at is null
  and (expires_at is null or expires_at > now())
  and (not $4 or read_at is null)
order by created_at desc
limit $2 offset $3
`

type GetNotificationsParams struct {
	PlayerID string      `json:"playerId"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Column4  interface{} `json:"column4"`
}

type GetNotificationsRow struct {
	ID        string          `json:"id"`
	Type      string          `json:"type"`
	Key       string          `json:"key"`
	Data      *map[string]any `json:"data"`
	CreatedAt time.Time       `json:"createdAt"`
	ReadAt    *time.Time      `json:"readAt"`
	ExpiresAt *time.Time      `json:"expiresAt"`
}

func (q *Queries) GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]GetNotificationsRow, error) {
	rows, err := q.db.Query(ctx, getNotifications,
		arg.PlayerID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNotificationsRow{}
	for rows.Next() {
		var i GetNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Key,
			&i.Data,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
update player_notifications
set read_at = now()
where player_id = $1
  and id = $2
`

func (q *Queries) MarkNotificationRead(ctx context.Context, playerID string, iD string) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, playerID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationUnread = `-- name: MarkNotificationUnread :execrows
update player_notifications
set read_at = null
where player_id = $1
  and id = $2
`

func (q *Queries) MarkNotificationUnread(ctx context.Context, playerID string, iD string) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationUnread, playerID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unsafe_AddNotification = `-- name: Unsafe_AddNotification :exec
insert into player_notifications (id, type, key, player_id, data, expires_at)
values (gen_random_uuid(), $1, $2, $3, $4, $5)
`

type Unsafe_AddNotificationParams struct {
	Type      string          `json:"type"`
	Key       string          `json:"key"`
	PlayerID  string          `json:"playerId"`
	Data      *map[string]any `json:"data"`
	ExpiresAt *time.Time      `json:"expiresAt"`
}

func (q *Queries) Unsafe_AddNotification(ctx context.Context, arg Unsafe_AddNotificationParams) error {
	_, err := q.db.Exec(ctx, unsafe_AddNotification,
		arg.Type,
		arg.Key,
		arg.PlayerID,
		arg.Data,
		arg.ExpiresAt,
	)
	return err
}

const unsafe_DeleteNotification = `-- name: Unsafe_DeleteNotification :exec
delete
from player_notifications
where type = $1
  and key = $2
  and player_id = $3
`

func (q *Queries) Unsafe_DeleteNotification(ctx context.Context, type_ string, key string, playerID string) error {
	_, err := q.db.Exec(ctx, unsafe_DeleteNotification, type_, key, playerID)
	return err
}
