// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payments.sql

package db

import (
	"context"
	"time"
)

const createPendingTransaction = `-- name: CreatePendingTransaction :exec
insert into public.pending_tebex_transactions (player_id, created_at, username, checkout_id)
values ($1, now(), $2, $3)
`

func (q *Queries) CreatePendingTransaction(ctx context.Context, playerID string, username string, checkoutID string) error {
	_, err := q.db.Exec(ctx, createPendingTransaction, playerID, username, checkoutID)
	return err
}

const createTebexState = `-- name: CreateTebexState :execrows
insert into tebex_state (tx_id, changes)
values ($1, $2)
on conflict do nothing
`

func (q *Queries) CreateTebexState(ctx context.Context, txID string, changes []byte) (int64, error) {
	result, err := q.db.Exec(ctx, createTebexState, txID, changes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingTransactionByCheckoutId = `-- name: GetPendingTransactionByCheckoutId :one
select basket_id, username
from pending_tebex_transactions
where checkout_id = $1
`

type GetPendingTransactionByCheckoutIdRow struct {
	BasketID *string `json:"basketId"`
	Username string  `json:"username"`
}

func (q *Queries) GetPendingTransactionByCheckoutId(ctx context.Context, checkoutID string) (GetPendingTransactionByCheckoutIdRow, error) {
	row := q.db.QueryRow(ctx, getPendingTransactionByCheckoutId, checkoutID)
	var i GetPendingTransactionByCheckoutIdRow
	err := row.Scan(&i.BasketID, &i.Username)
	return i, err
}

const logTebexEvent = `-- name: LogTebexEvent :exec
insert into tebex_events (event_id, timestamp, raw)
values ($1, $2, $3)
`

func (q *Queries) LogTebexEvent(ctx context.Context, eventID string, timestamp time.Time, raw []byte) error {
	_, err := q.db.Exec(ctx, logTebexEvent, eventID, timestamp, raw)
	return err
}

const resolvePendingTransaction = `-- name: ResolvePendingTransaction :exec
update pending_tebex_transactions
set basket_id = $2
where checkout_id = $1
`

func (q *Queries) ResolvePendingTransaction(ctx context.Context, checkoutID string, basketID *string) error {
	_, err := q.db.Exec(ctx, resolvePendingTransaction, checkoutID, basketID)
	return err
}
