// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: player_relationships.sql

package db

import (
	"context"
	"time"
)

const createRelationship = `-- name: CreateRelationship :one
insert into player_relationship (player_id, target_id, status)
values ($1, $2, $3)
returning player_id, target_id, status, created_at, updated_at
`

func (q *Queries) CreateRelationship(ctx context.Context, playerID string, targetID string, status RelationshipStatus) (*PlayerRelationship, error) {
	row := q.db.QueryRow(ctx, createRelationship, playerID, targetID, status)
	var i PlayerRelationship
	err := row.Scan(
		&i.PlayerID,
		&i.TargetID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteRelationship = `-- name: DeleteRelationship :execrows
delete from player_relationship
where (player_id = $1 and target_id = $2)
   or ($3::bool and player_id = $2 and target_id = $1)
`

func (q *Queries) DeleteRelationship(ctx context.Context, playerID string, targetID string, bidirectional bool) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRelationship, playerID, targetID, bidirectional)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIncomingFriendRequests = `-- name: GetIncomingFriendRequests :many
select pr.player_id, pd.username, pr.created_at
from player_relationship pr
         join player_data pd on pd.id = pr.player_id
where pr.target_id = $1
  and pr.status = 'pending'
`

type GetIncomingFriendRequestsRow struct {
	PlayerID  string    `json:"playerId"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) GetIncomingFriendRequests(ctx context.Context, targetID string) ([]*GetIncomingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, getIncomingFriendRequests, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetIncomingFriendRequestsRow{}
	for rows.Next() {
		var i GetIncomingFriendRequestsRow
		if err := rows.Scan(&i.PlayerID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationship = `-- name: GetRelationship :many
select player_id, target_id, status, created_at, updated_at
from player_relationship
where (player_id = $1 and target_id = $2)
   or ($3::bool and player_id = $2 and target_id = $1)
`

func (q *Queries) GetRelationship(ctx context.Context, playerID string, targetID string, bidirectional bool) ([]*PlayerRelationship, error) {
	rows, err := q.db.Query(ctx, getRelationship, playerID, targetID, bidirectional)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PlayerRelationship{}
	for rows.Next() {
		var i PlayerRelationship
		if err := rows.Scan(
			&i.PlayerID,
			&i.TargetID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationships = `-- name: GetRelationships :many
select pr.target_id as player_id, pd.username, pr.created_at
from player_relationship pr
         join player_data pd on pd.id = pr.target_id
where pr.player_id = $1
  and pr.status = $2
`

type GetRelationshipsRow struct {
	PlayerID  string    `json:"playerId"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) GetRelationships(ctx context.Context, playerID string, status RelationshipStatus) ([]*GetRelationshipsRow, error) {
	rows, err := q.db.Query(ctx, getRelationships, playerID, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRelationshipsRow{}
	for rows.Next() {
		var i GetRelationshipsRow
		if err := rows.Scan(&i.PlayerID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelationshipStatus = `-- name: UpdateRelationshipStatus :one
update player_relationship
set status = $3,
    updated_at = now()
where player_id = $1
  and target_id = $2
returning player_id, target_id, status, created_at, updated_at
`

func (q *Queries) UpdateRelationshipStatus(ctx context.Context, playerID string, targetID string, status RelationshipStatus) (*PlayerRelationship, error) {
	row := q.db.QueryRow(ctx, updateRelationshipStatus, playerID, targetID, status)
	var i PlayerRelationship
	err := row.Scan(
		&i.PlayerID,
		&i.TargetID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
