// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: player_data.sql

package db

import (
	"context"
	"time"
)

const activateTOTP = `-- name: ActivateTOTP :one
update player_totp
set active = true
where player_id = $1
  and key = $2
  and active = false
returning 1
`

func (q *Queries) ActivateTOTP(ctx context.Context, playerID string, key []byte) (int32, error) {
	row := q.db.QueryRow(ctx, activateTOTP, playerID, key)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const addTOTP = `-- name: AddTOTP :execrows
insert into player_totp (player_id, active, key, recovery_codes)
values ($1, $2, $3, $4)
on conflict (player_id)
  do update set key            = excluded.key,
                recovery_codes = excluded.recovery_codes,
                created_at     = now()
where player_totp.active = false
`

type AddTOTPParams struct {
	PlayerID      string   `json:"playerId"`
	Active        *bool    `json:"active"`
	Key           []byte   `json:"key"`
	RecoveryCodes []string `json:"recoveryCodes"`
}

func (q *Queries) AddTOTP(ctx context.Context, arg AddTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTOTP,
		arg.PlayerID,
		arg.Active,
		arg.Key,
		arg.RecoveryCodes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPlayerData = `-- name: CreatePlayerData :one
insert into player_data (id, username, first_join, last_online)
values ($1, $2, now(), now())
returning id, username, first_join, last_online, playtime, experience, beta_enabled, settings, coins, cubits
`

func (q *Queries) CreatePlayerData(ctx context.Context, iD string, username string) (*PlayerData, error) {
	row := q.db.QueryRow(ctx, createPlayerData, iD, username)
	var i PlayerData
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstJoin,
		&i.LastOnline,
		&i.Playtime,
		&i.Experience,
		&i.BetaEnabled,
		&i.Settings,
		&i.Coins,
		&i.Cubits,
	)
	return &i, err
}

const deleteTOTP = `-- name: DeleteTOTP :exec
delete
from player_totp
where player_id = $1
`

func (q *Queries) DeleteTOTP(ctx context.Context, playerID string) error {
	_, err := q.db.Exec(ctx, deleteTOTP, playerID)
	return err
}

const getPlayerData = `-- name: GetPlayerData :one
select id, username, first_join, last_online, playtime, experience, beta_enabled, settings, coins, cubits
from player_data
where id = $1
limit 1
`

func (q *Queries) GetPlayerData(ctx context.Context, id string) (*PlayerData, error) {
	row := q.db.QueryRow(ctx, getPlayerData, id)
	var i PlayerData
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstJoin,
		&i.LastOnline,
		&i.Playtime,
		&i.Experience,
		&i.BetaEnabled,
		&i.Settings,
		&i.Coins,
		&i.Cubits,
	)
	return &i, err
}

const getPlayerStats = `-- name: GetPlayerStats :one
select count(*), sum(playtime)
from public.player_data
`

type GetPlayerStatsRow struct {
	Count int64 `json:"count"`
	Sum   int64 `json:"sum"`
}

func (q *Queries) GetPlayerStats(ctx context.Context) (*GetPlayerStatsRow, error) {
	row := q.db.QueryRow(ctx, getPlayerStats)
	var i GetPlayerStatsRow
	err := row.Scan(&i.Count, &i.Sum)
	return &i, err
}

const getTOTP = `-- name: GetTOTP :one
select player_id, created_at, active, key, recovery_codes
from player_totp
where player_id = $1
`

func (q *Queries) GetTOTP(ctx context.Context, playerID string) (*PlayerTotp, error) {
	row := q.db.QueryRow(ctx, getTOTP, playerID)
	var i PlayerTotp
	err := row.Scan(
		&i.PlayerID,
		&i.CreatedAt,
		&i.Active,
		&i.Key,
		&i.RecoveryCodes,
	)
	return &i, err
}

const lookupPlayerByIdOrUsername = `-- name: LookupPlayerByIdOrUsername :one
select id
from public.player_data
where id = $1
   or lower(username) = lower($2)
`

func (q *Queries) LookupPlayerByIdOrUsername(ctx context.Context, iD string, lower string) (string, error) {
	row := q.db.QueryRow(ctx, lookupPlayerByIdOrUsername, iD, lower)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lookupPlayerByUsername = `-- name: LookupPlayerByUsername :one
select id
from public.player_data
where lower(username) = lower($1)
`

func (q *Queries) LookupPlayerByUsername(ctx context.Context, lower string) (string, error) {
	row := q.db.QueryRow(ctx, lookupPlayerByUsername, lower)
	var id string
	err := row.Scan(&id)
	return id, err
}

const playerExistsById = `-- name: PlayerExistsById :one
select exists (select 1
               from public.player_data
               where id = $1)
`

func (q *Queries) PlayerExistsById(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, playerExistsById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const searchPlayersFuzzy = `-- name: SearchPlayersFuzzy :many

select id, username
from player_data
where username ~* $1
limit 25
`

type SearchPlayersFuzzyRow struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

// SQLC is a bit dumb and redeclares the 'experience' variable so we have to rename it
func (q *Queries) SearchPlayersFuzzy(ctx context.Context, username string) ([]*SearchPlayersFuzzyRow, error) {
	rows, err := q.db.Query(ctx, searchPlayersFuzzy, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SearchPlayersFuzzyRow
	for rows.Next() {
		var i SearchPlayersFuzzyRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerData = `-- name: UpdatePlayerData :exec
update public.player_data
set username     = coalesce($2, username),
    last_online  = coalesce($3, last_online),
    playtime     = coalesce($4, playtime),
    beta_enabled = coalesce($5, beta_enabled),
    settings     = coalesce($6, settings)
where id = $1
`

type UpdatePlayerDataParams struct {
	ID          string         `json:"id"`
	Username    *string        `json:"username"`
	LastOnline  *time.Time     `json:"lastOnline"`
	Playtime    *int           `json:"playtime"`
	BetaEnabled *bool          `json:"betaEnabled"`
	Settings    PlayerSettings `json:"settings"`
}

func (q *Queries) UpdatePlayerData(ctx context.Context, arg UpdatePlayerDataParams) error {
	_, err := q.db.Exec(ctx, updatePlayerData,
		arg.ID,
		arg.Username,
		arg.LastOnline,
		arg.Playtime,
		arg.BetaEnabled,
		arg.Settings,
	)
	return err
}

const addExperience = `-- name: addExperience :one
update public.player_data
set experience = experience + $2
where id = $1
  and experience + $2 >= 0
returning experience as exp
`

func (q *Queries) addExperience(ctx context.Context, iD string, experience int) (int, error) {
	row := q.db.QueryRow(ctx, addExperience, iD, experience)
	var exp int
	err := row.Scan(&exp)
	return exp, err
}
