// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: player_data.sql

package db

import (
	"context"
)

const getPlayerData = `-- name: GetPlayerData :one
select id, username, first_join, last_online, playtime, experience, beta_enabled, settings, coins, cubits
from player_data
where id = $1
limit 1
`

func (q *Queries) GetPlayerData(ctx context.Context, id string) (*PlayerDatum, error) {
	row := q.db.QueryRow(ctx, getPlayerData, id)
	var i PlayerDatum
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstJoin,
		&i.LastOnline,
		&i.Playtime,
		&i.Experience,
		&i.BetaEnabled,
		&i.Settings,
		&i.Coins,
		&i.Cubits,
	)
	return &i, err
}
