// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: punishments.sql

package db

import (
	"context"
	"time"
)

const createPunishment = `-- name: CreatePunishment :one
insert into punishments (player_id, executor_id, type, created_at, ladder_id, comment, expires_at)
values ($1, $2, $3, now(), $4, $5, $6)
returning id, player_id, executor_id, type, created_at, ladder_id, comment, expires_at, revoked_by, revoked_at, revoked_reason
`

type CreatePunishmentParams struct {
	PlayerID   string     `json:"playerId"`
	ExecutorID string     `json:"executorId"`
	Type       string     `json:"type"`
	LadderID   *string    `json:"ladderId"`
	Comment    string     `json:"comment"`
	ExpiresAt  *time.Time `json:"expiresAt"`
}

func (q *Queries) CreatePunishment(ctx context.Context, arg CreatePunishmentParams) (*Punishment, error) {
	row := q.db.QueryRow(ctx, createPunishment,
		arg.PlayerID,
		arg.ExecutorID,
		arg.Type,
		arg.LadderID,
		arg.Comment,
		arg.ExpiresAt,
	)
	var i Punishment
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.ExecutorID,
		&i.Type,
		&i.CreatedAt,
		&i.LadderID,
		&i.Comment,
		&i.ExpiresAt,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return &i, err
}

const getActivePunishment = `-- name: GetActivePunishment :one
select id, player_id, executor_id, type, created_at, ladder_id, comment,
       expires_at, revoked_by, revoked_at, revoked_reason
from punishments
where type = $1
  and player_id = $2
  and (expires_at is null or expires_at > now())
  and revoked_by is null
order by created_at desc
limit 1
`

func (q *Queries) GetActivePunishment(ctx context.Context, type_ string, playerID string) (*Punishment, error) {
	row := q.db.QueryRow(ctx, getActivePunishment, type_, playerID)
	var i Punishment
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.ExecutorID,
		&i.Type,
		&i.CreatedAt,
		&i.LadderID,
		&i.Comment,
		&i.ExpiresAt,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return &i, err
}

const revokePunishment = `-- name: RevokePunishment :one
update punishments
set revoked_by     = $3,
    revoked_at     = now(),
    revoked_reason = $4
where type = $1
  and player_id = $2
  and (expires_at is null or expires_at > now())
  and revoked_by is null
returning id, player_id, executor_id, type, created_at, ladder_id, comment, expires_at, revoked_by, revoked_at, revoked_reason
`

type RevokePunishmentParams struct {
	Type          string  `json:"type"`
	PlayerID      string  `json:"playerId"`
	RevokedBy     *string `json:"revokedBy"`
	RevokedReason *string `json:"revokedReason"`
}

func (q *Queries) RevokePunishment(ctx context.Context, arg RevokePunishmentParams) (*Punishment, error) {
	row := q.db.QueryRow(ctx, revokePunishment,
		arg.Type,
		arg.PlayerID,
		arg.RevokedBy,
		arg.RevokedReason,
	)
	var i Punishment
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.ExecutorID,
		&i.Type,
		&i.CreatedAt,
		&i.LadderID,
		&i.Comment,
		&i.ExpiresAt,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return &i, err
}

const searchPunishments = `-- name: SearchPunishments :many
select id, player_id, executor_id, type, created_at, ladder_id, comment, expires_at, revoked_by, revoked_at, revoked_reason
from punishments
where type = $1
  and player_id = $2
  and (executor_id = $3 or $3 = '')
  and (ladder_id = $4 or $4 = '' or $4 is null)
`

type SearchPunishmentsParams struct {
	Type       string  `json:"type"`
	PlayerID   string  `json:"playerId"`
	ExecutorID string  `json:"executorId"`
	LadderID   *string `json:"ladderId"`
}

func (q *Queries) SearchPunishments(ctx context.Context, arg SearchPunishmentsParams) ([]*Punishment, error) {
	rows, err := q.db.Query(ctx, searchPunishments,
		arg.Type,
		arg.PlayerID,
		arg.ExecutorID,
		arg.LadderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Punishment
	for rows.Next() {
		var i Punishment
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.ExecutorID,
			&i.Type,
			&i.CreatedAt,
			&i.LadderID,
			&i.Comment,
			&i.ExpiresAt,
			&i.RevokedBy,
			&i.RevokedAt,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
