// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: punishment.sql

package db

import (
	"context"
)

const test123 = `-- name: Test123 :one
select 1
`

func (q *Queries) Test123(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, test123)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
