// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recaps.sql

package db

import (
	"context"
)

const getRecapById = `-- name: GetRecapById :one
select recap.id, player.id as player_id, player.username, recap.year, recap.data
from player_recaps recap
  inner join player_data player on player.id = recap.player_id
where recap.id = $1
`

type GetRecapByIdRow struct {
	ID       string         `json:"id"`
	PlayerID string         `json:"playerId"`
	Username string         `json:"username"`
	Year     int            `json:"year"`
	Data     map[string]any `json:"data"`
}

func (q *Queries) GetRecapById(ctx context.Context, id string) (GetRecapByIdRow, error) {
	row := q.db.QueryRow(ctx, getRecapById, id)
	var i GetRecapByIdRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Username,
		&i.Year,
		&i.Data,
	)
	return i, err
}

const getRecapByPlayerId = `-- name: GetRecapByPlayerId :one
select recap.id, player.id as player_id, player.username, recap.year, recap.data
from player_recaps recap
  inner join player_data player on player.id = recap.player_id
where player.id = $1 and recap.year = $2
`

type GetRecapByPlayerIdRow struct {
	ID       string         `json:"id"`
	PlayerID string         `json:"playerId"`
	Username string         `json:"username"`
	Year     int            `json:"year"`
	Data     map[string]any `json:"data"`
}

func (q *Queries) GetRecapByPlayerId(ctx context.Context, iD string, year int) (GetRecapByPlayerIdRow, error) {
	row := q.db.QueryRow(ctx, getRecapByPlayerId, iD, year)
	var i GetRecapByPlayerIdRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Username,
		&i.Year,
		&i.Data,
	)
	return i, err
}
