openapi: 3.0.2
info:
  title: Obungus Tower API
  version: "2"
paths:
  /review_queue:
    get:
      operationId: getBoxFromReviewQueue
      summary: Get the next box in the review queue
      description: long description TODO
      parameters:
        - name: player
          in: query
          description: The player to get the box for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required: [ id, createdAt ]
                properties:
                  id:
                    type: string
                  playerId:
                    type: string
                  createdAt:
                    type: string
                  name:
                    type: string
                  shape:
                    type: string
                  legacyUsername:
                    type: string
                  schematicData:
                    type: string
        '404':
          description: No boxes in the review queue

components:
  schemas: {}
