// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"
	"time"
)

const createLaunchGrant = `-- name: CreateLaunchGrant :exec
insert into api_launch_grants (code_hash, player_id, map_id, expires_at)
values ($1, $2, $3, $4)
`

type CreateLaunchGrantParams struct {
	CodeHash  []byte
	PlayerID  string
	MapID     *string
	ExpiresAt time.Time
}

func (q *Queries) CreateLaunchGrant(ctx context.Context, arg CreateLaunchGrantParams) error {
	_, err := q.db.Exec(ctx, createLaunchGrant,
		arg.CodeHash,
		arg.PlayerID,
		arg.MapID,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :one
insert into api_sessions (client_id, player_id, idle_expires_at, absolute_expires_at)
values ($1, $2, $3, $4)
returning id
`

type CreateSessionParams struct {
	ClientID          string
	PlayerID          string
	IdleExpiresAt     time.Time
	AbsoluteExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ClientID,
		arg.PlayerID,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getActiveSession = `-- name: GetActiveSession :one
select sess.player_id,
       client.kind             as client_kind,
       client.key_id           as client_key_id,
       sess.absolute_expires_at as absolute_expires_at
from api_sessions sess
       inner join api_clients client on sess.client_id = client.id
where sess.id = $1
  and sess.revoked_at is null
  and sess.idle_expires_at > now()
  and sess.absolute_expires_at > now()
`

type GetActiveSessionRow struct {
	PlayerID          string
	ClientKind        ApiClientKind
	ClientKeyID       string
	AbsoluteExpiresAt time.Time
}

func (q *Queries) GetActiveSession(ctx context.Context, id string) (*GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, id)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.PlayerID,
		&i.ClientKind,
		&i.ClientKeyID,
		&i.AbsoluteExpiresAt,
	)
	return &i, err
}

const getLaunchGrantForRedeem = `-- name: GetLaunchGrantForRedeem :one
select id, player_id, map_id
from api_launch_grants
where code_hash = $1
  and redeemed_at is null
  and expires_at > now()
for update
`

type GetLaunchGrantForRedeemRow struct {
	ID       string
	PlayerID string
	MapID    *string
}

func (q *Queries) GetLaunchGrantForRedeem(ctx context.Context, codeHash []byte) (*GetLaunchGrantForRedeemRow, error) {
	row := q.db.QueryRow(ctx, getLaunchGrantForRedeem, codeHash)
	var i GetLaunchGrantForRedeemRow
	err := row.Scan(&i.ID, &i.PlayerID, &i.MapID)
	return &i, err
}

const markLaunchGrantRedeemed = `-- name: MarkLaunchGrantRedeemed :exec
update api_launch_grants
set redeemed_at         = now(),
    redeemed_session_id = $2
where id = $1
`

func (q *Queries) MarkLaunchGrantRedeemed(ctx context.Context, iD string, redeemedSessionID *string) error {
	_, err := q.db.Exec(ctx, markLaunchGrantRedeemed, iD, redeemedSessionID)
	return err
}

const revokeSessionsForClientAccount = `-- name: RevokeSessionsForClientAccount :exec
update api_sessions
set revoked_at = now()
where client_id = $1
  and player_id = $2
  and revoked_at is null
`

func (q *Queries) RevokeSessionsForClientAccount(ctx context.Context, clientID string, playerID string) error {
	_, err := q.db.Exec(ctx, revokeSessionsForClientAccount, clientID, playerID)
	return err
}

const touchSession = `-- name: TouchSession :exec
update api_sessions
set last_active_at  = now(),
    idle_expires_at = $2
where id = $1
`

func (q *Queries) TouchSession(ctx context.Context, iD string, idleExpiresAt time.Time) error {
	_, err := q.db.Exec(ctx, touchSession, iD, idleExpiresAt)
	return err
}

const upsertApiClient = `-- name: UpsertApiClient :one
insert into api_clients (kind, public_key, key_id, label)
values ($1, $2, $3, $4)
on conflict (key_id) do update set last_seen_at = now()
returning id
`

type UpsertApiClientParams struct {
	Kind      ApiClientKind
	PublicKey []byte
	KeyID     string
	Label     *string
}

func (q *Queries) UpsertApiClient(ctx context.Context, arg UpsertApiClientParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertApiClient,
		arg.Kind,
		arg.PublicKey,
		arg.KeyID,
		arg.Label,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
