// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: map_states.sql

package db

import (
	"context"
)

const insertMapState = `-- name: InsertMapState :one
insert into map_states(id, map_id, server, state)
values ($1, $2, $3, $4)
returning id, map_id, server, state
`

type InsertMapStateParams struct {
	ID     string
	MapID  string
	Server string
	State  string
}

func (q *Queries) InsertMapState(ctx context.Context, arg InsertMapStateParams) (*MapState, error) {
	row := q.db.QueryRow(ctx, insertMapState,
		arg.ID,
		arg.MapID,
		arg.Server,
		arg.State,
	)
	var i MapState
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Server,
		&i.State,
	)
	return &i, err
}
