// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: map_worlds.sql

package db

import (
	"context"
)

const deleteMapWorld = `-- name: DeleteMapWorld :exec
delete
from map_worlds
where id = $1
`

func (q *Queries) DeleteMapWorld(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMapWorld, id)
	return err
}

const getWorldsForMap = `-- name: GetWorldsForMap :many
select id, map_id, server_id, created_at
from map_worlds
where map_id = $1
`

func (q *Queries) GetWorldsForMap(ctx context.Context, mapID string) ([]*MapWorld, error) {
	rows, err := q.db.Query(ctx, getWorldsForMap, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*MapWorld
	for rows.Next() {
		var i MapWorld
		if err := rows.Scan(
			&i.ID,
			&i.MapID,
			&i.ServerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMapWorld = `-- name: InsertMapWorld :exec
insert into map_worlds (id, map_id, server_id)
values ($1, $2, $3)
returning id, map_id, server_id, created_at
`

func (q *Queries) InsertMapWorld(ctx context.Context, iD string, mapID string, serverID string) error {
	_, err := q.db.Exec(ctx, insertMapWorld, iD, mapID, serverID)
	return err
}
