// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chat.sql

package db

import (
	"context"
	"time"
)

const insertChatMessage = `-- name: InsertChatMessage :exec
insert into chat_messages (timestamp, server_id, channel, sender, target, content, censored_by, censored_detail)
values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertChatMessageParams struct {
	Timestamp      time.Time
	ServerID       string
	Channel        string
	Sender         string
	Target         *string
	Content        string
	CensoredBy     *string
	CensoredDetail *string
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) error {
	_, err := q.db.Exec(ctx, insertChatMessage,
		arg.Timestamp,
		arg.ServerID,
		arg.Channel,
		arg.Sender,
		arg.Target,
		arg.Content,
		arg.CensoredBy,
		arg.CensoredDetail,
	)
	return err
}
