// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type MapState struct {
	ID     string
	MapID  string
	Server string
	State  string
}

type PlayerSession struct {
	PlayerID        string
	CreatedAt       time.Time
	ProxyID         string
	ServerID        *string
	Hidden          bool
	Username        *string
	SkinTexture     string
	SkinSignature   string
	PType           *string
	PState          *string
	PInstanceID     *string
	PMapID          *string
	PStartTime      *time.Time
	LastSeen        pgtype.Timestamptz
	ProtocolVersion int32
}

type ServerState struct {
	ID          string
	Role        string
	StartTime   time.Time
	Status      int32
	ClusterIp   string
	StatusV2    string
	StatusSince time.Time
}
